# -*- coding: utf-8 -*-
"""EQ branch names + descriptions — the last English in the EQ result panel."""
import os, sys
sys.path.insert(0, os.path.join(os.getcwd(), '_build'))
import tools as T

NAMES = ["eq_b_p","eq_b_p_desc","eq_b_u","eq_b_u_desc","eq_b_n","eq_b_n_desc","eq_b_m","eq_b_m_desc"]

K = {
"en": ["Perceiving Emotions","Your ability to accurately read emotions in faces, voices, and surroundings.","Using Emotions","How well you leverage emotional states to enhance thinking and creativity.","Understanding Emotions","Your knowledge of emotional dynamics — how they blend, evolve, and influence behavior.","Managing Emotions","Your capacity to regulate your own emotions and positively influence others."],
"af": ["Waarneming van Emosies","Jou vermoë om emosies akkuraat te lees in gesigte, stemme en die omgewing.","Gebruik van Emosies","Hoe goed jy emosionele toestande inspan om denke en kreatiwiteit te versterk.","Begrip van Emosies","Jou kennis van emosionele dinamika — hoe emosies meng, ontwikkel en gedrag beïnvloed.","Bestuur van Emosies","Jou vermoë om jou eie emosies te reguleer en ander positief te beïnvloed."],
"ar": ["إدراك المشاعر","قدرتك على قراءة المشاعر بدقة في الوجوه والأصوات والمحيط.","استخدام المشاعر","مدى توظيفك للحالات الشعورية لتعزيز التفكير والإبداع.","فهم المشاعر","معرفتك بديناميكيات المشاعر — كيف تمتزج وتتطور وتؤثر في السلوك.","إدارة المشاعر","قدرتك على تنظيم مشاعرك والتأثير الإيجابي في الآخرين."],
"bg": ["Разпознаване на емоции","Способността ви да разчитате точно емоциите по лица, гласове и обкръжение.","Използване на емоции","Доколко използвате емоционалните състояния, за да подсилите мисленето и творчеството.","Разбиране на емоции","Познанията ви за динамиката на емоциите — как се смесват, развиват и влияят на поведението.","Управление на емоции","Способността ви да регулирате собствените емоции и да влияете положително на другите."],
"cs": ["Vnímání emocí","Vaše schopnost přesně číst emoce ve tvářích, hlasech a okolí.","Využívání emocí","Jak dobře využíváte emoční stavy k posílení myšlení a tvořivosti.","Porozumění emocím","Vaše znalost dynamiky emocí — jak se mísí, vyvíjejí a ovlivňují chování.","Řízení emocí","Vaše schopnost regulovat vlastní emoce a pozitivně působit na druhé."],
"da": ["Opfattelse af følelser","Din evne til præcist at aflæse følelser i ansigter, stemmer og omgivelser.","Brug af følelser","Hvor godt du udnytter følelsestilstande til at styrke tænkning og kreativitet.","Forståelse af følelser","Din viden om følelsers dynamik — hvordan de blandes, udvikler sig og påvirker adfærd.","Håndtering af følelser","Din evne til at regulere egne følelser og påvirke andre positivt."],
"de": ["Emotionen wahrnehmen","Ihre Fähigkeit, Emotionen in Gesichtern, Stimmen und Umgebung genau zu lesen.","Emotionen nutzen","Wie gut Sie emotionale Zustände nutzen, um Denken und Kreativität zu stärken.","Emotionen verstehen","Ihr Wissen über emotionale Dynamik — wie Gefühle sich mischen, entwickeln und Verhalten prägen.","Emotionen steuern","Ihre Fähigkeit, eigene Emotionen zu regulieren und andere positiv zu beeinflussen."],
"el": ["Αντίληψη συναισθημάτων","Η ικανότητά σας να διαβάζετε με ακρίβεια συναισθήματα σε πρόσωπα, φωνές και περιβάλλον.","Χρήση συναισθημάτων","Πόσο καλά αξιοποιείτε τις συναισθηματικές καταστάσεις για να ενισχύσετε τη σκέψη και τη δημιουργικότητα.","Κατανόηση συναισθημάτων","Η γνώση σας για τη δυναμική των συναισθημάτων — πώς αναμειγνύονται, εξελίσσονται και επηρεάζουν τη συμπεριφορά.","Διαχείριση συναισθημάτων","Η ικανότητά σας να ρυθμίζετε τα συναισθήματά σας και να επηρεάζετε θετικά τους άλλους."],
"es": ["Percibir emociones","Tu capacidad para leer con precisión las emociones en rostros, voces y entorno.","Usar emociones","Hasta qué punto aprovechas los estados emocionales para potenciar el pensamiento y la creatividad.","Comprender emociones","Tu conocimiento de la dinámica emocional: cómo se mezclan, evolucionan e influyen en la conducta.","Gestionar emociones","Tu capacidad para regular tus propias emociones e influir positivamente en los demás."],
"et": ["Emotsioonide tajumine","Sinu võime lugeda emotsioone täpselt nägudelt, häälest ja ümbrusest.","Emotsioonide kasutamine","Kui hästi kasutad emotsionaalseid seisundeid mõtlemise ja loovuse toetamiseks.","Emotsioonide mõistmine","Sinu teadmised emotsioonide dünaamikast — kuidas need segunevad, arenevad ja mõjutavad käitumist.","Emotsioonide juhtimine","Sinu võime reguleerida oma emotsioone ja mõjutada teisi positiivselt."],
"fa": ["درک هیجان‌ها","توانایی شما در خواندن دقیق هیجان‌ها از چهره، صدا و محیط.","به‌کارگیری هیجان‌ها","اینکه چقدر از حالت‌های هیجانی برای تقویت تفکر و خلاقیت بهره می‌گیرید.","فهم هیجان‌ها","دانش شما از پویایی هیجان‌ها — اینکه چگونه درهم می‌آمیزند، تغییر می‌کنند و بر رفتار اثر می‌گذارند.","مدیریت هیجان‌ها","توان شما در تنظیم هیجان‌های خود و اثرگذاری مثبت بر دیگران."],
"fi": ["Tunteiden havaitseminen","Kykysi lukea tunteita tarkasti kasvoista, äänestä ja ympäristöstä.","Tunteiden hyödyntäminen","Kuinka hyvin hyödynnät tunnetiloja ajattelun ja luovuuden vahvistamiseen.","Tunteiden ymmärtäminen","Tietosi tunteiden dynamiikasta — miten ne sekoittuvat, kehittyvät ja ohjaavat käytöstä.","Tunteiden hallinta","Kykysi säädellä omia tunteitasi ja vaikuttaa muihin myönteisesti."],
"fr": ["Percevoir les émotions","Votre capacité à lire avec justesse les émotions sur les visages, dans les voix et l'environnement.","Utiliser les émotions","À quel point vous mobilisez les états émotionnels pour renforcer la pensée et la créativité.","Comprendre les émotions","Votre connaissance de la dynamique émotionnelle : comment les émotions se mêlent, évoluent et orientent le comportement.","Gérer les émotions","Votre capacité à réguler vos propres émotions et à influencer positivement autrui."],
"he": ["תפיסת רגשות","היכולת שלך לקרוא רגשות בדיוק מתוך הבעות פנים, טון דיבור וסביבה.","שימוש ברגשות","עד כמה אתה רותם מצבים רגשיים כדי לחדד חשיבה ויצירתיות.","הבנת רגשות","הידע שלך על הדינמיקה הרגשית — כיצד רגשות מתמזגים, מתפתחים ומשפיעים על התנהגות.","ניהול רגשות","היכולת שלך לווסת את רגשותיך ולהשפיע לטובה על אחרים."],
"hi": ["भावनाओं को पहचानना","चेहरों, आवाज़ों और परिवेश में भावनाओं को सटीक रूप से पढ़ने की आपकी क्षमता।","भावनाओं का उपयोग","आप भावनात्मक स्थितियों का उपयोग सोच और रचनात्मकता बढ़ाने में कितनी अच्छी तरह करते हैं।","भावनाओं को समझना","भावनात्मक गतिशीलता की आपकी समझ — वे कैसे मिलती हैं, बदलती हैं और व्यवहार को प्रभावित करती हैं।","भावनाओं का प्रबंधन","अपनी भावनाओं को नियंत्रित करने और दूसरों को सकारात्मक रूप से प्रभावित करने की आपकी क्षमता।"],
"hr": ["Opažanje emocija","Vaša sposobnost da točno čitate emocije s lica, iz glasa i okoline.","Korištenje emocija","Koliko dobro koristite emocionalna stanja za jačanje mišljenja i kreativnosti.","Razumijevanje emocija","Vaše poznavanje dinamike emocija — kako se miješaju, razvijaju i utječu na ponašanje.","Upravljanje emocijama","Vaša sposobnost da regulirate vlastite emocije i pozitivno utječete na druge."],
"hu": ["Érzelmek észlelése","Képessége, hogy pontosan olvassa az érzelmeket arcokról, hangból és a környezetből.","Érzelmek használata","Mennyire aknázza ki az érzelmi állapotokat a gondolkodás és a kreativitás erősítésére.","Érzelmek megértése","Tudása az érzelmi dinamikáról — hogyan keverednek, alakulnak és befolyásolják a viselkedést.","Érzelmek kezelése","Képessége, hogy szabályozza saját érzelmeit és pozitívan hasson másokra."],
"id": ["Memahami Emosi","Kemampuan Anda membaca emosi secara akurat dari wajah, suara, dan lingkungan.","Menggunakan Emosi","Seberapa baik Anda memanfaatkan keadaan emosi untuk menajamkan pemikiran dan kreativitas.","Mengerti Dinamika Emosi","Pengetahuan Anda tentang dinamika emosi — bagaimana emosi berbaur, berkembang, dan memengaruhi perilaku.","Mengelola Emosi","Kapasitas Anda mengatur emosi sendiri dan memengaruhi orang lain secara positif."],
"it": ["Percepire le emozioni","La tua capacità di leggere con precisione le emozioni nei volti, nelle voci e nell'ambiente.","Usare le emozioni","Quanto sfrutti gli stati emotivi per potenziare pensiero e creatività.","Comprendere le emozioni","La tua conoscenza della dinamica emotiva: come le emozioni si mescolano, evolvono e guidano il comportamento.","Gestire le emozioni","La tua capacità di regolare le tue emozioni e influenzare positivamente gli altri."],
"ja": ["感情の知覚","表情や声、周囲の状況から感情を正確に読み取る力です。","感情の活用","思考や創造性を高めるために感情の状態をどれだけ活かせているかです。","感情の理解","感情がどのように混ざり、変化し、行動に影響するかについての理解です。","感情の管理","自分の感情を整え、周囲によい影響を与える力です。"],
"ko": ["감정 인식","표정과 목소리, 주변 상황에서 감정을 정확히 읽어 내는 능력입니다.","감정 활용","사고와 창의성을 높이기 위해 감정 상태를 얼마나 잘 활용하는지를 뜻합니다.","감정 이해","감정이 어떻게 섞이고 변화하며 행동에 영향을 주는지에 대한 이해입니다.","감정 관리","자신의 감정을 조절하고 타인에게 긍정적인 영향을 주는 능력입니다."],
"lt": ["Emocijų suvokimas","Jūsų gebėjimas tiksliai perskaityti emocijas veiduose, balse ir aplinkoje.","Emocijų naudojimas","Kaip gerai pasitelkiate emocines būsenas mąstymui ir kūrybiškumui stiprinti.","Emocijų supratimas","Jūsų žinios apie emocijų dinamiką — kaip jos susilieja, kinta ir veikia elgesį.","Emocijų valdymas","Jūsų gebėjimas reguliuoti savo emocijas ir teigiamai veikti kitus."],
"lv": ["Emociju uztvere","Jūsu spēja precīzi nolasīt emocijas sejās, balsī un apkārtējā vidē.","Emociju izmantošana","Cik labi izmantojat emocionālos stāvokļus, lai stiprinātu domāšanu un radošumu.","Emociju izpratne","Jūsu zināšanas par emociju dinamiku — kā tās sajaucas, mainās un ietekmē uzvedību.","Emociju vadība","Jūsu spēja regulēt savas emocijas un pozitīvi ietekmēt citus."],
"mk": ["Согледување на емоции","Вашата способност точно да ги читате емоциите од лица, гласови и опкружување.","Користење на емоции","Колку добро ги користите емоционалните состојби за поттик на мислењето и креативноста.","Разбирање на емоции","Вашето познавање на динамиката на емоциите — како се мешаат, се менуваат и влијаат врз однесувањето.","Управување со емоции","Вашата способност да ги регулирате сопствените емоции и позитивно да влијаете врз другите."],
"ms": ["Mengesan Emosi","Keupayaan anda membaca emosi dengan tepat pada wajah, suara dan persekitaran.","Menggunakan Emosi","Sejauh mana anda memanfaatkan keadaan emosi untuk menajamkan pemikiran dan kreativiti.","Memahami Emosi","Pengetahuan anda tentang dinamika emosi — bagaimana emosi bercampur, berkembang dan mempengaruhi tingkah laku.","Mengurus Emosi","Kapasiti anda mengawal emosi sendiri dan mempengaruhi orang lain secara positif."],
"nl": ["Emoties waarnemen","Je vermogen om emoties nauwkeurig te lezen in gezichten, stemmen en omgeving.","Emoties gebruiken","Hoe goed je emotionele toestanden inzet om denken en creativiteit te versterken.","Emoties begrijpen","Je kennis van emotionele dynamiek — hoe emoties mengen, veranderen en gedrag sturen.","Emoties beheersen","Je vermogen om je eigen emoties te reguleren en anderen positief te beïnvloeden."],
"no": ["Oppfatte følelser","Din evne til å lese følelser presist i ansikter, stemmer og omgivelser.","Bruke følelser","Hvor godt du utnytter følelsestilstander til å styrke tenkning og kreativitet.","Forstå følelser","Din kunnskap om følelsenes dynamikk — hvordan de blandes, utvikler seg og påvirker atferd.","Håndtere følelser","Din evne til å regulere egne følelser og påvirke andre positivt."],
"pl": ["Postrzeganie emocji","Twoja zdolność trafnego odczytywania emocji z twarzy, głosu i otoczenia.","Wykorzystywanie emocji","Jak dobrze wykorzystujesz stany emocjonalne, by wzmocnić myślenie i kreatywność.","Rozumienie emocji","Twoja wiedza o dynamice emocji — jak się mieszają, zmieniają i wpływają na zachowanie.","Zarządzanie emocjami","Twoja zdolność regulowania własnych emocji i pozytywnego wpływania na innych."],
"pt": ["Percecionar emoções","A sua capacidade de ler com rigor as emoções em rostos, vozes e no ambiente.","Usar emoções","O quanto aproveita os estados emocionais para reforçar o pensamento e a criatividade.","Compreender emoções","O seu conhecimento da dinâmica emocional — como as emoções se misturam, evoluem e influenciam o comportamento.","Gerir emoções","A sua capacidade de regular as próprias emoções e influenciar positivamente os outros."],
"ro": ["Perceperea emoțiilor","Capacitatea ta de a citi cu precizie emoțiile de pe chipuri, din voce și din mediu.","Utilizarea emoțiilor","Cât de bine folosești stările emoționale pentru a susține gândirea și creativitatea.","Înțelegerea emoțiilor","Cunoașterea ta despre dinamica emoțiilor — cum se combină, evoluează și influențează comportamentul.","Gestionarea emoțiilor","Capacitatea ta de a-ți regla propriile emoții și de a-i influența pozitiv pe ceilalți."],
"ru": ["Распознавание эмоций","Ваша способность точно считывать эмоции по лицам, голосу и обстановке.","Использование эмоций","Насколько хорошо вы используете эмоциональные состояния для мышления и творчества.","Понимание эмоций","Ваши знания о динамике эмоций — как они смешиваются, меняются и влияют на поведение.","Управление эмоциями","Ваша способность регулировать собственные эмоции и положительно влиять на других."],
"sk": ["Vnímanie emócií","Vaša schopnosť presne čítať emócie z tvárí, hlasu a okolia.","Využívanie emócií","Ako dobre využívate emočné stavy na posilnenie myslenia a tvorivosti.","Porozumenie emóciám","Vaše znalosti o dynamike emócií — ako sa miešajú, vyvíjajú a ovplyvňujú správanie.","Zvládanie emócií","Vaša schopnosť regulovať vlastné emócie a pozitívne pôsobiť na druhých."],
"sl": ["Zaznavanje čustev","Vaša sposobnost natančno brati čustva z obrazov, iz glasu in okolice.","Uporaba čustev","Kako dobro izkoriščate čustvena stanja za krepitev mišljenja in ustvarjalnosti.","Razumevanje čustev","Vaše poznavanje dinamike čustev — kako se mešajo, razvijajo in vplivajo na vedenje.","Upravljanje čustev","Vaša sposobnost uravnavati lastna čustva in pozitivno vplivati na druge."],
"sq": ["Perceptimi i emocioneve","Aftësia juaj për të lexuar me saktësi emocionet në fytyra, zëra dhe mjedis.","Përdorimi i emocioneve","Sa mirë i shfrytëzoni gjendjet emocionale për të forcuar mendimin dhe krijimtarinë.","Kuptimi i emocioneve","Njohuritë tuaja për dinamikën e emocioneve — si përzihen, evoluojnë dhe ndikojnë në sjellje.","Menaxhimi i emocioneve","Aftësia juaj për të rregulluar emocionet tuaja dhe për të ndikuar pozitivisht te të tjerët."],
"sr": ["Опажање емоција","Ваша способност да тачно читате емоције са лица, из гласа и окружења.","Коришћење емоција","Колико добро користите емоционална стања да ојачате мишљење и креативност.","Разумевање емоција","Ваше познавање динамике емоција — како се мешају, развијају и утичу на понашање.","Управљање емоцијама","Ваша способност да регулишете сопствене емоције и позитивно утичете на друге."],
"sv": ["Uppfatta känslor","Din förmåga att exakt läsa känslor i ansikten, röster och omgivning.","Använda känslor","Hur väl du utnyttjar känslotillstånd för att stärka tänkande och kreativitet.","Förstå känslor","Din kunskap om känslornas dynamik — hur de blandas, utvecklas och påverkar beteende.","Hantera känslor","Din förmåga att reglera dina egna känslor och påverka andra positivt."],
"sw": ["Kutambua Hisia","Uwezo wako wa kusoma hisia kwa usahihi katika nyuso, sauti na mazingira.","Kutumia Hisia","Jinsi unavyotumia hali za hisia kuimarisha fikra na ubunifu.","Kuelewa Hisia","Ujuzi wako wa mienendo ya hisia — jinsi zinavyochanganyika, kubadilika na kuathiri tabia.","Kudhibiti Hisia","Uwezo wako wa kudhibiti hisia zako na kuwaathiri wengine kwa njia chanya."],
"th": ["การรับรู้อารมณ์","ความสามารถของคุณในการอ่านอารมณ์อย่างแม่นยำจากใบหน้า น้ำเสียง และสภาพแวดล้อม","การใช้อารมณ์","คุณใช้สภาวะอารมณ์เพื่อเสริมการคิดและความคิดสร้างสรรค์ได้ดีเพียงใด","การเข้าใจอารมณ์","ความรู้ของคุณเกี่ยวกับพลวัตของอารมณ์ ว่าอารมณ์ผสมผสาน เปลี่ยนแปลง และส่งผลต่อพฤติกรรมอย่างไร","การจัดการอารมณ์","ความสามารถของคุณในการกำกับอารมณ์ตนเองและส่งผลเชิงบวกต่อผู้อื่น"],
"tl": ["Pagkilala sa Damdamin","Ang kakayahan mong basahin nang tumpak ang damdamin sa mukha, tinig, at paligid.","Paggamit ng Damdamin","Kung gaano mo nagagamit ang mga damdamin para patalasin ang pag-iisip at pagkamalikhain.","Pag-unawa sa Damdamin","Ang alam mo tungkol sa dinamika ng damdamin — kung paano ito naghahalo, nagbabago, at nakaaapekto sa asal.","Pamamahala sa Damdamin","Ang kakayahan mong pamahalaan ang sariling damdamin at positibong makaimpluwensya sa iba."],
"tr": ["Duyguları algılama","Yüzlerden, sesten ve çevreden duyguları doğru okuma beceriniz.","Duyguları kullanma","Düşünmeyi ve yaratıcılığı güçlendirmek için duygusal durumlardan ne kadar yararlandığınız.","Duyguları anlama","Duygusal dinamiklere dair bilginiz — duyguların nasıl harmanlandığı, geliştiği ve davranışı etkilediği.","Duyguları yönetme","Kendi duygularınızı düzenleme ve başkalarını olumlu etkileme kapasiteniz."],
"uk": ["Розпізнавання емоцій","Ваша здатність точно зчитувати емоції з облич, голосу та оточення.","Використання емоцій","Наскільки добре ви застосовуєте емоційні стани для мислення та творчості.","Розуміння емоцій","Ваші знання про динаміку емоцій — як вони змішуються, змінюються та впливають на поведінку.","Керування емоціями","Ваша здатність регулювати власні емоції та позитивно впливати на інших."],
"vi": ["Nhận biết cảm xúc","Khả năng đọc chính xác cảm xúc qua nét mặt, giọng nói và bối cảnh xung quanh.","Sử dụng cảm xúc","Mức độ bạn tận dụng trạng thái cảm xúc để nâng cao tư duy và sáng tạo.","Thấu hiểu cảm xúc","Hiểu biết của bạn về động lực cảm xúc — cách chúng pha trộn, biến đổi và chi phối hành vi.","Quản lý cảm xúc","Khả năng bạn điều chỉnh cảm xúc của mình và tác động tích cực đến người khác."],
"zh": ["感知情绪","你从表情、语气和环境中准确读出情绪的能力。","运用情绪","你在多大程度上借助情绪状态提升思考与创造力。","理解情绪","你对情绪运作的了解——它们如何交织、演变并影响行为。","管理情绪","你调节自身情绪并积极影响他人的能力。"],
}

ready = T.ready_langs()
missing = [l for l in ready if l not in K]
if missing:
    print('NO TRANSLATIONS FOR:', missing); sys.exit(1)
for lang in ready:
    vals = K[lang]
    assert len(vals) == len(NAMES), (lang, len(vals))
    T.add_keys(lang, dict(zip(NAMES, vals)))
print('done: %d EQ branch keys x %d languages' % (len(NAMES), len(ready)))
