# -*- coding: utf-8 -*-
"""The four homepage selling points. Three of them were false.

  why1_desc  "Same tools used in academic studies" - they are our own
             instruments modelled on published research, not the published
             instruments themselves.
  why2_*     "See exactly where you rank against millions of people" - we have
             no comparison sample at all. The percentile came from an assumed
             normal curve. This was the same fabrication as the norms claim.
  why3_*     "100% Anonymous ... No tracking" - GA4 and AdSense both run on
             every page, so "no tracking" was simply untrue. What was actually
             meant is "no sign-up", which is true and is the better line anyway.

Order: why1_desc, why2_title, why2_desc, why3_title, why3_desc, badge_anon
"""
import os, sys
sys.path.insert(0, os.path.join(os.getcwd(), '_build'))
import tools as T

NAMES = ["why1_desc","why2_title","why2_desc","why3_title","why3_desc","badge_anon"]

K = {
"en": ["Every test is modelled on published psychometric research — Raven's matrices, the Big Five, the Stroop task.","Honest Scoring","Results come with a confidence interval instead of a falsely precise number, and we say plainly what each test can and cannot tell you.","No Sign-Up Needed","No account, no email, no paywall. Your results appear the moment you finish, and stay free.","No sign-up"],
"af": ["Elke toets is gemodelleer op gepubliseerde psigometriese navorsing — Raven se matrikse, die Groot Vyf, die Stroop-taak.","Eerlike Telling","Uitslae kom met 'n vertrouensinterval eerder as 'n vals presiese getal, en ons sê reguit wat elke toets wel en nie kan vertel nie.","Geen Registrasie Nodig","Geen rekening, geen e-pos, geen betaalmuur nie. Jou uitslae verskyn sodra jy klaar is, en bly gratis.","Geen registrasie"],
"ar": ["كل اختبار مصمم على غرار أبحاث قياس نفسي منشورة — مصفوفات ريفن، والعوامل الخمسة الكبرى، ومهمة ستروب.","تقييم صادق","تأتي النتائج بفاصل ثقة بدل رقم دقيق زائفًا، ونقول بوضوح ما يستطيع كل اختبار إخبارك به وما لا يستطيع.","بلا تسجيل","بلا حساب ولا بريد ولا جدار دفع. تظهر نتائجك فور انتهائك، وتبقى مجانية.","بلا تسجيل"],
"bg": ["Всеки тест е изграден по публикувани психометрични изследвания — матриците на Рейвън, Големите пет, задачата на Струп.","Честно оценяване","Резултатите идват с доверителен интервал вместо с фалшиво точно число, и казваме ясно какво може и какво не може да ви каже всеки тест.","Без регистрация","Без акаунт, без имейл, без плащане. Резултатите се появяват веднага щом приключите и остават безплатни.","Без регистрация"],
"cs": ["Každý test vychází z publikovaného psychometrického výzkumu — Ravenových matic, Velké pětky, Stroopovy úlohy.","Poctivé skóre","Výsledky přicházejí s intervalem spolehlivosti místo falešně přesného čísla a otevřeně říkáme, co který test může a nemůže prozradit.","Bez registrace","Žádný účet, žádný e-mail, žádná platební brána. Výsledek se objeví hned po dokončení a zůstává zdarma.","Bez registrace"],
"da": ["Hver test er bygget på publiceret psykometrisk forskning — Ravens matricer, Big Five, Stroop-opgaven.","Ærlig scoring","Resultater kommer med et konfidensinterval i stedet for et falsk præcist tal, og vi siger ligeud, hvad hver test kan og ikke kan fortælle.","Ingen tilmelding","Ingen konto, ingen e-mail, ingen betalingsmur. Dine resultater vises, så snart du er færdig, og forbliver gratis.","Ingen tilmelding"],
"de": ["Jeder Test ist publizierter psychometrischer Forschung nachgebildet — Ravens Matrizen, den Big Five, der Stroop-Aufgabe.","Ehrliche Auswertung","Ergebnisse kommen mit einem Konfidenzintervall statt einer scheingenauen Zahl, und wir sagen offen, was jeder Test aussagen kann und was nicht.","Keine Anmeldung","Kein Konto, keine E-Mail, keine Bezahlschranke. Ihr Ergebnis erscheint sofort und bleibt kostenlos.","Ohne Anmeldung"],
"el": ["Κάθε τεστ είναι φτιαγμένο πάνω σε δημοσιευμένη ψυχομετρική έρευνα — τις μήτρες του Raven, τους Big Five, τη δοκιμασία Stroop.","Τίμια βαθμολόγηση","Τα αποτελέσματα συνοδεύονται από διάστημα εμπιστοσύνης αντί για ψευδώς ακριβή αριθμό, και λέμε καθαρά τι μπορεί και τι δεν μπορεί να δείξει κάθε τεστ.","Χωρίς εγγραφή","Χωρίς λογαριασμό, χωρίς email, χωρίς χρέωση. Τα αποτελέσματα εμφανίζονται μόλις τελειώσετε και μένουν δωρεάν.","Χωρίς εγγραφή"],
"es": ["Cada test está modelado sobre investigación psicométrica publicada: las matrices de Raven, los Cinco Grandes, la tarea de Stroop.","Puntuación honesta","Los resultados llegan con un intervalo de confianza en lugar de un número falsamente preciso, y decimos con claridad qué puede y qué no puede decirte cada test.","Sin registro","Sin cuenta, sin correo, sin muro de pago. Tus resultados aparecen al terminar y siguen siendo gratis.","Sin registro"],
"et": ["Iga test on üles ehitatud avaldatud psühhomeetriliste uuringute järgi — Raveni maatriksid, Suur Viisik, Stroopi ülesanne.","Aus hindamine","Tulemused tulevad usaldusvahemikuga, mitte valelikult täpse arvuna, ja me ütleme otse, mida iga test näitab ja mida mitte.","Registreerimist pole vaja","Ei kontot, ei e-posti, ei maksumüüri. Tulemused ilmuvad kohe pärast lõpetamist ja jäävad tasuta.","Ilma registreerimata"],
"fa": ["هر آزمون بر پایهٔ پژوهش‌های روان‌سنجی منتشرشده ساخته شده است — ماتریس‌های ریون، پنج عامل بزرگ، تکلیف استروپ.","نمره‌دهی صادقانه","نتایج با بازهٔ اطمینان می‌آیند، نه عددی با دقت ساختگی، و روشن می‌گوییم هر آزمون چه چیزی را می‌تواند و چه چیزی را نمی‌تواند نشان دهد.","بدون ثبت‌نام","بدون حساب، بدون ایمیل، بدون پرداخت. نتیجه همان لحظه که تمام کنید نمایان می‌شود و رایگان می‌ماند.","بدون ثبت‌نام"],
"fi": ["Jokainen testi on rakennettu julkaistun psykometrisen tutkimuksen pohjalle — Ravenin matriisit, Big Five, Stroopin tehtävä.","Rehellinen pisteytys","Tulokset tulevat luottamusvälin kanssa eikä valheellisen tarkkana lukuna, ja sanomme suoraan, mitä kukin testi voi ja ei voi kertoa.","Ei rekisteröitymistä","Ei tiliä, ei sähköpostia, ei maksumuuria. Tulos näkyy heti lopetettuasi ja pysyy ilmaisena.","Ei rekisteröitymistä"],
"fr": ["Chaque test est modelé sur des recherches psychométriques publiées : les matrices de Raven, les Big Five, la tâche de Stroop.","Notation honnête","Les résultats arrivent avec un intervalle de confiance plutôt qu'un chiffre faussement précis, et nous disons clairement ce que chaque test peut et ne peut pas révéler.","Sans inscription","Pas de compte, pas d'e-mail, pas de paiement. Vos résultats s'affichent dès la fin et restent gratuits.","Sans inscription"],
"he": ["כל מבחן בנוי על מחקר פסיכומטרי שפורסם — מטריצות רייבן, חמשת הגדולים, מטלת שטרופ.","ניקוד כן","התוצאות מגיעות עם רווח בר-סמך במקום מספר מדויק לכאורה, ואנחנו אומרים בפירוש מה כל מבחן יכול ולא יכול לגלות.","בלי הרשמה","בלי חשבון, בלי אימייל, בלי תשלום. התוצאות מופיעות ברגע שסיימתם ונשארות חינם.","בלי הרשמה"],
"hi": ["हर परीक्षण प्रकाशित मनोमापन शोध पर बना है — रेवेन की मैट्रिसेज़, बिग फ़ाइव, स्ट्रूप कार्य।","ईमानदार अंकन","परिणाम झूठी सटीकता वाले अंक के बजाय विश्वास अंतराल के साथ आते हैं, और हम साफ़ कहते हैं कि हर परीक्षण क्या बता सकता है और क्या नहीं।","कोई पंजीकरण नहीं","न खाता, न ईमेल, न भुगतान। परिणाम पूरा करते ही दिखते हैं और मुफ़्त रहते हैं।","बिना पंजीकरण"],
"hr": ["Svaki je test građen na objavljenim psihometrijskim istraživanjima — Ravenovim matricama, Velikih pet, Stroopovu zadatku.","Pošteno bodovanje","Rezultati dolaze s intervalom pouzdanosti umjesto lažno preciznog broja, a otvoreno kažemo što svaki test može, a što ne može otkriti.","Bez registracije","Bez računa, bez e-pošte, bez naplate. Rezultati se pojave čim završite i ostaju besplatni.","Bez registracije"],
"hu": ["Minden teszt publikált pszichometriai kutatás mintájára készült — Raven mátrixai, a Big Five, a Stroop-feladat.","Őszinte pontozás","Az eredmények konfidenciaintervallummal érkeznek, nem álpontos számmal, és kimondjuk, mit tud és mit nem tud megmutatni az adott teszt.","Nincs regisztráció","Nincs fiók, nincs e-mail, nincs fizetés. Az eredmény azonnal megjelenik, és ingyenes marad.","Regisztráció nélkül"],
"id": ["Setiap tes dibentuk dari riset psikometri yang dipublikasikan — matriks Raven, Big Five, tugas Stroop.","Penilaian jujur","Hasil datang dengan selang kepercayaan, bukan angka yang seolah-olah presisi, dan kami menyatakan terus terang apa yang bisa dan tidak bisa ditunjukkan tiap tes.","Tanpa pendaftaran","Tanpa akun, tanpa email, tanpa bayar. Hasil muncul begitu Anda selesai dan tetap gratis.","Tanpa daftar"],
"it": ["Ogni test è modellato su ricerca psicometrica pubblicata: le matrici di Raven, i Big Five, il compito di Stroop.","Punteggio onesto","I risultati arrivano con un intervallo di confidenza invece di un numero falsamente preciso, e diciamo chiaramente cosa ogni test può e non può dire.","Nessuna registrazione","Nessun account, nessuna email, nessun pagamento. I risultati compaiono appena finisci e restano gratis.","Senza registrazione"],
"ja": ["どの検査も公表された心理測定の研究をもとに作っています。レーヴンの行列、ビッグファイブ、ストループ課題などです。","偽りのない採点","結果は見かけだけ正確な数値ではなく信頼区間つきで示し、その検査で分かること・分からないことをはっきり書きます。","登録不要","アカウントもメールも課金もありません。終わればすぐ結果が出て、ずっと無料です。","登録不要"],
"ko": ["모든 검사는 공개된 심리측정 연구를 본떠 만들었습니다. 레이븐 행렬, 빅 파이브, 스트룹 과제 같은 것들입니다.","정직한 채점","결과는 그럴듯하게 정밀한 숫자 대신 신뢰구간과 함께 제시하며, 각 검사가 무엇을 말해 줄 수 있고 없는지 분명히 밝힙니다.","가입 불필요","계정도 이메일도 결제도 없습니다. 끝내는 즉시 결과가 나오고 계속 무료입니다.","가입 불필요"],
"lt": ["Kiekvienas testas sukurtas pagal paskelbtus psichometrinius tyrimus — Raveno matricas, Didįjį penketą, Stroopo užduotį.","Sąžiningas vertinimas","Rezultatai pateikiami su pasikliautinuoju intervalu, o ne apgaulingai tiksliu skaičiumi, ir aiškiai pasakome, ką kiekvienas testas gali ir ko negali parodyti.","Registracijos nereikia","Jokios paskyros, jokio el. pašto, jokio mokesčio. Rezultatai pasirodo iškart baigus ir lieka nemokami.","Be registracijos"],
"lv": ["Katrs tests veidots pēc publicētiem psihometriskiem pētījumiem — Rāvena matricām, Lielā piecinieka, Strūpa uzdevuma.","Godīgs vērtējums","Rezultāti nāk ar ticamības intervālu, nevis maldinoši precīzu skaitli, un mēs skaidri sakām, ko katrs tests var un ko nevar parādīt.","Nav jāreģistrējas","Nav konta, nav e-pasta, nav maksas. Rezultāti parādās uzreiz pēc pabeigšanas un paliek bez maksas.","Bez reģistrācijas"],
"mk": ["Секој тест е граден врз објавени психометриски истражувања — Равеновите матрици, Големите пет, Струповата задача.","Чесно оценување","Резултатите доаѓаат со интервал на доверба наместо со лажно прецизен број, и отворено кажуваме што може, а што не може да покаже секој тест.","Без регистрација","Без сметка, без е-пошта, без плаќање. Резултатите се појавуваат штом ќе завршите и остануваат бесплатни.","Без регистрација"],
"ms": ["Setiap ujian dibentuk daripada penyelidikan psikometrik yang diterbitkan — matriks Raven, Big Five, tugas Stroop.","Pemarkahan jujur","Keputusan datang dengan selang keyakinan, bukan angka yang kelihatan tepat, dan kami nyatakan terus terang apa yang boleh dan tidak boleh ditunjukkan setiap ujian.","Tanpa pendaftaran","Tiada akaun, tiada e-mel, tiada bayaran. Keputusan muncul sebaik anda selesai dan kekal percuma.","Tanpa daftar"],
"nl": ["Elke test is gemodelleerd op gepubliceerd psychometrisch onderzoek — Ravens matrices, de Big Five, de Stroop-taak.","Eerlijke score","Resultaten komen met een betrouwbaarheidsinterval in plaats van een schijnnauwkeurig getal, en we zeggen ronduit wat elke test wel en niet kan vertellen.","Geen registratie","Geen account, geen e-mail, geen betaalmuur. Je resultaat verschijnt zodra je klaar bent en blijft gratis.","Geen registratie"],
"no": ["Hver test er bygget på publisert psykometrisk forskning — Ravens matriser, Big Five, Stroop-oppgaven.","Ærlig poengsetting","Resultatene kommer med et konfidensintervall i stedet for et falskt presist tall, og vi sier rett ut hva hver test kan og ikke kan fortelle.","Ingen registrering","Ingen konto, ingen e-post, ingen betalingsmur. Resultatet vises straks du er ferdig, og forblir gratis.","Uten registrering"],
"pl": ["Każdy test jest wzorowany na opublikowanych badaniach psychometrycznych — macierzach Ravena, Wielkiej Piątce, zadaniu Stroopa.","Uczciwa punktacja","Wyniki podajemy z przedziałem ufności zamiast pozornie precyzyjnej liczby i wprost mówimy, co dany test może, a czego nie może pokazać.","Bez rejestracji","Bez konta, bez e-maila, bez opłat. Wynik pojawia się zaraz po zakończeniu i pozostaje darmowy.","Bez rejestracji"],
"pt": ["Cada teste é modelado sobre investigação psicométrica publicada — as matrizes de Raven, os Cinco Grandes, a tarefa de Stroop.","Pontuação honesta","Os resultados vêm com um intervalo de confiança em vez de um número falsamente preciso, e dizemos com clareza o que cada teste pode e não pode revelar.","Sem registo","Sem conta, sem email, sem pagamento. Os resultados aparecem assim que termina e continuam gratuitos.","Sem registo"],
"ro": ["Fiecare test este construit după cercetări psihometrice publicate — matricile Raven, Big Five, sarcina Stroop.","Punctare onestă","Rezultatele vin cu un interval de încredere în loc de un număr fals precis, iar noi spunem limpede ce poate și ce nu poate arăta fiecare test.","Fără înregistrare","Fără cont, fără email, fără plată. Rezultatele apar imediat ce termini și rămân gratuite.","Fără cont"],
"ru": ["Каждый тест построен по опубликованным психометрическим исследованиям — матрицам Равена, Большой пятёрке, задаче Струпа.","Честная оценка","Результаты приходят с доверительным интервалом, а не с мнимо точным числом, и мы прямо говорим, что тест может показать, а что нет.","Без регистрации","Ни аккаунта, ни почты, ни оплаты. Результат появляется сразу после завершения и остаётся бесплатным.","Без регистрации"],
"sk": ["Každý test vychádza z publikovaného psychometrického výskumu — Ravenových matíc, Veľkej päťky, Stroopovej úlohy.","Poctivé skóre","Výsledky prichádzajú s intervalom spoľahlivosti namiesto falošne presného čísla a otvorene hovoríme, čo daný test môže a nemôže prezradiť.","Bez registrácie","Žiadny účet, žiadny e-mail, žiadna platba. Výsledok sa zobrazí hneď po dokončení a zostáva zadarmo.","Bez registrácie"],
"sl": ["Vsak test je zasnovan po objavljenih psihometričnih raziskavah — Ravenovih matricah, Velikih petih, Stroopovi nalogi.","Pošteno ocenjevanje","Rezultati pridejo z intervalom zaupanja namesto z lažno natančno številko, in odkrito povemo, kaj posamezen test lahko in česa ne more pokazati.","Brez registracije","Brez računa, brez e-pošte, brez plačila. Rezultat se pokaže takoj po koncu in ostane brezplačen.","Brez registracije"],
"sq": ["Çdo test është ndërtuar mbi kërkime psikometrike të botuara — matricat e Ravenit, Pesë të Mëdhenjtë, detyrën e Stroopit.","Vlerësim i ndershëm","Rezultatet vijnë me një interval besimi në vend të një numri me saktësi të rreme, dhe themi hapur çfarë mund dhe çfarë nuk mund të tregojë secili test.","Pa regjistrim","Pa llogari, pa email, pa pagesë. Rezultatet shfaqen sapo mbaroni dhe mbeten falas.","Pa regjistrim"],
"sr": ["Сваки тест је грађен на објављеним психометријским истраживањима — Равеновим матрицама, Великих пет, Струповом задатку.","Поштено бодовање","Резултати долазе са интервалом поверења уместо лажно прецизног броја, а отворено кажемо шта сваки тест може, а шта не може да покаже.","Без регистрације","Без налога, без мејла, без плаћања. Резултати се појаве чим завршите и остају бесплатни.","Без регистрације"],
"sv": ["Varje test är byggt på publicerad psykometrisk forskning — Ravens matriser, Big Five, Stroop-uppgiften.","Ärlig poängsättning","Resultaten kommer med ett konfidensintervall i stället för en falskt exakt siffra, och vi säger rakt ut vad varje test kan och inte kan visa.","Ingen registrering","Inget konto, ingen e-post, ingen betalvägg. Resultatet visas så fort du är klar och förblir gratis.","Utan registrering"],
"sw": ["Kila kipimo kimeundwa kwa kufuata utafiti wa kipimo cha akili uliochapishwa — matriki za Raven, Big Five, kazi ya Stroop.","Upimaji wa uwazi","Matokeo huja na kipimo cha mpaka wa uhakika badala ya namba yenye usahihi wa uongo, na tunasema wazi kila kipimo kinaweza na hakiwezi kuonyesha nini.","Hakuna kujisajili","Hakuna akaunti, hakuna barua pepe, hakuna malipo. Matokeo hutokea mara umalizapo na hubaki bure.","Bila kujisajili"],
"th": ["ทุกแบบทดสอบสร้างตามงานวิจัยการวัดทางจิตวิทยาที่ตีพิมพ์ ทั้งเมทริกซ์ของเรเวน บิกไฟฟ์ และงานสตรูป","การให้คะแนนอย่างตรงไปตรงมา","ผลลัพธ์มาพร้อมช่วงความเชื่อมั่นแทนตัวเลขที่ดูแม่นยำเกินจริง และเราบอกชัดเจนว่าแต่ละแบบทดสอบบอกอะไรได้และบอกอะไรไม่ได้","ไม่ต้องสมัคร","ไม่ต้องมีบัญชี ไม่ต้องใช้อีเมล ไม่มีค่าใช้จ่าย ผลขึ้นทันทีที่ทำเสร็จและฟรีตลอด","ไม่ต้องสมัคร"],
"tl": ["Bawat pagsusulit ay hinubog mula sa nailathalang pananaliksik sa sikometriks — mga matris ni Raven, ang Big Five, ang gawaing Stroop.","Tapat na pagmamarka","May kasamang confidence interval ang resulta sa halip na numerong mukhang eksakto, at malinaw naming sinasabi kung ano ang kaya at hindi kayang ipakita ng bawat pagsusulit.","Walang pagpaparehistro","Walang account, walang email, walang bayad. Lumalabas ang resulta pagkatapos mo at mananatiling libre.","Walang rehistro"],
"tr": ["Her test yayımlanmış psikometri araştırmalarına göre kurgulandı — Raven matrisleri, Beş Büyük Faktör, Stroop görevi.","Dürüst puanlama","Sonuçlar sahte bir kesinlik taşıyan tek sayı yerine güven aralığıyla gelir; her testin neyi söyleyip neyi söyleyemeyeceğini açıkça yazarız.","Kayıt gerekmez","Hesap yok, e-posta yok, ödeme yok. Sonuçlarınız bitirir bitirmez çıkar ve ücretsiz kalır.","Kayıtsız"],
"uk": ["Кожен тест побудовано за опублікованими психометричними дослідженнями — матрицями Равена, Великою п'ятіркою, завданням Струпа.","Чесне оцінювання","Результати надходять із довірчим інтервалом, а не з удавано точним числом, і ми прямо кажемо, що тест може показати, а що ні.","Без реєстрації","Ні акаунта, ні пошти, ні оплати. Результат з'являється одразу після завершення й лишається безкоштовним.","Без реєстрації"],
"vi": ["Mỗi bài kiểm tra được dựng theo nghiên cứu tâm trắc đã công bố — ma trận Raven, Big Five, nhiệm vụ Stroop.","Chấm điểm trung thực","Kết quả đi kèm khoảng tin cậy thay vì một con số chính xác giả tạo, và chúng tôi nói rõ mỗi bài kiểm tra cho biết được gì và không cho biết được gì.","Không cần đăng ký","Không tài khoản, không email, không trả phí. Kết quả hiện ngay khi bạn xong và luôn miễn phí.","Không đăng ký"],
"zh": ["每一项测验都参照公开发表的心理测量研究设计——瑞文矩阵、大五人格、斯特鲁普任务。","诚实的评分","结果附带置信区间，而不是一个看似精确的数字；每项测验能说明什么、不能说明什么，我们都直说。","无需注册","无需账号、邮箱或付费。做完立刻出结果，且永久免费。","无需注册"],
}

ready = T.ready_langs()
missing = [l for l in ready if l not in K]
if missing:
    print('NO TRANSLATIONS FOR:', missing); sys.exit(1)
for lang in ready:
    v = K[lang]
    assert len(v) == len(NAMES), (lang, len(v))
    T.set_keys(lang, dict(zip(NAMES, v)))
print('done: %d hero keys x %d languages' % (len(NAMES), len(ready)))
