# -*- coding: utf-8 -*-
"""Pattern Recognition test copy.

pat_res_desc previously told every visitor, in 43 languages, that their score
"corresponds to an estimated IQ range" and that this was "based on published
norms". It was based on a 13-entry lookup table someone typed by hand.
Order: pat_how2, pat_res_desc, pat_note, pat_accuracy, pat_chance
"""
import os, sys
sys.path.insert(0, os.path.join(os.getcwd(), '_build'))
import tools as T

NAMES = ["pat_how2","pat_res_desc","pat_note","pat_accuracy","pat_chance"]

K = {
"en": ["Work out the rule and choose the missing piece from 6 options. Fresh puzzles every attempt.","You solved {n} of {t}. This is a short screener, so treat the percentile as a rough placement rather than a measurement — the full IQ test uses more items and reports a confidence interval.","A short screener, not a certified IQ test, and not standardised on a representative sample. For a clinical assessment, consult a psychologist.","Accuracy","Chance level"],
"af": ["Werk die reël uit en kies die ontbrekende stuk uit 6 opsies. Elke poging het nuwe puzzels.","Jy het {n} uit {t} opgelos. Dit is 'n kort siftingstoets, so beskou die persentiel as 'n rowwe plasing eerder as 'n meting — die volle IK-toets gebruik meer items en gee 'n vertrouensinterval.","'n Kort siftingstoets, nie 'n gesertifiseerde IK-toets nie, en nie op 'n verteenwoordigende steekproef gestandaardiseer nie. Raadpleeg 'n sielkundige vir 'n kliniese assessering.","Akkuraatheid","Kansvlak"],
"ar": ["استنتج القاعدة واختر القطعة الناقصة من ٦ خيارات. ألغاز جديدة في كل محاولة.","حللت {n} من {t}. هذا اختبار فرز قصير، فاعتبر المئين تحديدًا تقريبيًا لا قياسًا؛ اختبار الذكاء الكامل يستخدم أسئلة أكثر ويعطي فاصل ثقة.","اختبار فرز قصير، وليس اختبار ذكاء معتمدًا، ولم يُقنَّن على عينة ممثلة. للتقييم السريري راجع أخصائيًا نفسيًا.","الدقة","مستوى التخمين"],
"bg": ["Открийте правилото и изберете липсващата част от 6 възможности. Нови задачи при всеки опит.","Решихте {n} от {t}. Това е кратък скринингов тест, затова приемайте персентила като приблизително подреждане, а не измерване — пълният тест използва повече задачи и дава доверителен интервал.","Кратък скринингов тест, а не сертифициран тест за интелигентност, и не е стандартизиран върху представителна извадка. За клинична оценка се обърнете към психолог.","Точност","Ниво на случайност"],
"cs": ["Odhalte pravidlo a vyberte chybějící dílek ze 6 možností. Každý pokus přináší nové úlohy.","Vyřešili jste {n} z {t}. Jde o krátký screening, berte tedy percentil jako hrubé zařazení, ne měření — plný IQ test má více položek a uvádí interval spolehlivosti.","Krátký screening, nikoli certifikovaný test IQ, a není standardizován na reprezentativním vzorku. Pro klinické vyšetření se obraťte na psychologa.","Přesnost","Úroveň náhody"],
"da": ["Find reglen, og vælg den manglende brik blandt 6 muligheder. Nye opgaver hver gang.","Du løste {n} af {t}. Det er en kort screening, så opfat percentilen som en grov placering frem for en måling — den fulde IQ-test bruger flere opgaver og angiver et konfidensinterval.","En kort screening, ikke en certificeret IQ-test, og ikke standardiseret på en repræsentativ stikprøve. Kontakt en psykolog for en klinisk vurdering.","Præcision","Tilfældighedsniveau"],
"de": ["Erkennen Sie die Regel und wählen Sie das fehlende Teil aus 6 Optionen. Bei jedem Versuch neue Aufgaben.","Sie haben {n} von {t} gelöst. Das ist ein kurzer Screener, betrachten Sie das Perzentil also als grobe Einordnung und nicht als Messung — der vollständige IQ-Test hat mehr Aufgaben und nennt ein Konfidenzintervall.","Ein kurzer Screener, kein zertifizierter IQ-Test, und nicht an einer repräsentativen Stichprobe normiert. Für eine klinische Abklärung wenden Sie sich an eine Psychologin oder einen Psychologen.","Trefferquote","Zufallsniveau"],
"el": ["Βρείτε τον κανόνα και επιλέξτε το κομμάτι που λείπει από 6 επιλογές. Νέα ερωτήματα σε κάθε προσπάθεια.","Λύσατε {n} από {t}. Πρόκειται για σύντομο τεστ ανίχνευσης, οπότε δείτε το εκατοστημόριο ως χονδρική τοποθέτηση και όχι ως μέτρηση — το πλήρες τεστ έχει περισσότερα ερωτήματα και δίνει διάστημα εμπιστοσύνης.","Σύντομο τεστ ανίχνευσης, όχι πιστοποιημένο τεστ νοημοσύνης, και χωρίς στάθμιση σε αντιπροσωπευτικό δείγμα. Για κλινική αξιολόγηση απευθυνθείτε σε ψυχολόγο.","Ακρίβεια","Επίπεδο τύχης"],
"es": ["Deduce la regla y elige la pieza que falta entre 6 opciones. Puzles nuevos en cada intento.","Resolviste {n} de {t}. Es una prueba corta de cribado, así que toma el percentil como una ubicación aproximada y no como una medición: el test de IQ completo usa más ítems y da un intervalo de confianza.","Una prueba corta de cribado, no un test de IQ certificado, y sin estandarizar con una muestra representativa. Para una evaluación clínica, consulta a un psicólogo.","Precisión","Nivel de azar"],
"et": ["Leia reegel ja vali puuduv tükk 6 variandi hulgast. Iga katse annab uued ülesanded.","Lahendasid {n} / {t}. See on lühike sõeltest, seega võta protsentiili pigem ligikaudse paigutusena kui mõõtmisena — täielikus testis on rohkem ülesandeid ja see annab usaldusvahemiku.","Lühike sõeltest, mitte sertifitseeritud intelligentsustest, ega ole standarditud esindusliku valimi peal. Kliiniliseks hindamiseks pöördu psühholoogi poole.","Täpsus","Juhuse tase"],
"fa": ["قاعده را بیابید و قطعهٔ گمشده را از میان ۶ گزینه برگزینید. هر بار معماهای تازه.","شما {n} از {t} را حل کردید. این یک غربالگری کوتاه است، پس صدک را جایگاهی تقریبی بدانید نه اندازه‌گیری؛ آزمون کامل هوش پرسش‌های بیشتری دارد و بازهٔ اطمینان می‌دهد.","یک غربالگری کوتاه است، نه آزمون هوش معتبر، و روی نمونه‌ای معرف هنجاریابی نشده. برای ارزیابی بالینی به روان‌شناس مراجعه کنید.","دقت","سطح شانس"],
"fi": ["Päättele sääntö ja valitse puuttuva palanen 6 vaihtoehdosta. Uudet tehtävät joka kerta.","Ratkaisit {n} / {t}. Tämä on lyhyt seulonta, joten pidä persentiiliä karkeana sijoituksena eikä mittauksena — täydessä testissä on enemmän tehtäviä ja se antaa luottamusvälin.","Lyhyt seulonta, ei sertifioitu älykkyystesti, eikä sitä ole normitettu edustavalla otoksella. Kliinistä arviota varten käänny psykologin puoleen.","Osumatarkkuus","Sattuman taso"],
"fr": ["Trouvez la règle et choisissez la pièce manquante parmi 6 options. De nouveaux puzzles à chaque tentative.","Vous avez résolu {n} sur {t}. Il s'agit d'un test court : considérez le centile comme un positionnement approximatif, pas une mesure — le test de QI complet comporte plus d'items et fournit un intervalle de confiance.","Un test de dépistage court, pas un test de QI certifié, et non étalonné sur un échantillon représentatif. Pour une évaluation clinique, consultez un psychologue.","Précision","Niveau du hasard"],
"he": ["גלו את הכלל ובחרו את החלק החסר מתוך 6 אפשרויות. חידות חדשות בכל ניסיון.","פתרתם {n} מתוך {t}. זהו מבחן סינון קצר, לכן ראו את האחוזון כמיקום גס ולא כמדידה — מבחן האינטליגנציה המלא כולל יותר פריטים ומדווח רווח בר-סמך.","מבחן סינון קצר, לא מבחן אינטליגנציה מוסמך, ולא תוקנן על מדגם מייצג. להערכה קלינית פנו לפסיכולוג.","דיוק","רמת ניחוש"],
"hi": ["नियम पहचानिए और 6 विकल्पों में से लुप्त टुकड़ा चुनिए। हर प्रयास में नई पहेलियाँ।","आपने {t} में से {n} हल किए। यह एक संक्षिप्त स्क्रीनिंग है, इसलिए प्रतिशतक को माप नहीं बल्कि मोटा स्थान समझिए — पूरा बुद्धि परीक्षण अधिक प्रश्न लेता है और विश्वास अंतराल देता है।","एक संक्षिप्त स्क्रीनिंग, प्रमाणित बुद्धि परीक्षण नहीं, और किसी प्रतिनिधि नमूने पर मानकीकृत नहीं। नैदानिक मूल्यांकन के लिए मनोवैज्ञानिक से परामर्श लें।","शुद्धता","संयोग स्तर"],
"hr": ["Otkrijte pravilo i odaberite dio koji nedostaje od 6 ponuđenih. Novi zadaci pri svakom pokušaju.","Riješili ste {n} od {t}. Ovo je kratki probirni test, pa percentil shvatite kao grubo smještanje, a ne mjerenje — potpuni test ima više zadataka i daje interval pouzdanosti.","Kratki probirni test, ne certificirani test inteligencije, i nije standardiziran na reprezentativnom uzorku. Za kliničku procjenu obratite se psihologu.","Točnost","Razina slučajnosti"],
"hu": ["Fejtse meg a szabályt, és válassza ki a hiányzó darabot 6 lehetőség közül. Minden próbálkozás új feladatokat hoz.","{t} feladatból {n} sikerült. Ez rövid szűrés, ezért a percentilist inkább durva besorolásnak tekintse, mint mérésnek — a teljes teszt több feladatot használ és konfidenciaintervallumot közöl.","Rövid szűrés, nem hitelesített intelligenciateszt, és nem standardizálták reprezentatív mintán. Klinikai vizsgálathoz forduljon pszichológushoz.","Pontosság","Véletlen szintje"],
"id": ["Temukan aturannya dan pilih potongan yang hilang dari 6 pilihan. Teka-teki baru setiap percobaan.","Anda menyelesaikan {n} dari {t}. Ini penyaringan singkat, jadi anggap persentil sebagai penempatan kasar, bukan pengukuran — tes IQ lengkap memakai lebih banyak soal dan memberi selang kepercayaan.","Penyaringan singkat, bukan tes IQ bersertifikat, dan belum dibakukan pada sampel representatif. Untuk asesmen klinis, temui psikolog.","Akurasi","Tingkat kebetulan"],
"it": ["Individua la regola e scegli il pezzo mancante tra 6 opzioni. Rompicapi nuovi a ogni tentativo.","Hai risolto {n} su {t}. È uno screening breve, quindi considera il percentile come una collocazione approssimativa e non una misura: il test del QI completo usa più item e riporta un intervallo di confidenza.","Uno screening breve, non un test del QI certificato, e non standardizzato su un campione rappresentativo. Per una valutazione clinica rivolgiti a uno psicologo.","Precisione","Livello del caso"],
"ja": ["規則を見抜き、6つの選択肢から欠けた図形を選んでください。毎回新しい問題です。","{t}問中{n}問正解でした。これは短い簡易検査なので、パーセンタイルは測定値ではなく大まかな位置づけとお考えください。本編の知能検査はより多くの問題を使い、信頼区間を示します。","短い簡易検査であり、認定された知能検査ではありません。代表標本による標準化も行っていません。臨床的な評価は心理士にご相談ください。","正答率","偶然の水準"],
"ko": ["규칙을 찾아 6개 선택지 가운데 빠진 조각을 고르세요. 시도할 때마다 새로운 문제가 나옵니다.","{t}문항 중 {n}문항을 맞히셨습니다. 짧은 선별 검사이므로 백분위는 측정값이 아니라 대략적인 위치로 보아 주세요. 본 지능 검사는 문항이 더 많고 신뢰구간을 함께 제시합니다.","짧은 선별 검사이며 공인된 지능 검사가 아니고, 대표 표본으로 표준화되지도 않았습니다. 임상 평가는 심리학자와 상담하세요.","정답률","우연 수준"],
"lt": ["Atskleiskite taisyklę ir iš 6 variantų pasirinkite trūkstamą dalį. Kiekvieną kartą naujos užduotys.","Išsprendėte {n} iš {t}. Tai trumpa atranka, tad procentilį laikykite apytiksle vieta, o ne matavimu — pilname teste daugiau užduočių ir pateikiamas pasikliautinasis intervalas.","Trumpa atranka, o ne sertifikuotas intelekto testas, ir nestandartizuota reprezentatyvioje imtyje. Dėl klinikinio vertinimo kreipkitės į psichologą.","Tikslumas","Atsitiktinumo lygis"],
"lv": ["Atklājiet likumsakarību un no 6 variantiem izvēlieties trūkstošo daļu. Katrā mēģinājumā jauni uzdevumi.","Atrisinājāt {n} no {t}. Šis ir īss skrīnings, tāpēc uztveriet procentili kā aptuvenu novietojumu, nevis mērījumu — pilnajā testā ir vairāk uzdevumu un tas norāda ticamības intervālu.","Īss skrīnings, nevis sertificēts intelekta tests, un nav standartizēts reprezentatīvā izlasē. Klīniskam novērtējumam vērsieties pie psihologa.","Precizitāte","Nejaušības līmenis"],
"mk": ["Откријте го правилото и изберете го делот што недостига од 6 понудени. Нови задачи при секој обид.","Решивте {n} од {t}. Ова е краток скрининг, па перцентилот сфатете го како груба положба, а не мерење — целосниот тест користи повеќе задачи и дава интервал на доверба.","Краток скрининг, не сертифициран тест за интелигенција, и не е стандардизиран на репрезентативен примерок. За клиничка проценка обратете се кај психолог.","Точност","Ниво на случајност"],
"ms": ["Cari peraturannya dan pilih kepingan yang hilang daripada 6 pilihan. Teka-teki baharu setiap percubaan.","Anda menyelesaikan {n} daripada {t}. Ini saringan ringkas, jadi anggap persentil sebagai penempatan kasar dan bukan pengukuran — ujian IQ penuh menggunakan lebih banyak item dan memberi selang keyakinan.","Saringan ringkas, bukan ujian IQ bertauliah, dan belum dipiawaikan pada sampel mewakili. Untuk penilaian klinikal, rujuk ahli psikologi.","Ketepatan","Aras nasib"],
"nl": ["Achterhaal de regel en kies het ontbrekende stuk uit 6 opties. Bij elke poging nieuwe puzzels.","Je loste er {n} van {t} op. Dit is een korte screening, dus zie het percentiel als een ruwe plaatsing en niet als een meting — de volledige IQ-test gebruikt meer items en geeft een betrouwbaarheidsinterval.","Een korte screening, geen gecertificeerde IQ-test, en niet genormeerd op een representatieve steekproef. Raadpleeg voor een klinische beoordeling een psycholoog.","Nauwkeurigheid","Kansniveau"],
"no": ["Finn regelen og velg den manglende brikken blant 6 alternativer. Nye oppgaver hver gang.","Du løste {n} av {t}. Dette er en kort screening, så se på persentilen som en grov plassering og ikke en måling — den fulle IQ-testen bruker flere oppgaver og oppgir et konfidensintervall.","En kort screening, ikke en sertifisert IQ-test, og ikke normert på et representativt utvalg. Kontakt en psykolog for en klinisk vurdering.","Treffsikkerhet","Tilfeldighetsnivå"],
"pl": ["Odkryj regułę i wybierz brakujący element spośród 6 opcji. Nowe zadania przy każdym podejściu.","Rozwiązałeś {n} z {t}. To krótki test przesiewowy, więc traktuj centyl jako zgrubne umiejscowienie, a nie pomiar — pełny test ma więcej zadań i podaje przedział ufności.","Krótki test przesiewowy, nie certyfikowany test inteligencji, i bez normalizacji na reprezentatywnej próbie. Po ocenę kliniczną zgłoś się do psychologa.","Trafność","Poziom przypadku"],
"pt": ["Descubra a regra e escolha a peça em falta entre 6 opções. Puzzles novos em cada tentativa.","Resolveu {n} de {t}. Este é um rastreio curto, por isso veja o percentil como uma colocação aproximada e não uma medição — o teste de QI completo usa mais itens e apresenta um intervalo de confiança.","Um rastreio curto, não um teste de QI certificado, e sem aferição numa amostra representativa. Para uma avaliação clínica, consulte um psicólogo.","Precisão","Nível do acaso"],
"ro": ["Descoperă regula și alege piesa lipsă dintre 6 variante. Puzzle-uri noi la fiecare încercare.","Ai rezolvat {n} din {t}. Este un screening scurt, așa că privește percentila ca pe o plasare aproximativă, nu ca pe o măsurătoare — testul complet folosește mai mulți itemi și oferă un interval de încredere.","Un screening scurt, nu un test de inteligență certificat, și neetalonat pe un eșantion reprezentativ. Pentru o evaluare clinică, consultă un psiholog.","Acuratețe","Nivelul întâmplării"],
"ru": ["Найдите правило и выберите недостающий фрагмент из 6 вариантов. Каждая попытка — новые задачи.","Вы решили {n} из {t}. Это короткий скрининг, поэтому воспринимайте процентиль как грубое размещение, а не измерение: полный тест содержит больше заданий и указывает доверительный интервал.","Короткий скрининг, а не сертифицированный тест интеллекта, и он не стандартизирован на репрезентативной выборке. За клинической оценкой обратитесь к психологу.","Точность","Уровень случайности"],
"sk": ["Odhaľte pravidlo a vyberte chýbajúci dielik zo 6 možností. Každý pokus prináša nové úlohy.","Vyriešili ste {n} z {t}. Ide o krátky skríning, preto berte percentil ako hrubé zaradenie, nie meranie — plný test má viac položiek a uvádza interval spoľahlivosti.","Krátky skríning, nie certifikovaný test inteligencie, a nie je štandardizovaný na reprezentatívnej vzorke. Pre klinické vyšetrenie sa obráťte na psychológa.","Presnosť","Úroveň náhody"],
"sl": ["Odkrijte pravilo in med 6 možnostmi izberite manjkajoči delec. Ob vsakem poskusu nove naloge.","Rešili ste {n} od {t}. To je kratek presejalni test, zato percentil razumite kot grobo umestitev in ne kot meritev — celoten test uporablja več nalog in navede interval zaupanja.","Kratek presejalni test, ne certificiran test inteligentnosti, in ni standardiziran na reprezentativnem vzorcu. Za klinično oceno se obrnite na psihologa.","Natančnost","Raven naključja"],
"sq": ["Gjeni rregullin dhe zgjidhni pjesën që mungon nga 6 mundësi. Enigma të reja çdo herë.","Zgjidhët {n} nga {t}. Ky është një filtrim i shkurtër, prandaj përqindjen shikojeni si vendosje të përafërt e jo si matje — testi i plotë i inteligjencës përdor më shumë pyetje dhe jep interval besimi.","Një filtrim i shkurtër, jo një test inteligjence i certifikuar, dhe i pastandardizuar mbi një kampion përfaqësues. Për vlerësim klinik, konsultohuni me një psikolog.","Saktësia","Niveli i rastësisë"],
"sr": ["Откријте правило и изаберите део који недостаје од 6 понуђених. Нови задаци при сваком покушају.","Решили сте {n} од {t}. Ово је кратак скрининг, па перцентил схватите као грубо смештање, а не мерење — потпун тест користи више задатака и даје интервал поверења.","Кратак скрининг, а не сертификован тест интелигенције, и није стандардизован на репрезентативном узорку. За клиничку процену обратите се психологу.","Тачност","Ниво случајности"],
"sv": ["Lista ut regeln och välj den saknade biten bland 6 alternativ. Nya uppgifter varje gång.","Du löste {n} av {t}. Det här är en kort screening, så se percentilen som en grov placering snarare än en mätning — det fullständiga IQ-testet har fler uppgifter och anger ett konfidensintervall.","En kort screening, inte ett certifierat IQ-test, och inte normerat på ett representativt urval. Kontakta en psykolog för en klinisk bedömning.","Träffsäkerhet","Slumpnivå"],
"sw": ["Tambua kanuni na uchague kipande kilichokosekana kati ya chaguo 6. Mafumbo mapya kila jaribio.","Ulitatua {n} kati ya {t}. Hiki ni kipimo kifupi cha uchunguzi, hivyo chukua asilimia kama nafasi ya jumla si kipimo halisi — kipimo kamili cha akili hutumia maswali mengi zaidi na hutoa kipimo cha mpaka wa uhakika.","Kipimo kifupi cha uchunguzi, si kipimo cha akili chenye ithibati, na hakijasawazishwa kwa sampuli wakilishi. Kwa tathmini ya kitabibu, muone mwanasaikolojia.","Usahihi","Kiwango cha bahati"],
"th": ["หากฎแล้วเลือกชิ้นส่วนที่ขาดหายจาก 6 ตัวเลือก โจทย์ใหม่ทุกครั้งที่ทำ","คุณทำได้ {n} จาก {t} ข้อ นี่เป็นแบบคัดกรองสั้น ๆ จึงควรมองเปอร์เซ็นไทล์เป็นตำแหน่งคร่าว ๆ ไม่ใช่การวัด แบบทดสอบเชาวน์ปัญญาฉบับเต็มใช้ข้อมากกว่าและรายงานช่วงความเชื่อมั่น","แบบคัดกรองสั้น ไม่ใช่แบบทดสอบเชาวน์ปัญญาที่รับรอง และไม่ได้สร้างเกณฑ์ปกติจากกลุ่มตัวอย่างที่เป็นตัวแทน หากต้องการประเมินทางคลินิก โปรดปรึกษานักจิตวิทยา","ความแม่นยำ","ระดับการเดา"],
"tl": ["Alamin ang panuntunan at piliin ang nawawalang piyesa mula sa 6 na pagpipilian. Bagong palaisipan sa bawat pagsubok.","Nasagot mo ang {n} sa {t}. Maikling screener ito, kaya ituring ang percentile bilang magaspang na pagkakalagay at hindi sukat — mas marami ang aytem ng buong pagsusulit sa katalinuhan at may confidence interval ito.","Maikling screener, hindi sertipikadong pagsusulit sa katalinuhan, at hindi naisanaysay sa kinatawang sampol. Para sa klinikal na pagtatasa, kumonsulta sa psychologist.","Katumpakan","Antas ng tsamba"],
"tr": ["Kuralı çözün ve eksik parçayı 6 seçenek arasından seçin. Her denemede yeni bulmacalar.","{t} sorudan {n} tanesini çözdünüz. Bu kısa bir tarama, bu yüzden yüzdelik dilimi bir ölçüm değil kaba bir yerleştirme olarak görün — tam zeka testi daha fazla soru kullanır ve güven aralığı verir.","Kısa bir tarama, sertifikalı bir zeka testi değil ve temsili bir örneklem üzerinde standardize edilmedi. Klinik değerlendirme için bir psikoloğa başvurun.","İsabet","Şans düzeyi"],
"uk": ["Знайдіть правило та оберіть відсутній фрагмент із 6 варіантів. Щоразу нові задачі.","Ви розв'язали {n} з {t}. Це короткий скринінг, тож сприймайте процентиль як приблизне розміщення, а не вимірювання — повний тест має більше завдань і подає довірчий інтервал.","Короткий скринінг, а не сертифікований тест інтелекту, і він не стандартизований на репрезентативній вибірці. По клінічну оцінку зверніться до психолога.","Точність","Рівень випадковості"],
"vi": ["Tìm ra quy luật và chọn mảnh còn thiếu trong 6 lựa chọn. Câu đố mới ở mỗi lần làm.","Bạn giải được {n} trên {t}. Đây là bài sàng lọc ngắn, nên hãy xem phân vị là vị trí ước chừng chứ không phải phép đo — bài kiểm tra trí tuệ đầy đủ dùng nhiều câu hơn và báo cáo khoảng tin cậy.","Một bài sàng lọc ngắn, không phải bài kiểm tra trí tuệ được chứng nhận, và chưa chuẩn hóa trên mẫu đại diện. Để đánh giá lâm sàng, hãy gặp nhà tâm lý học.","Độ chính xác","Mức đoán mò"],
"zh": ["找出规律，从 6 个选项中选出缺失的图形。每次作答都是全新题目。","你答对了 {t} 题中的 {n} 题。这是一次简短初筛，请把百分位看作大致定位而非测量结果——完整的智力测验题量更多，并会给出置信区间。","这是简短初筛，不是经过认证的智力测验，也未在代表性样本上建立常模。如需临床评估，请咨询心理学专业人士。","正确率","猜测水平"],
}

ready = T.ready_langs()
missing = [l for l in ready if l not in K]
if missing:
    print('NO TRANSLATIONS FOR:', missing); sys.exit(1)
for lang in ready:
    v = K[lang]
    assert len(v) == len(NAMES), (lang, len(v))
    assert '{n}' in v[1] and '{t}' in v[1], lang
    T.set_keys(lang, dict(zip(NAMES, v)))
print('done: %d pattern keys x %d languages' % (len(NAMES), len(ready)))
