# -*- coding: utf-8 -*-
"""Strings for the new Mental Rotation test, in all 43 markets.

Order: rot_title, rot_desc, rot_how_title, rot_how1, rot_how2, rot_how3,
       rot_how4, rot_start, rot_q, rot_target, rot_result_label,
       rot_small_turn, rot_big_turn, rot_note
"""
import os, sys
sys.path.insert(0, os.path.join(os.getcwd(), '_build'))
import tools as T

NAMES = ["rot_title","rot_desc","rot_how_title","rot_how1","rot_how2","rot_how3","rot_how4",
         "rot_start","rot_q","rot_target","rot_result_label","rot_small_turn","rot_big_turn","rot_note"]

K = {
"en": ["Mental Rotation Test","20 spatial puzzles measuring how well you turn shapes in your mind. No words, no numbers.","How This Test Works","A figure appears at the top. Below it are six candidates.","Exactly one is that figure turned to a new angle. The rest are mirror images — the same shape flipped over.","Turn the figure in your head to compare. The wider the turn, the harder it gets.","Nothing to read, and fresh figures every attempt.","Start Test →","Which one is the same figure, rotated?","Target figure","Spatial Reasoning","Small turns","Large turns","Scores are corrected for guessing. This is a short screening task, not a standardised spatial battery, and it has not been normed on a representative sample."],
"af": ["Geestelike Rotasietoets","20 ruimtelike raaisels wat meet hoe goed jy vorms in jou kop draai. Geen woorde, geen syfers.","Hoe Hierdie Toets Werk","'n Figuur verskyn bo. Daaronder is ses kandidate.","Presies een is daardie figuur na 'n nuwe hoek gedraai. Die res is spieëlbeelde — dieselfde vorm omgekeer.","Draai die figuur in jou kop om te vergelyk. Hoe wyer die draai, hoe moeiliker.","Niks om te lees nie, en nuwe figure elke keer.","Begin Toets →","Watter een is dieselfde figuur, gedraai?","Teikenfiguur","Ruimtelike Redenasie","Klein draaie","Groot draaie","Tellings word vir raaiwerk reggestel. Dit is 'n kort siftingstaak, nie 'n gestandaardiseerde ruimtelike battery nie, en dit is nie op 'n verteenwoordigende steekproef genormeer nie."],
"ar": ["اختبار الدوران الذهني","٢٠ لغزًا مكانيًا يقيس قدرتك على تدوير الأشكال في ذهنك. بلا كلمات ولا أرقام.","كيف يعمل هذا الاختبار","يظهر شكل في الأعلى، وتحته ستة مرشحين.","واحد فقط هو الشكل نفسه مُدارًا إلى زاوية جديدة. والبقية صور مرآوية، أي الشكل نفسه مقلوبًا.","أدِر الشكل في ذهنك للمقارنة. وكلما اتسعت الزاوية زادت الصعوبة.","لا شيء للقراءة، وأشكال جديدة في كل محاولة.","ابدأ الاختبار ←","أي واحد هو الشكل نفسه بعد التدوير؟","الشكل المرجعي","الاستدلال المكاني","دورات صغيرة","دورات كبيرة","تُصحَّح الدرجات لأثر التخمين. هذه مهمة فرز قصيرة، وليست بطارية مكانية مقننة، ولم تُعاير على عينة ممثلة."],
"bg": ["Тест за мислено въртене","20 пространствени задачи, които измерват колко добре въртите форми наум. Без думи и без числа.","Как работи този тест","Отгоре се появява фигура. Под нея има шест кандидата.","Точно една е същата фигура, завъртяна под нов ъгъл. Останалите са огледални образи — същата форма, обърната.","Завъртете фигурата наум, за да сравните. Колкото по-голям е ъгълът, толкова по-трудно.","Няма какво да се чете, а фигурите са нови при всеки опит.","Започни теста →","Коя е същата фигура, само завъртяна?","Целева фигура","Пространствено мислене","Малки завъртания","Големи завъртания","Резултатите се коригират за отгатване. Това е кратка скринингова задача, а не стандартизирана пространствена батерия, и не е нормирана върху представителна извадка."],
"cs": ["Test mentální rotace","20 prostorových úloh měřících, jak dobře otáčíte tvary v hlavě. Žádná slova, žádná čísla.","Jak tento test funguje","Nahoře se objeví obrazec. Pod ním je šest kandidátů.","Právě jeden je tentýž obrazec otočený do nového úhlu. Ostatní jsou zrcadlové obrazy — týž tvar převrácený.","Otočte si obrazec v hlavě a porovnejte. Čím větší otočení, tím obtížnější.","Nic se nečte a obrazce jsou při každém pokusu nové.","Spustit test →","Který je tentýž obrazec, jen otočený?","Cílový obrazec","Prostorové uvažování","Malá otočení","Velká otočení","Skóre je opraveno o hádání. Jde o krátkou screeningovou úlohu, ne o standardizovanou prostorovou baterii, a není normována na reprezentativním vzorku."],
"da": ["Mental rotationstest","20 rumlige opgaver, der måler, hvor godt du drejer former i hovedet. Ingen ord, ingen tal.","Sådan fungerer testen","Øverst vises en figur. Nedenunder står seks kandidater.","Præcis én er den samme figur drejet til en ny vinkel. Resten er spejlbilleder — samme form vendt om.","Drej figuren i hovedet for at sammenligne. Jo større drejning, jo sværere.","Intet at læse, og nye figurer hver gang.","Start test →","Hvilken er den samme figur, bare drejet?","Målfigur","Rumlig tænkning","Små drejninger","Store drejninger","Scoren er korrigeret for gætteri. Dette er en kort screeningsopgave, ikke et standardiseret rumligt testbatteri, og den er ikke normeret på en repræsentativ stikprøve."],
"de": ["Test zur mentalen Rotation","20 räumliche Aufgaben, die messen, wie gut Sie Formen im Kopf drehen. Keine Wörter, keine Zahlen.","So funktioniert der Test","Oben erscheint eine Figur, darunter sechs Kandidaten.","Genau eine ist dieselbe Figur in einem neuen Winkel. Die übrigen sind Spiegelbilder — dieselbe Form umgeklappt.","Drehen Sie die Figur im Kopf und vergleichen Sie. Je größer die Drehung, desto schwerer.","Nichts zu lesen, und bei jedem Versuch neue Figuren.","Test starten →","Welche ist dieselbe Figur, nur gedreht?","Zielfigur","Räumliches Denken","Kleine Drehungen","Große Drehungen","Die Punktzahl ist um Rateeffekte bereinigt. Dies ist eine kurze Screening-Aufgabe, keine normierte räumliche Testbatterie, und sie wurde nicht an einer repräsentativen Stichprobe geeicht."],
"el": ["Τεστ νοερής περιστροφής","20 χωρικά ερωτήματα που μετρούν πόσο καλά περιστρέφετε σχήματα στο μυαλό σας. Χωρίς λέξεις, χωρίς αριθμούς.","Πώς λειτουργεί το τεστ","Πάνω εμφανίζεται ένα σχήμα. Από κάτω υπάρχουν έξι υποψήφια.","Ακριβώς ένα είναι το ίδιο σχήμα σε νέα γωνία. Τα υπόλοιπα είναι κατοπτρικά είδωλα — το ίδιο σχήμα αναποδογυρισμένο.","Περιστρέψτε το σχήμα νοερά για να συγκρίνετε. Όσο μεγαλύτερη η γωνία, τόσο δυσκολότερο.","Τίποτα προς ανάγνωση, και νέα σχήματα σε κάθε προσπάθεια.","Έναρξη τεστ →","Ποιο είναι το ίδιο σχήμα, περιστραμμένο;","Σχήμα-στόχος","Χωρική σκέψη","Μικρές περιστροφές","Μεγάλες περιστροφές","Οι βαθμοί διορθώνονται για την τύχη. Πρόκειται για σύντομη δοκιμασία ανίχνευσης, όχι για σταθμισμένη χωρική συστοιχία, και δεν έχει σταθμιστεί σε αντιπροσωπευτικό δείγμα."],
"es": ["Test de rotación mental","20 puzles espaciales que miden lo bien que giras formas en tu mente. Sin palabras ni números.","Cómo funciona este test","Arriba aparece una figura. Debajo hay seis candidatas.","Solo una es esa misma figura girada a un ángulo nuevo. Las demás son imágenes especulares: la misma forma volteada.","Gira la figura mentalmente para comparar. Cuanto mayor el giro, más difícil.","Nada que leer, y figuras nuevas en cada intento.","Empezar test →","¿Cuál es la misma figura, girada?","Figura objetivo","Razonamiento espacial","Giros pequeños","Giros grandes","Las puntuaciones se corrigen por azar. Es una tarea breve de cribado, no una batería espacial estandarizada, y no está baremada con una muestra representativa."],
"et": ["Vaimse pöörlemise test","20 ruumilist ülesannet, mis mõõdavad, kui hästi pöörad kujundeid peas. Ei sõnu, ei numbreid.","Kuidas test töötab","Üleval ilmub kujund, all on kuus kandidaati.","Täpselt üks on sama kujund uue nurga all. Ülejäänud on peegelpildid — sama kujund ümber pööratud.","Pööra kujundit peas ja võrdle. Mida suurem pööre, seda raskem.","Midagi pole lugeda ja iga katse annab uued kujundid.","Alusta testi →","Milline on sama kujund, lihtsalt pööratud?","Sihtkujund","Ruumiline mõtlemine","Väikesed pöörded","Suured pöörded","Tulemused on äraarvamise suhtes korrigeeritud. See on lühike sõelumisülesanne, mitte standarditud ruumitestide komplekt, ja seda pole esindusliku valimi peal normitud."],
"fa": ["آزمون چرخش ذهنی","۲۰ معمای فضایی که می‌سنجد چقدر خوب شکل‌ها را در ذهن می‌چرخانید. بدون واژه و بدون عدد.","این آزمون چگونه کار می‌کند","در بالا یک شکل نمایان می‌شود و زیر آن شش گزینه.","تنها یکی همان شکل است که به زاویه‌ای تازه چرخیده. بقیه تصویر آینه‌ای‌اند؛ همان شکل، وارونه‌شده.","شکل را در ذهن بچرخانید و مقایسه کنید. هرچه زاویه بزرگ‌تر، دشوارتر.","چیزی برای خواندن نیست و هر بار شکل‌های تازه ساخته می‌شود.","شروع آزمون ←","کدام همان شکل است، فقط چرخیده؟","شکل مرجع","استدلال فضایی","چرخش‌های کوچک","چرخش‌های بزرگ","نمره‌ها بابت حدس‌زدن تصحیح می‌شوند. این یک تکلیف غربالگری کوتاه است، نه مجموعه‌آزمون فضایی استاندارد، و روی نمونه‌ای معرف هنجاریابی نشده است."],
"fi": ["Mielikuvarotaatiotesti","20 avaruudellista tehtävää, jotka mittaavat kuinka hyvin käännät muotoja mielessäsi. Ei sanoja, ei numeroita.","Näin testi toimii","Ylhäällä näkyy kuvio. Sen alla on kuusi vaihtoehtoa.","Täsmälleen yksi on sama kuvio uuteen kulmaan käännettynä. Muut ovat peilikuvia — sama muoto käännettynä ympäri.","Käännä kuviota mielessäsi ja vertaa. Mitä suurempi käännös, sitä vaikeampi.","Ei mitään luettavaa, ja uudet kuviot joka kerta.","Aloita testi →","Mikä on sama kuvio käännettynä?","Kohdekuvio","Avaruudellinen päättely","Pienet käännökset","Suuret käännökset","Pisteet on korjattu arvaamisen varalta. Tämä on lyhyt seulontatehtävä, ei normitettu avaruudellinen testipatteristo, eikä sitä ole normitettu edustavalla otoksella."],
"fr": ["Test de rotation mentale","20 énigmes spatiales mesurant votre aptitude à faire tourner des formes mentalement. Ni mots ni chiffres.","Comment fonctionne ce test","Une figure apparaît en haut. En dessous, six candidates.","Une seule est cette figure tournée d'un nouvel angle. Les autres sont des images miroir : la même forme retournée.","Faites tourner la figure dans votre tête pour comparer. Plus l'angle est grand, plus c'est difficile.","Rien à lire, et des figures nouvelles à chaque essai.","Commencer le test →","Laquelle est la même figure, simplement tournée ?","Figure cible","Raisonnement spatial","Petites rotations","Grandes rotations","Les scores sont corrigés du hasard. Il s'agit d'une tâche de dépistage brève, non d'une batterie spatiale étalonnée, et elle n'a pas été normée sur un échantillon représentatif."],
"he": ["מבחן סיבוב מנטלי","20 חידות מרחביות שמודדות כמה טוב אתם מסובבים צורות בראש. בלי מילים ובלי מספרים.","איך המבחן עובד","למעלה מופיעה צורה, ומתחתיה שש מועמדות.","בדיוק אחת היא אותה צורה בזווית חדשה. השאר הן תמונות ראי — אותה צורה הפוכה.","סובבו את הצורה בראש כדי להשוות. ככל שהסיבוב גדול יותר, כך קשה יותר.","אין מה לקרוא, והצורות חדשות בכל ניסיון.","התחלת המבחן ←","איזו היא אותה צורה, רק מסובבת?","צורת היעד","חשיבה מרחבית","סיבובים קטנים","סיבובים גדולים","הציונים מתוקנים עבור ניחוש. זו מטלת סינון קצרה, לא סוללת מבחנים מרחבית מתוקננת, והיא לא נורמלה על מדגם מייצג."],
"hi": ["मानसिक घूर्णन परीक्षण","20 स्थानिक पहेलियाँ जो मापती हैं कि आप मन में आकृतियाँ कितनी अच्छी तरह घुमाते हैं। न शब्द, न अंक।","यह परीक्षण कैसे काम करता है","ऊपर एक आकृति दिखती है, नीचे छह विकल्प।","ठीक एक वही आकृति है, नए कोण पर घुमाई हुई। बाकी दर्पण-प्रतिबिंब हैं — वही आकृति पलटी हुई।","तुलना के लिए आकृति को मन में घुमाइए। कोण जितना बड़ा, उतना कठिन।","पढ़ने को कुछ नहीं, और हर प्रयास में नई आकृतियाँ।","परीक्षण शुरू करें →","कौन-सी वही आकृति है, बस घुमाई हुई?","लक्ष्य आकृति","स्थानिक तर्क","छोटे घुमाव","बड़े घुमाव","अंक अनुमान के लिए सुधारे जाते हैं। यह एक संक्षिप्त स्क्रीनिंग कार्य है, मानकीकृत स्थानिक परीक्षण-समूह नहीं, और इसे प्रतिनिधि नमूने पर मानकीकृत नहीं किया गया है।"],
"hr": ["Test mentalne rotacije","20 prostornih zadataka koji mjere koliko dobro okrećete oblike u glavi. Bez riječi i bez brojeva.","Kako ovaj test radi","Gore se pojavi lik, ispod njega šest kandidata.","Točno jedan je isti lik okrenut pod novim kutom. Ostali su zrcalne slike — isti oblik preokrenut.","Okrenite lik u glavi i usporedite. Što je zaokret veći, to je teže.","Nema se što čitati, a likovi su novi pri svakom pokušaju.","Pokreni test →","Koji je isti lik, samo zakrenut?","Ciljni lik","Prostorno zaključivanje","Mali zaokreti","Veliki zaokreti","Rezultati su ispravljeni za pogađanje. Ovo je kratak probirni zadatak, a ne standardizirana prostorna baterija, i nije normiran na reprezentativnom uzorku."],
"hu": ["Mentális forgatás teszt","20 téri feladat, amely azt méri, milyen jól forgat alakzatokat fejben. Se szavak, se számok.","Hogyan működik a teszt","Fent megjelenik egy alakzat, alatta hat jelölt.","Pontosan egy ugyanaz az alakzat új szögben. A többi tükörkép — ugyanaz az alak átfordítva.","Forgassa el fejben az alakzatot és hasonlítsa össze. Minél nagyobb a fordulat, annál nehezebb.","Semmit sem kell olvasni, és minden próbálkozáskor új alakzatok.","Teszt indítása →","Melyik ugyanaz az alakzat, csak elforgatva?","Célalakzat","Téri gondolkodás","Kis fordulatok","Nagy fordulatok","A pontszám a találgatásra korrigált. Ez rövid szűrőfeladat, nem szabványosított téri tesztsorozat, és nem normálták reprezentatív mintán."],
"id": ["Tes Rotasi Mental","20 teka-teki spasial yang mengukur seberapa baik Anda memutar bentuk dalam pikiran. Tanpa kata, tanpa angka.","Cara Kerja Tes Ini","Sebuah gambar muncul di atas. Di bawahnya ada enam kandidat.","Tepat satu adalah gambar yang sama diputar ke sudut baru. Sisanya bayangan cermin — bentuk yang sama dibalik.","Putar gambar dalam kepala untuk membandingkan. Makin besar putaran, makin sulit.","Tak ada yang perlu dibaca, dan gambar baru setiap percobaan.","Mulai Tes →","Mana yang merupakan gambar sama, hanya diputar?","Gambar acuan","Penalaran Spasial","Putaran kecil","Putaran besar","Skor dikoreksi untuk tebakan. Ini tugas penyaringan singkat, bukan baterai spasial baku, dan belum dinormakan pada sampel representatif."],
"it": ["Test di rotazione mentale","20 rompicapi spaziali che misurano quanto bene ruoti le forme nella mente. Nessuna parola, nessun numero.","Come funziona questo test","In alto compare una figura, sotto sei candidate.","Esattamente una è la stessa figura ruotata a una nuova angolazione. Le altre sono immagini speculari: la stessa forma ribaltata.","Ruota la figura nella mente per confrontarla. Più ampia la rotazione, più difficile.","Niente da leggere, e figure nuove a ogni tentativo.","Inizia il test →","Quale è la stessa figura, solo ruotata?","Figura bersaglio","Ragionamento spaziale","Rotazioni piccole","Rotazioni ampie","I punteggi sono corretti per il caso. È un compito di screening breve, non una batteria spaziale standardizzata, e non è tarato su un campione rappresentativo."],
"ja": ["心的回転テスト","頭の中で形を回す力を測る20問の空間課題です。文字も数字も使いません。","このテストの進め方","上に図形が出て、その下に6つの候補が並びます。","そのうち1つだけが同じ図形を別の角度に回したものです。残りは鏡像、つまり同じ形を裏返したものです。","頭の中で図形を回して見比べてください。回す角度が大きいほど難しくなります。","読むものはなく、毎回新しい図形が出ます。","テストを始める →","同じ図形を回したものはどれでしょう。","基準となる図形","空間認識","小さな回転","大きな回転","得点は当て推量の分を補正しています。これは短い簡易課題であり、標準化された空間能力検査ではありません。代表標本による基準値もありません。"],
"ko": ["심적 회전 검사","머릿속에서 도형을 얼마나 잘 돌리는지 재는 20개의 공간 문제입니다. 글자도 숫자도 없습니다.","검사 진행 방식","위에 도형이 하나 나오고 아래에 여섯 개의 후보가 있습니다.","그중 하나만 같은 도형을 새 각도로 돌린 것입니다. 나머지는 거울상, 곧 같은 모양을 뒤집은 것입니다.","머릿속에서 도형을 돌려 비교해 보세요. 각도가 클수록 어려워집니다.","읽을 것이 없고, 시도할 때마다 새로운 도형이 나옵니다.","검사 시작 →","같은 도형을 돌린 것은 어느 것일까요?","기준 도형","공간 추론","작은 회전","큰 회전","점수는 추측을 보정한 값입니다. 짧은 선별 과제이며 표준화된 공간 능력 검사가 아니고, 대표 표본으로 규준을 만들지도 않았습니다."],
"lt": ["Mintinio sukimo testas","20 erdvinių užduočių, matuojančių, kaip gerai mintyse sukate figūras. Jokių žodžių ir skaičių.","Kaip veikia šis testas","Viršuje pasirodo figūra, po ja – šeši variantai.","Lygiai vienas yra ta pati figūra, pasukta nauju kampu. Kiti – veidrodiniai atvaizdai, ta pati forma apversta.","Pasukite figūrą mintyse ir palyginkite. Kuo didesnis posūkis, tuo sunkiau.","Nieko skaityti nereikia, o figūros kaskart naujos.","Pradėti testą →","Kuri yra ta pati figūra, tik pasukta?","Tikslinė figūra","Erdvinis mąstymas","Maži posūkiai","Dideli posūkiai","Rezultatai pataisyti dėl spėliojimo. Tai trumpa atrankos užduotis, o ne standartizuota erdvinių testų baterija, ir ji nestandartizuota reprezentatyvioje imtyje."],
"lv": ["Mentālās rotācijas tests","20 telpiski uzdevumi, kas mēra, cik labi prātā pagriežat formas. Bez vārdiem un cipariem.","Kā šis tests darbojas","Augšā parādās figūra, zem tās – seši varianti.","Tieši viens ir tā pati figūra, pagriezta jaunā leņķī. Pārējie ir spoguļattēli — tā pati forma apgriezta.","Pagrieziet figūru prātā un salīdziniet. Jo lielāks pagrieziens, jo grūtāk.","Nekas nav jālasa, un figūras katrā mēģinājumā ir jaunas.","Sākt testu →","Kura ir tā pati figūra, tikai pagriezta?","Mērķa figūra","Telpiskā domāšana","Mazi pagriezieni","Lieli pagriezieni","Rezultāti ir koriģēti pēc minēšanas. Šis ir īss skrīninga uzdevums, nevis standartizēta telpisko testu baterija, un tas nav normēts reprezentatīvā izlasē."],
"mk": ["Тест за ментална ротација","20 просторни задачи што мерат колку добро вртите форми во главата. Без зборови и без бројки.","Како функционира овој тест","Горе се појавува фигура, под неа шест кандидати.","Точно една е истата фигура завртена под нов агол. Останатите се огледални слики — истата форма превртена.","Завртете ја фигурата во главата за да споредите. Колку е поголем аголот, толку е потешко.","Нема што да се чита, а фигурите се нови при секој обид.","Почни тест →","Која е истата фигура, само завртена?","Целна фигура","Просторно расудување","Мали вртења","Големи вртења","Резултатите се коригирани за погодување. Ова е кратка скрининг задача, а не стандардизирана просторна батерија, и не е нормирана на репрезентативен примерок."],
"ms": ["Ujian Putaran Mental","20 teka-teki ruang yang mengukur sebaik mana anda memutar bentuk dalam fikiran. Tiada perkataan, tiada nombor.","Cara Ujian Ini Berfungsi","Satu rajah muncul di atas. Di bawahnya ada enam calon.","Tepat satu ialah rajah yang sama diputar ke sudut baharu. Selebihnya imej cermin — bentuk yang sama diterbalikkan.","Putarkan rajah dalam fikiran untuk membanding. Semakin besar putaran, semakin sukar.","Tiada apa untuk dibaca, dan rajah baharu setiap percubaan.","Mula Ujian →","Yang mana rajah yang sama, cuma diputar?","Rajah sasaran","Penaakulan Ruang","Putaran kecil","Putaran besar","Skor diperbetulkan untuk tekaan. Ini tugas saringan ringkas, bukan bateri ujian ruang piawai, dan belum dinormakan pada sampel mewakili."],
"nl": ["Mentale rotatietest","20 ruimtelijke puzzels die meten hoe goed je vormen in je hoofd draait. Geen woorden, geen cijfers.","Hoe deze test werkt","Bovenaan verschijnt een figuur. Daaronder staan zes kandidaten.","Precies één is dezelfde figuur onder een nieuwe hoek. De rest zijn spiegelbeelden — dezelfde vorm omgeklapt.","Draai de figuur in je hoofd om te vergelijken. Hoe groter de draai, hoe lastiger.","Niets te lezen, en elke poging nieuwe figuren.","Test starten →","Welke is dezelfde figuur, maar gedraaid?","Doelfiguur","Ruimtelijk redeneren","Kleine draaiingen","Grote draaiingen","Scores zijn gecorrigeerd voor gokken. Dit is een korte screeningstaak, geen genormeerde ruimtelijke testbatterij, en hij is niet genormeerd op een representatieve steekproef."],
"no": ["Mental rotasjonstest","20 romlige oppgaver som måler hvor godt du snur former i hodet. Ingen ord, ingen tall.","Slik fungerer testen","Øverst vises en figur. Under den står seks kandidater.","Nøyaktig én er den samme figuren snudd til en ny vinkel. Resten er speilbilder — samme form vendt om.","Snu figuren i hodet for å sammenligne. Jo større dreining, jo vanskeligere.","Ingenting å lese, og nye figurer hver gang.","Start test →","Hvilken er den samme figuren, bare dreid?","Målfigur","Romlig tenkning","Små dreininger","Store dreininger","Skårene er korrigert for gjetting. Dette er en kort screeningoppgave, ikke et normert romlig testbatteri, og det er ikke normert på et representativt utvalg."],
"pl": ["Test rotacji mentalnej","20 zadań przestrzennych mierzących, jak dobrze obracasz kształty w głowie. Bez słów i bez liczb.","Jak działa ten test","U góry pojawia się figura, pod nią sześć kandydatek.","Dokładnie jedna to ta sama figura obrócona pod nowym kątem. Pozostałe to odbicia lustrzane — ten sam kształt odwrócony.","Obróć figurę w myślach i porównaj. Im większy obrót, tym trudniej.","Nic do czytania, a figury są nowe przy każdym podejściu.","Rozpocznij test →","Która to ta sama figura, tylko obrócona?","Figura wzorcowa","Myślenie przestrzenne","Małe obroty","Duże obroty","Wyniki są korygowane o zgadywanie. To krótkie zadanie przesiewowe, a nie znormalizowana bateria testów przestrzennych, i nie zostało znormalizowane na reprezentatywnej próbie."],
"pt": ["Teste de rotação mental","20 puzzles espaciais que medem o quão bem roda formas na sua cabeça. Sem palavras nem números.","Como funciona este teste","No topo aparece uma figura. Abaixo estão seis candidatas.","Exatamente uma é a mesma figura rodada para um novo ângulo. As restantes são imagens espelhadas — a mesma forma invertida.","Rode a figura na sua cabeça para comparar. Quanto maior a rotação, mais difícil.","Nada para ler, e figuras novas em cada tentativa.","Começar teste →","Qual é a mesma figura, apenas rodada?","Figura alvo","Raciocínio espacial","Rotações pequenas","Rotações grandes","As pontuações são corrigidas para o acaso. Esta é uma tarefa de rastreio breve, não uma bateria espacial aferida, e não foi normalizada numa amostra representativa."],
"ro": ["Test de rotație mentală","20 de puzzle-uri spațiale care măsoară cât de bine rotești forme în minte. Fără cuvinte, fără cifre.","Cum funcționează acest test","Sus apare o figură. Dedesubt sunt șase variante.","Exact una este aceeași figură rotită la un unghi nou. Restul sunt imagini în oglindă — aceeași formă întoarsă.","Rotește figura în minte ca să compari. Cu cât rotația e mai mare, cu atât e mai greu.","Nimic de citit, iar figurile sunt noi la fiecare încercare.","Începe testul →","Care este aceeași figură, doar rotită?","Figura țintă","Raționament spațial","Rotații mici","Rotații mari","Scorurile sunt corectate pentru ghicire. Este o sarcină scurtă de screening, nu o baterie spațială etalonată, și nu a fost normată pe un eșantion reprezentativ."],
"ru": ["Тест мысленного вращения","20 пространственных задач, измеряющих, насколько хорошо вы вращаете фигуры в уме. Ни слов, ни цифр.","Как устроен тест","Сверху появляется фигура, под ней — шесть вариантов.","Ровно один — та же фигура, повёрнутая на новый угол. Остальные зеркальные: та же форма, перевёрнутая.","Поверните фигуру в уме и сравните. Чем больше угол, тем труднее.","Читать нечего, и фигуры каждый раз новые.","Начать тест →","Какая фигура та же самая, только повёрнутая?","Целевая фигура","Пространственное мышление","Малые повороты","Большие повороты","Баллы скорректированы на угадывание. Это короткая скрининговая задача, а не стандартизированная батарея пространственных тестов, и она не нормирована на репрезентативной выборке."],
"sk": ["Test mentálnej rotácie","20 priestorových úloh, ktoré merajú, ako dobre otáčate tvary v hlave. Žiadne slová, žiadne čísla.","Ako tento test funguje","Hore sa objaví útvar, pod ním šesť kandidátov.","Práve jeden je ten istý útvar otočený do nového uhla. Ostatné sú zrkadlové obrazy — ten istý tvar prevrátený.","Otočte si útvar v hlave a porovnajte. Čím väčšie otočenie, tým ťažšie.","Nič sa nečíta a útvary sú pri každom pokuse nové.","Spustiť test →","Ktorý je ten istý útvar, len otočený?","Cieľový útvar","Priestorové uvažovanie","Malé otočenia","Veľké otočenia","Skóre je opravené o hádanie. Ide o krátku skríningovú úlohu, nie o štandardizovanú priestorovú batériu, a nie je normovaná na reprezentatívnej vzorke."],
"sl": ["Test miselne rotacije","20 prostorskih nalog, ki merijo, kako dobro v mislih vrtite oblike. Brez besed in brez številk.","Kako deluje ta test","Zgoraj se pojavi lik, pod njim šest kandidatov.","Natanko en je isti lik, zavrten pod novim kotom. Ostali so zrcalne slike — ista oblika, obrnjena.","Zavrtite lik v mislih in primerjajte. Večji kot je zasuk, težje je.","Ni ničesar za branje, liki pa so ob vsakem poskusu novi.","Začni test →","Kateri je isti lik, le zavrten?","Ciljni lik","Prostorsko sklepanje","Majhni zasuki","Veliki zasuki","Rezultati so popravljeni za ugibanje. To je kratka presejalna naloga, ne standardizirana prostorska baterija, in ni normirana na reprezentativnem vzorcu."],
"sq": ["Testi i rrotullimit mendor","20 enigma hapësinore që matin sa mirë i rrotulloni format në mendje. Pa fjalë dhe pa numra.","Si funksionon ky test","Lart shfaqet një figurë. Poshtë saj janë gjashtë kandidate.","Vetëm një është e njëjta figurë e rrotulluar në një kënd të ri. Të tjerat janë pasqyrime — e njëjta formë e kthyer.","Rrotullojeni figurën në mendje për ta krahasuar. Sa më i madh rrotullimi, aq më e vështirë.","Asgjë për të lexuar dhe figura të reja çdo herë.","Fillo testin →","Cila është e njëjta figurë, vetëm e rrotulluar?","Figura e synuar","Arsyetim hapësinor","Rrotullime të vogla","Rrotullime të mëdha","Rezultatet korrigjohen për hamendësimin. Kjo është një detyrë e shkurtër filtruese, jo një bateri hapësinore e standardizuar, dhe nuk është normuar mbi një kampion përfaqësues."],
"sr": ["Тест менталне ротације","20 просторних задатака који мере колико добро окрећете облике у глави. Без речи и без бројева.","Како овај тест функционише","Горе се појављује лик, испод њега шест кандидата.","Тачно један је исти лик окренут под новим углом. Остали су огледалне слике — исти облик преврнут.","Окрените лик у глави и упоредите. Што је заокрет већи, то је теже.","Нема шта да се чита, а ликови су нови при сваком покушају.","Покрени тест →","Који је исти лик, само заокренут?","Циљни лик","Просторно закључивање","Мали заокрети","Велики заокрети","Резултати су исправљени за погађање. Ово је кратак скрининг задатак, а не стандардизована просторна батерија, и није нормиран на репрезентативном узорку."],
"sv": ["Test i mental rotation","20 rumsliga uppgifter som mäter hur väl du vrider former i huvudet. Inga ord, inga siffror.","Så fungerar testet","Överst visas en figur. Under den finns sex kandidater.","Exakt en är samma figur vriden till en ny vinkel. Resten är spegelbilder — samma form vänd.","Vrid figuren i huvudet och jämför. Ju större vridning, desto svårare.","Inget att läsa, och nya figurer varje gång.","Starta testet →","Vilken är samma figur, fast vriden?","Målfigur","Rumsligt tänkande","Små vridningar","Stora vridningar","Poängen är korrigerade för gissning. Detta är en kort screeninguppgift, inte ett normerat rumsligt testbatteri, och det är inte normerat på ett representativt urval."],
"sw": ["Kipimo cha Mzunguko wa Kiakili","Mafumbo 20 ya nafasi yanayopima jinsi unavyozungusha maumbo akilini. Hakuna maneno wala namba.","Jinsi Kipimo Hiki Kinavyofanya Kazi","Umbo linaonekana juu. Chini yake kuna chaguo sita.","Moja tu ndilo umbo lilelile lililozungushwa kwa pembe mpya. Mengine ni taswira za kioo — umbo lilelile likiwa limegeuzwa.","Zungusha umbo akilini ili kulinganisha. Kadri pembe inavyokuwa kubwa, ndivyo inavyokuwa vigumu.","Hakuna cha kusoma, na maumbo mapya kila jaribio.","Anza Kipimo →","Ni lipi lenye umbo lilelile, likiwa limezungushwa?","Umbo lengwa","Ufikiri wa Nafasi","Mizunguko midogo","Mizunguko mikubwa","Alama zimerekebishwa kwa ubashiri. Hii ni kazi fupi ya uchunguzi, si mkusanyiko wa vipimo vya nafasi vilivyosawazishwa, na haijasawazishwa kwa sampuli wakilishi."],
"th": ["แบบทดสอบการหมุนภาพในใจ","โจทย์เชิงพื้นที่ 20 ข้อ วัดว่าคุณหมุนรูปทรงในใจได้ดีเพียงใด ไม่มีตัวอักษรและตัวเลข","แบบทดสอบนี้ทำงานอย่างไร","ด้านบนจะมีรูปหนึ่งปรากฏ ด้านล่างมีตัวเลือกหกรูป","มีเพียงรูปเดียวที่เป็นรูปเดิมหมุนไปอีกมุมหนึ่ง ที่เหลือเป็นภาพสะท้อนกระจก คือรูปเดิมที่ถูกพลิก","หมุนรูปในใจเพื่อเปรียบเทียบ ยิ่งหมุนมากยิ่งยาก","ไม่มีอะไรต้องอ่าน และได้รูปใหม่ทุกครั้งที่ทำ","เริ่มทำแบบทดสอบ →","รูปใดคือรูปเดิมที่ถูกหมุน","รูปต้นแบบ","การให้เหตุผลเชิงพื้นที่","หมุนน้อย","หมุนมาก","คะแนนได้รับการปรับแก้การเดาแล้ว นี่เป็นงานคัดกรองสั้น ๆ ไม่ใช่ชุดแบบทดสอบเชิงพื้นที่ที่มีมาตรฐาน และยังไม่ได้สร้างเกณฑ์ปกติจากกลุ่มตัวอย่างที่เป็นตัวแทน"],
"tl": ["Pagsusulit sa Mental Rotation","20 palaisipang pang-espasyo na sumusukat kung gaano kahusay mong pinaiikot ang mga hugis sa isip. Walang salita, walang numero.","Paano Ito Gumagana","May lalabas na hugis sa itaas. Sa ilalim nito ay anim na kandidato.","Iisa lang ang siya ring hugis na ipinihit sa bagong anggulo. Ang iba ay salamin — parehong hugis na binaligtad.","Iikot ang hugis sa isip mo para ikumpara. Habang lumalaki ang ikot, lalong humihirap.","Walang babasahin, at bagong hugis sa bawat pagsubok.","Simulan ang Pagsusulit →","Alin ang siya ring hugis, ipinihit lang?","Hugis na target","Pangangatwirang Pang-espasyo","Maliliit na ikot","Malalaking ikot","Itinatama ang iskor para sa panghuhula. Maikling screening ito, hindi standardisadong baterya ng pagsusulit sa espasyo, at hindi pa naisasanaysay sa kinatawang sampol."],
"tr": ["Zihinsel Döndürme Testi","Şekilleri zihninizde ne kadar iyi döndürdüğünüzü ölçen 20 uzamsal bulmaca. Kelime yok, sayı yok.","Bu Test Nasıl İşler","Üstte bir şekil görünür, altında altı aday vardır.","Yalnızca biri aynı şeklin yeni bir açıya döndürülmüş hâlidir. Geri kalanlar ayna görüntüsüdür — aynı şeklin ters çevrilmişi.","Şekli zihninizde döndürüp karşılaştırın. Açı büyüdükçe zorlaşır.","Okunacak bir şey yok ve her denemede yeni şekiller gelir.","Teste Başla →","Hangisi aynı şeklin döndürülmüş hâli?","Hedef şekil","Uzamsal Muhakeme","Küçük dönüşler","Büyük dönüşler","Puanlar tahmine göre düzeltilmiştir. Bu kısa bir tarama görevidir, standardize edilmiş bir uzamsal test bataryası değildir ve temsili bir örneklem üzerinde normlanmamıştır."],
"uk": ["Тест на уявне обертання","20 просторових задач, які вимірюють, наскільки добре ви обертаєте фігури подумки. Ні слів, ні цифр.","Як працює цей тест","Угорі з'являється фігура, під нею — шість варіантів.","Рівно один — та сама фігура, повернута на новий кут. Решта дзеркальні: та сама форма, перевернута.","Оберніть фігуру подумки й порівняйте. Що більший кут, то важче.","Читати нічого, а фігури щоразу нові.","Почати тест →","Яка фігура та сама, лише повернута?","Цільова фігура","Просторове мислення","Малі повороти","Великі повороти","Бали скориговано на вгадування. Це коротке скринінгове завдання, а не стандартизована батарея просторових тестів, і воно не нормоване на репрезентативній вибірці."],
"vi": ["Bài kiểm tra xoay hình trong đầu","20 câu đố không gian đo khả năng xoay hình trong đầu của bạn. Không chữ, không số.","Bài kiểm tra hoạt động thế nào","Một hình xuất hiện ở trên, bên dưới là sáu lựa chọn.","Đúng một lựa chọn là chính hình đó được xoay sang góc mới. Số còn lại là ảnh phản chiếu — cùng hình dạng nhưng bị lật.","Hãy xoay hình trong đầu để so sánh. Góc xoay càng lớn càng khó.","Không có gì để đọc, và mỗi lần làm lại có hình mới.","Bắt đầu →","Hình nào là cùng một hình, chỉ được xoay?","Hình mẫu","Tư duy không gian","Xoay ít","Xoay nhiều","Điểm đã được hiệu chỉnh cho việc đoán. Đây là bài sàng lọc ngắn, không phải bộ trắc nghiệm không gian chuẩn hóa, và chưa được xây dựng chuẩn trên mẫu đại diện."],
"zh": ["心理旋转测验","20 道空间题目，测量你在脑中旋转图形的能力。不涉及文字与数字。","这项测验怎么进行","上方出现一个图形，下方是六个选项。","其中只有一个是同一图形转到了新的角度，其余都是镜像，也就是同一形状被翻转过来。","在脑中把图形转一转再比较。转动的角度越大越难。","没有需要阅读的内容，每次作答都是全新图形。","开始测验 →","哪一个是同一图形，只是旋转过？","目标图形","空间推理","小角度旋转","大角度旋转","分数已做猜测校正。这是一项简短的初筛任务，不是标准化的空间能力测验组合，也未在代表性样本上建立常模。"],
}

ready = T.ready_langs()
missing = [l for l in ready if l not in K]
if missing:
    print('NO TRANSLATIONS FOR:', missing); sys.exit(1)
for lang in ready:
    v = K[lang]
    assert len(v) == len(NAMES), (lang, len(v))
    T.set_keys(lang, dict(zip(NAMES, v)))
print('done: %d rotation keys x %d languages' % (len(NAMES), len(ready)))
