/* CoreSkillAI — Big Five Personality Test (IPIP-50) */
(function(){
function _t(k,fb){return window.I18n?.t(k)||fb||k;}
// 50 items from the public-domain IPIP Big-Five Factor Markers (Goldberg, 1992)
// Format: [text, trait, reverse(bool)]
// Traits: E=Extraversion, A=Agreeableness, C=Conscientiousness, N=Neuroticism, O=Openness
// English master list. Translations live in ITEMS_I18N below; a market with
// no entry falls back to English. Note this is a FALLBACK, not a feature:
// a personality item a reader cannot understand produces a meaningless answer.
const ITEMS_EN=[
  ["Am the life of the party","E",false],
  ["Feel little concern for others","A",true],
  ["Am always prepared","C",false],
  ["Get stressed out easily","N",false],
  ["Have a rich vocabulary","O",false],
  ["Don't talk a lot","E",true],
  ["Am interested in people","A",false],
  ["Leave my belongings around","C",true],
  ["Am relaxed most of the time","N",true],
  ["Have difficulty understanding abstract ideas","O",true],
  ["Feel comfortable around people","E",false],
  ["Insult people","A",true],
  ["Pay attention to details","C",false],
  ["Worry about things","N",false],
  ["Have a vivid imagination","O",false],
  ["Keep in the background","E",true],
  ["Sympathize with others' feelings","A",false],
  ["Make a mess of things","C",true],
  ["Seldom feel blue","N",true],
  ["Am not interested in abstract ideas","O",true],
  ["Start conversations","E",false],
  ["Am not really interested in others","A",true],
  ["Get chores done right away","C",false],
  ["Get upset easily","N",false],
  ["Have excellent ideas","O",false],
  ["Have little to say","E",true],
  ["Have a soft heart","A",false],
  ["Often forget to put things back in their proper place","C",true],
  ["Am not easily bothered by things","N",true],
  ["Do not have a good imagination","O",true],
  ["Talk to a lot of different people at parties","E",false],
  ["Am not really interested in others","A",true],
  ["Like order","C",false],
  ["Change my mood a lot","N",false],
  ["Am quick to understand things","O",false],
  ["Don't like to draw attention to myself","E",true],
  ["Take time out for others","A",false],
  ["Shirk my duties","C",true],
  ["Have frequent mood swings","N",false],
  ["Use difficult words","O",false],
  ["Don't mind being the center of attention","E",false],
  ["Feel others' emotions","A",false],
  ["Follow a schedule","C",false],
  ["Get irritated easily","N",false],
  ["Spend time reflecting on things","O",false],
  ["Am quiet around strangers","E",true],
  ["Make people feel at ease","A",false],
  ["Am exacting in my work","C",false],
  ["Often feel blue","N",false],
  ["Am full of ideas","O",false],
];

const ITEMS_I18N = {
  de: [
    "Bin der Mittelpunkt jeder Feier",
    "Kümmere mich wenig um andere",
    "Bin immer vorbereitet",
    "Gerate leicht unter Stress",
    "Habe einen großen Wortschatz",
    "Rede nicht viel",
    "Interessiere mich für Menschen",
    "Lasse meine Sachen herumliegen",
    "Bin meistens entspannt",
    "Habe Mühe, abstrakte Ideen zu verstehen",
    "Fühle mich in Gesellschaft wohl",
    "Beleidige andere",
    "Achte auf Details",
    "Mache mir viele Sorgen",
    "Habe eine lebhafte Fantasie",
    "Halte mich im Hintergrund",
    "Fühle mit anderen mit",
    "Bringe Dinge durcheinander",
    "Bin selten niedergeschlagen",
    "Interessiere mich nicht für abstrakte Ideen",
    "Beginne Gespräche",
    "Interessiere mich nicht wirklich für andere",
    "Erledige Aufgaben sofort",
    "Bin schnell aufgebracht",
    "Habe ausgezeichnete Ideen",
    "Habe wenig zu sagen",
    "Habe ein weiches Herz",
    "Vergesse oft, Dinge an ihren Platz zurückzulegen",
    "Lasse mich nicht leicht aus der Ruhe bringen",
    "Habe keine gute Vorstellungskraft",
    "Rede auf Feiern mit vielen verschiedenen Leuten",
    "Andere Menschen lassen mich eher kalt",
    "Mag Ordnung",
    "Meine Stimmung wechselt oft",
    "Verstehe Dinge schnell",
    "Ziehe ungern Aufmerksamkeit auf mich",
    "Nehme mir Zeit für andere",
    "Drücke mich vor meinen Pflichten",
    "Habe häufige Stimmungsschwankungen",
    "Verwende anspruchsvolle Wörter",
    "Stehe gern im Mittelpunkt",
    "Spüre die Gefühle anderer",
    "Halte mich an einen Zeitplan",
    "Bin schnell gereizt",
    "Denke viel über Dinge nach",
    "Bin unter Fremden still",
    "Gebe anderen ein gutes Gefühl",
    "Arbeite sehr genau",
    "Bin oft niedergeschlagen",
    "Stecke voller Ideen",
  ],
  es: [
    "Soy el alma de la fiesta",
    "Me preocupo poco por los demás",
    "Estoy siempre preparado",
    "Me estreso con facilidad",
    "Tengo un vocabulario rico",
    "No hablo mucho",
    "Me intereso por la gente",
    "Dejo mis cosas tiradas",
    "Estoy relajado la mayor parte del tiempo",
    "Me cuesta entender ideas abstractas",
    "Me siento cómodo entre la gente",
    "Insulto a los demás",
    "Presto atención a los detalles",
    "Me preocupo por las cosas",
    "Tengo una imaginación vívida",
    "Me mantengo en segundo plano",
    "Comprendo los sentimientos de los demás",
    "Lo desordeno todo",
    "Rara vez me siento decaído",
    "No me interesan las ideas abstractas",
    "Inicio conversaciones",
    "No me interesan realmente los demás",
    "Hago las tareas de inmediato",
    "Me altero con facilidad",
    "Tengo ideas excelentes",
    "Tengo poco que decir",
    "Tengo buen corazón",
    "Olvido a menudo devolver las cosas a su sitio",
    "No me molestan fácilmente las cosas",
    "No tengo buena imaginación",
    "Hablo con mucha gente distinta en las fiestas",
    "Los demás me resultan bastante indiferentes",
    "Me gusta el orden",
    "Mi estado de ánimo cambia mucho",
    "Entiendo las cosas rápido",
    "No me gusta llamar la atención",
    "Saco tiempo para los demás",
    "Eludo mis obligaciones",
    "Tengo cambios de humor frecuentes",
    "Uso palabras complicadas",
    "No me importa ser el centro de atención",
    "Percibo las emociones de los demás",
    "Sigo un horario",
    "Me irrito con facilidad",
    "Dedico tiempo a reflexionar",
    "Estoy callado con desconocidos",
    "Hago que la gente se sienta a gusto",
    "Soy muy meticuloso en mi trabajo",
    "Me siento decaído a menudo",
    "Estoy lleno de ideas",
  ],
  fr: [
    "Suis l'animateur de la soirée",
    "Me soucie peu des autres",
    "Suis toujours préparé",
    "Suis vite stressé",
    "Ai un vocabulaire riche",
    "Ne parle pas beaucoup",
    "M'intéresse aux gens",
    "Laisse traîner mes affaires",
    "Suis détendu la plupart du temps",
    "Ai du mal à comprendre les idées abstraites",
    "Me sens à l'aise en société",
    "Insulte les autres",
    "Fais attention aux détails",
    "Me fais du souci",
    "Ai une imagination vive",
    "Reste en retrait",
    "Compatis aux sentiments des autres",
    "Mets le désordre partout",
    "Me sens rarement abattu",
    "Ne m'intéresse pas aux idées abstraites",
    "Engage la conversation",
    "Ne m'intéresse pas vraiment aux autres",
    "Fais mes tâches tout de suite",
    "Me contrarie facilement",
    "Ai d'excellentes idées",
    "Ai peu de choses à dire",
    "Ai bon cœur",
    "Oublie souvent de ranger les choses à leur place",
    "Ne me laisse pas facilement perturber",
    "N'ai pas une bonne imagination",
    "Parle à beaucoup de monde en soirée",
    "Les autres me laissent plutôt indifférent",
    "Aime l'ordre",
    "Change souvent d'humeur",
    "Comprends vite",
    "N'aime pas attirer l'attention",
    "Prends du temps pour les autres",
    "Me dérobe à mes obligations",
    "Ai de fréquentes sautes d'humeur",
    "Emploie des mots compliqués",
    "Ne déteste pas être au centre de l'attention",
    "Ressens les émotions des autres",
    "Suis un planning",
    "M'irrite facilement",
    "Prends le temps de réfléchir",
    "Suis silencieux avec les inconnus",
    "Mets les gens à l'aise",
    "Suis très rigoureux dans mon travail",
    "Me sens souvent abattu",
    "Suis plein d'idées",
  ],
  pt: [
    "Sou a alma da festa",
    "Me importo pouco com os outros",
    "Estou sempre preparado",
    "Fico estressado com facilidade",
    "Tenho vocabulário rico",
    "Não falo muito",
    "Me interesso pelas pessoas",
    "Deixo minhas coisas espalhadas",
    "Fico relaxado na maior parte do tempo",
    "Tenho dificuldade com ideias abstratas",
    "Me sinto à vontade perto das pessoas",
    "Ofendo os outros",
    "Presto atenção aos detalhes",
    "Me preocupo com as coisas",
    "Tenho imaginação viva",
    "Fico em segundo plano",
    "Me solidarizo com os sentimentos dos outros",
    "Faço bagunça",
    "Raramente me sinto para baixo",
    "Não me interesso por ideias abstratas",
    "Puxo conversa",
    "Não me interesso de verdade pelos outros",
    "Faço as tarefas na hora",
    "Me chateio facilmente",
    "Tenho ideias excelentes",
    "Tenho pouco a dizer",
    "Tenho bom coração",
    "Esqueço de devolver as coisas ao lugar",
    "Não me abalo com facilidade",
    "Não tenho boa imaginação",
    "Converso com muita gente diferente nas festas",
    "Os outros me deixam bastante indiferente",
    "Gosto de ordem",
    "Meu humor muda muito",
    "Entendo as coisas rápido",
    "Não gosto de chamar atenção",
    "Reservo tempo para os outros",
    "Fujo das minhas obrigações",
    "Tenho mudanças de humor frequentes",
    "Uso palavras difíceis",
    "Não me incomodo em ser o centro das atenções",
    "Sinto as emoções dos outros",
    "Sigo uma agenda",
    "Fico irritado com facilidade",
    "Passo tempo refletindo",
    "Fico quieto perto de estranhos",
    "Deixo as pessoas à vontade",
    "Sou rigoroso no meu trabalho",
    "Me sinto para baixo com frequência",
    "Estou cheio de ideias",
  ],
  it: [
    "Sono l'anima della festa",
    "Mi importa poco degli altri",
    "Sono sempre preparato",
    "Mi stresso facilmente",
    "Ho un vocabolario ricco",
    "Non parlo molto",
    "Mi interesso alle persone",
    "Lascio le mie cose in giro",
    "Sono rilassato quasi sempre",
    "Faccio fatica a capire le idee astratte",
    "Mi sento a mio agio con la gente",
    "Insulto gli altri",
    "Faccio attenzione ai dettagli",
    "Mi preoccupo delle cose",
    "Ho una fantasia vivida",
    "Resto in secondo piano",
    "Comprendo i sentimenti degli altri",
    "Metto disordine ovunque",
    "Raramente mi sento giù",
    "Non mi interessano le idee astratte",
    "Inizio conversazioni",
    "Non mi interesso davvero agli altri",
    "Sbrigo subito le faccende",
    "Mi altero facilmente",
    "Ho ottime idee",
    "Ho poco da dire",
    "Ho un cuore tenero",
    "Dimentico spesso di rimettere le cose al loro posto",
    "Non mi lascio turbare facilmente",
    "Non ho molta immaginazione",
    "Parlo con molte persone diverse alle feste",
    "Gli altri mi lasciano piuttosto indifferente",
    "Amo l'ordine",
    "Il mio umore cambia spesso",
    "Capisco le cose in fretta",
    "Non amo attirare l'attenzione",
    "Trovo tempo per gli altri",
    "Mi sottraggo ai miei doveri",
    "Ho frequenti sbalzi d'umore",
    "Uso parole difficili",
    "Non mi dispiace essere al centro dell'attenzione",
    "Sento le emozioni degli altri",
    "Seguo un programma",
    "Mi irrito facilmente",
    "Dedico tempo a riflettere",
    "Sono silenzioso con gli sconosciuti",
    "Metto le persone a proprio agio",
    "Sono molto preciso nel lavoro",
    "Mi sento spesso giù",
    "Sono pieno di idee",
  ],
  nl: [
    "Ben het middelpunt van het feest",
    "Geef weinig om anderen",
    "Ben altijd voorbereid",
    "Raak snel gestrest",
    "Heb een rijke woordenschat",
    "Praat niet veel",
    "Ben geïnteresseerd in mensen",
    "Laat mijn spullen slingeren",
    "Ben meestal ontspannen",
    "Heb moeite met abstracte ideeën",
    "Voel me op mijn gemak bij mensen",
    "Beledig anderen",
    "Let op details",
    "Maak me zorgen over dingen",
    "Heb een levendige fantasie",
    "Blijf op de achtergrond",
    "Leef mee met de gevoelens van anderen",
    "Maak er een rommel van",
    "Voel me zelden somber",
    "Ben niet geïnteresseerd in abstracte ideeën",
    "Begin gesprekken",
    "Ben niet echt geïnteresseerd in anderen",
    "Doe klusjes meteen",
    "Raak snel van streek",
    "Heb uitstekende ideeën",
    "Heb weinig te zeggen",
    "Heb een zacht hart",
    "Vergeet vaak dingen terug te leggen",
    "Laat me niet snel van mijn stuk brengen",
    "Heb geen goede verbeelding",
    "Praat op feesten met veel verschillende mensen",
    "Anderen laten me tamelijk koud",
    "Houd van orde",
    "Wissel vaak van stemming",
    "Begrijp dingen snel",
    "Trek niet graag de aandacht",
    "Maak tijd voor anderen",
    "Ontloop mijn plichten",
    "Heb vaak stemmingswisselingen",
    "Gebruik moeilijke woorden",
    "Vind het niet erg in het middelpunt te staan",
    "Voel de emoties van anderen",
    "Volg een planning",
    "Raak snel geïrriteerd",
    "Neem tijd om na te denken",
    "Ben stil bij vreemden",
    "Stel mensen op hun gemak",
    "Ben nauwgezet in mijn werk",
    "Voel me vaak somber",
    "Zit vol ideeën",
  ],
  pl: [
    "Jestem duszą towarzystwa",
    "Mało obchodzą mnie inni",
    "Zawsze jestem przygotowany",
    "Łatwo się stresuję",
    "Mam bogate słownictwo",
    "Niewiele mówię",
    "Interesuję się ludźmi",
    "Zostawiam swoje rzeczy byle gdzie",
    "Przez większość czasu jestem rozluźniony",
    "Mam trudność ze zrozumieniem abstrakcyjnych idei",
    "Czuję się swobodnie wśród ludzi",
    "Obrażam innych",
    "Zwracam uwagę na szczegóły",
    "Martwię się o różne rzeczy",
    "Mam żywą wyobraźnię",
    "Trzymam się w cieniu",
    "Współodczuwam z innymi",
    "Robię bałagan",
    "Rzadko czuję przygnębienie",
    "Nie interesują mnie abstrakcyjne idee",
    "Zaczynam rozmowy",
    "Inni niespecjalnie mnie interesują",
    "Załatwiam obowiązki od razu",
    "Łatwo się denerwuję",
    "Mam znakomite pomysły",
    "Mam niewiele do powiedzenia",
    "Mam miękkie serce",
    "Często zapominam odłożyć rzeczy na miejsce",
    "Niełatwo wytrącić mnie z równowagi",
    "Nie mam dobrej wyobraźni",
    "Na imprezach rozmawiam z wieloma różnymi osobami",
    "Inni ludzie są mi raczej obojętni",
    "Lubię porządek",
    "Często zmienia mi się nastrój",
    "Szybko rozumiem",
    "Nie lubię zwracać na siebie uwagi",
    "Znajduję czas dla innych",
    "Uchylam się od obowiązków",
    "Miewam częste wahania nastroju",
    "Używam trudnych słów",
    "Nie przeszkadza mi bycie w centrum uwagi",
    "Wyczuwam emocje innych",
    "Trzymam się planu",
    "Łatwo mnie zirytować",
    "Poświęcam czas na przemyślenia",
    "Jestem cichy wśród obcych",
    "Sprawiam, że ludzie czują się swobodnie",
    "Jestem skrupulatny w pracy",
    "Często czuję przygnębienie",
    "Jestem pełen pomysłów",
  ],
  ru: [
    "Я душа компании",
    "Мало забочусь о других",
    "Я всегда подготовлен",
    "Легко впадаю в стресс",
    "У меня богатый словарный запас",
    "Я мало говорю",
    "Мне интересны люди",
    "Я разбрасываю свои вещи",
    "Почти всё время я расслаблен",
    "Мне трудно понимать отвлечённые идеи",
    "Мне легко среди людей",
    "Я оскорбляю других",
    "Я внимателен к деталям",
    "Я тревожусь о разном",
    "У меня живое воображение",
    "Я держусь в тени",
    "Я сопереживаю чувствам других",
    "Я устраиваю беспорядок",
    "Я редко грущу",
    "Мне неинтересны отвлечённые идеи",
    "Я первым завожу разговор",
    "Другие меня не очень интересуют",
    "Я делаю дела сразу",
    "Меня легко расстроить",
    "У меня прекрасные идеи",
    "Мне почти нечего сказать",
    "У меня мягкое сердце",
    "Я часто забываю класть вещи на место",
    "Меня трудно вывести из равновесия",
    "У меня нет хорошего воображения",
    "На вечеринках я говорю со многими разными людьми",
    "Другие люди мне довольно безразличны",
    "Я люблю порядок",
    "У меня часто меняется настроение",
    "Я быстро схватываю",
    "Я не люблю привлекать к себе внимание",
    "Я нахожу время для других",
    "Я уклоняюсь от обязанностей",
    "У меня частые перепады настроения",
    "Я употребляю сложные слова",
    "Я не против быть в центре внимания",
    "Я чувствую эмоции других",
    "Я придерживаюсь расписания",
    "Я легко раздражаюсь",
    "Я много размышляю",
    "С незнакомыми я молчалив",
    "Рядом со мной людям спокойно",
    "Я очень требователен к своей работе",
    "Мне часто бывает грустно",
    "Я полон идей",
  ],
  tr: [
    "Partinin ruhuyum",
    "Başkalarını pek umursamam",
    "Her zaman hazırlıklıyım",
    "Kolayca strese girerim",
    "Zengin bir kelime dağarcığım var",
    "Fazla konuşmam",
    "İnsanlarla ilgilenirim",
    "Eşyalarımı ortalıkta bırakırım",
    "Çoğu zaman rahatım",
    "Soyut fikirleri anlamakta zorlanırım",
    "İnsanların yanında rahat hissederim",
    "İnsanlara hakaret ederim",
    "Ayrıntılara dikkat ederim",
    "Bir şeyler için endişelenirim",
    "Canlı bir hayal gücüm var",
    "Geri planda kalırım",
    "Başkalarının duygularını paylaşırım",
    "Ortalığı dağıtırım",
    "Nadiren keyifsiz olurum",
    "Soyut fikirlerle ilgilenmem",
    "Sohbet başlatırım",
    "Başkalarıyla pek ilgilenmem",
    "İşleri hemen hallederim",
    "Kolay üzülürüm",
    "Mükemmel fikirlerim olur",
    "Söyleyecek fazla şeyim olmaz",
    "Yufka yürekliyim",
    "Eşyaları yerine koymayı sık sık unuturum",
    "Kolay kolay huzurum kaçmaz",
    "İyi bir hayal gücüm yok",
    "Partilerde birçok farklı insanla konuşurum",
    "Başkaları beni pek ilgilendirmez",
    "Düzeni severim",
    "Ruh halim çok değişir",
    "Bir şeyleri çabuk kavrarım",
    "Dikkat çekmekten hoşlanmam",
    "Başkalarına vakit ayırırım",
    "Sorumluluklarımdan kaçarım",
    "Sık sık ruh hali dalgalanmaları yaşarım",
    "Zor kelimeler kullanırım",
    "İlgi odağı olmak beni rahatsız etmez",
    "Başkalarının duygularını hissederim",
    "Bir programa uyarım",
    "Çabuk sinirlenirim",
    "Düşünmeye vakit ayırırım",
    "Yabancıların yanında sessizimdir",
    "İnsanları rahat ettiririm",
    "İşimde titizimdir",
    "Sık sık keyifsiz hissederim",
    "Fikir doluyum",
  ],
  ro: [
    "Sunt sufletul petrecerii",
    "Îmi pasă puțin de ceilalți",
    "Sunt mereu pregătit",
    "Mă stresez ușor",
    "Am un vocabular bogat",
    "Nu vorbesc mult",
    "Mă interesează oamenii",
    "Îmi las lucrurile împrăștiate",
    "Sunt relaxat în cea mai mare parte a timpului",
    "Îmi vine greu să înțeleg ideile abstracte",
    "Mă simt bine printre oameni",
    "Îi jignesc pe ceilalți",
    "Sunt atent la detalii",
    "Îmi fac griji pentru lucruri",
    "Am o imaginație vie",
    "Rămân în plan secund",
    "Empatizez cu sentimentele altora",
    "Fac dezordine",
    "Rareori mă simt abătut",
    "Nu mă interesează ideile abstracte",
    "Încep conversații",
    "Nu mă interesează cu adevărat ceilalți",
    "Îmi fac treburile imediat",
    "Mă supăr ușor",
    "Am idei excelente",
    "Am puține de spus",
    "Am o inimă bună",
    "Uit adesea să pun lucrurile la loc",
    "Nu mă tulbur ușor",
    "Nu am o imaginație bună",
    "Vorbesc cu mulți oameni diferiți la petreceri",
    "Ceilalți mă lasă mai degrabă indiferent",
    "Îmi place ordinea",
    "Îmi schimb des starea de spirit",
    "Înțeleg repede lucrurile",
    "Nu-mi place să atrag atenția",
    "Îmi fac timp pentru ceilalți",
    "Mă eschivez de la obligații",
    "Am schimbări frecvente de dispoziție",
    "Folosesc cuvinte dificile",
    "Nu mă deranjează să fiu în centrul atenției",
    "Simt emoțiile celorlalți",
    "Respect un program",
    "Mă irit ușor",
    "Petrec timp reflectând",
    "Sunt tăcut printre străini",
    "Îi fac pe oameni să se simtă în largul lor",
    "Sunt riguros în munca mea",
    "Mă simt adesea abătut",
    "Sunt plin de idei",
  ],
  sv: [
    "Är festens medelpunkt",
    "Bryr mig föga om andra",
    "Är alltid förberedd",
    "Blir lätt stressad",
    "Har ett rikt ordförråd",
    "Pratar inte mycket",
    "Är intresserad av människor",
    "Lämnar mina saker överallt",
    "Är avslappnad för det mesta",
    "Har svårt att förstå abstrakta idéer",
    "Trivs bland människor",
    "Förolämpar andra",
    "Är uppmärksam på detaljer",
    "Oroar mig för saker",
    "Har livlig fantasi",
    "Håller mig i bakgrunden",
    "Känner med andras känslor",
    "Ställer till oreda",
    "Känner mig sällan nedstämd",
    "Är inte intresserad av abstrakta idéer",
    "Inleder samtal",
    "Är inte särskilt intresserad av andra",
    "Gör sysslorna direkt",
    "Blir lätt upprörd",
    "Har utmärkta idéer",
    "Har lite att säga",
    "Har ett mjukt hjärta",
    "Glömmer ofta att lägga tillbaka saker",
    "Låter mig inte lätt störas",
    "Har inte god fantasi",
    "Pratar med många olika på fester",
    "Andra lämnar mig ganska oberörd",
    "Gillar ordning",
    "Skiftar humör ofta",
    "Förstår saker snabbt",
    "Gillar inte att dra uppmärksamhet till mig",
    "Tar mig tid för andra",
    "Smiter från mina plikter",
    "Har täta humörsvängningar",
    "Använder svåra ord",
    "Har inget emot att stå i centrum",
    "Känner andras känslor",
    "Följer ett schema",
    "Blir lätt irriterad",
    "Ägnar tid åt att reflektera",
    "Är tyst bland främlingar",
    "Får folk att slappna av",
    "Är noggrann i mitt arbete",
    "Känner mig ofta nedstämd",
    "Är full av idéer",
  ],
  da: [
    "Er festens midtpunkt",
    "Bekymrer mig lidt om andre",
    "Er altid forberedt",
    "Bliver let stresset",
    "Har et rigt ordforråd",
    "Taler ikke meget",
    "Er interesseret i mennesker",
    "Lader mine ting flyde",
    "Er afslappet det meste af tiden",
    "Har svært ved at forstå abstrakte idéer",
    "Har det godt blandt mennesker",
    "Fornærmer andre",
    "Er opmærksom på detaljer",
    "Bekymrer mig om ting",
    "Har en livlig fantasi",
    "Holder mig i baggrunden",
    "Føler med andres følelser",
    "Laver rod",
    "Føler mig sjældent nedtrykt",
    "Er ikke interesseret i abstrakte idéer",
    "Indleder samtaler",
    "Er ikke rigtig interesseret i andre",
    "Klarer opgaverne med det samme",
    "Bliver let ked af det",
    "Har fremragende idéer",
    "Har ikke meget at sige",
    "Har et blødt hjerte",
    "Glemmer ofte at lægge ting på plads",
    "Lader mig ikke let forstyrre",
    "Har ikke en god fantasi",
    "Taler med mange forskellige til fester",
    "Andre lader mig ret uberørt",
    "Kan lide orden",
    "Skifter humør ofte",
    "Forstår ting hurtigt",
    "Bryder mig ikke om at tiltrække opmærksomhed",
    "Tager mig tid til andre",
    "Smyger mig uden om mine pligter",
    "Har hyppige humørsvingninger",
    "Bruger svære ord",
    "Har ikke noget imod at være i centrum",
    "Mærker andres følelser",
    "Følger en plan",
    "Bliver let irriteret",
    "Bruger tid på at reflektere",
    "Er stille blandt fremmede",
    "Får folk til at slappe af",
    "Er omhyggelig i mit arbejde",
    "Føler mig ofte nedtrykt",
    "Er fuld af idéer",
  ],
  no: [
    "Er midtpunktet i selskapet",
    "Bryr meg lite om andre",
    "Er alltid forberedt",
    "Blir lett stresset",
    "Har et rikt ordforråd",
    "Snakker ikke mye",
    "Er interessert i mennesker",
    "Lar tingene mine ligge og slenge",
    "Er avslappet det meste av tiden",
    "Har vansker med å forstå abstrakte ideer",
    "Trives blant folk",
    "Fornærmer andre",
    "Er oppmerksom på detaljer",
    "Bekymrer meg for ting",
    "Har livlig fantasi",
    "Holder meg i bakgrunnen",
    "Føler med andres følelser",
    "Roter det til",
    "Føler meg sjelden nedfor",
    "Er ikke interessert i abstrakte ideer",
    "Tar initiativ til samtaler",
    "Er ikke særlig interessert i andre",
    "Gjør oppgavene med en gang",
    "Blir lett opprørt",
    "Har utmerkede ideer",
    "Har lite å si",
    "Har et mykt hjerte",
    "Glemmer ofte å legge ting tilbake",
    "Lar meg ikke lett forstyrre",
    "Har ikke god fantasi",
    "Snakker med mange forskjellige i selskaper",
    "Andre lar meg ganske uberørt",
    "Liker orden",
    "Skifter humør ofte",
    "Forstår ting raskt",
    "Liker ikke å trekke oppmerksomhet til meg",
    "Tar meg tid til andre",
    "Sniker meg unna pliktene mine",
    "Har hyppige humørsvingninger",
    "Bruker vanskelige ord",
    "Har ikke noe imot å være i sentrum",
    "Kjenner andres følelser",
    "Følger en plan",
    "Blir lett irritert",
    "Bruker tid på å reflektere",
    "Er stille blant fremmede",
    "Får folk til å slappe av",
    "Er nøye i arbeidet mitt",
    "Føler meg ofte nedfor",
    "Er full av ideer",
  ],
  fi: [
    "Olen juhlien keskipiste",
    "Välitän muista vähän",
    "Olen aina valmistautunut",
    "Stressaannun helposti",
    "Minulla on laaja sanavarasto",
    "En puhu paljon",
    "Olen kiinnostunut ihmisistä",
    "Jätän tavarani lojumaan",
    "Olen useimmiten rentoutunut",
    "Minun on vaikea ymmärtää abstrakteja ajatuksia",
    "Viihdyn ihmisten seurassa",
    "Loukkaan muita",
    "Kiinnitän huomiota yksityiskohtiin",
    "Murehdin asioita",
    "Minulla on vilkas mielikuvitus",
    "Pysyttelen taustalla",
    "Eläydyn toisten tunteisiin",
    "Saan aikaan sotkua",
    "Tunnen itseni harvoin alakuloiseksi",
    "En ole kiinnostunut abstrakteista ajatuksista",
    "Aloitan keskusteluja",
    "En ole oikeastaan kiinnostunut muista",
    "Hoidan tehtävät heti",
    "Suutun helposti",
    "Minulla on erinomaisia ideoita",
    "Minulla on vähän sanottavaa",
    "Minulla on lämmin sydän",
    "Unohdan usein palauttaa tavarat paikoilleen",
    "En hermostu helposti",
    "Minulla ei ole hyvää mielikuvitusta",
    "Juttelen juhlissa monien eri ihmisten kanssa",
    "Muut jättävät minut aika kylmäksi",
    "Pidän järjestyksestä",
    "Mielialani vaihtelee usein",
    "Ymmärrän asiat nopeasti",
    "En pidä huomion herättämisestä",
    "Varaan aikaa muille",
    "Laistan velvollisuuksistani",
    "Minulla on tiheitä mielialan vaihteluita",
    "Käytän vaikeita sanoja",
    "En pahastu ollessani huomion keskipisteenä",
    "Aistin toisten tunteet",
    "Noudatan aikataulua",
    "Ärsyynnyn helposti",
    "Käytän aikaa pohtimiseen",
    "Olen hiljainen vieraiden seurassa",
    "Saan ihmiset tuntemaan olonsa mukavaksi",
    "Olen tarkka työssäni",
    "Tunnen itseni usein alakuloiseksi",
    "Olen täynnä ideoita",
  ],
  id: [
    "Menjadi pusat perhatian di pesta",
    "Kurang peduli pada orang lain",
    "Selalu siap",
    "Mudah stres",
    "Memiliki kosakata yang kaya",
    "Tidak banyak bicara",
    "Tertarik pada orang lain",
    "Membiarkan barang berserakan",
    "Santai hampir sepanjang waktu",
    "Sulit memahami gagasan abstrak",
    "Nyaman berada di antara orang",
    "Menghina orang lain",
    "Memperhatikan detail",
    "Mengkhawatirkan banyak hal",
    "Memiliki imajinasi yang hidup",
    "Memilih berada di belakang layar",
    "Ikut merasakan perasaan orang lain",
    "Membuat berantakan",
    "Jarang merasa murung",
    "Tidak tertarik pada gagasan abstrak",
    "Memulai percakapan",
    "Tidak begitu tertarik pada orang lain",
    "Mengerjakan tugas segera",
    "Mudah kesal",
    "Punya gagasan yang sangat baik",
    "Tidak banyak yang ingin dikatakan",
    "Berhati lembut",
    "Sering lupa mengembalikan barang ke tempatnya",
    "Tidak mudah terganggu",
    "Tidak punya imajinasi yang baik",
    "Berbicara dengan banyak orang berbeda di pesta",
    "Cukup acuh terhadap orang lain",
    "Menyukai keteraturan",
    "Suasana hati sering berubah",
    "Cepat memahami sesuatu",
    "Tidak suka menarik perhatian",
    "Meluangkan waktu untuk orang lain",
    "Menghindari kewajiban",
    "Sering mengalami perubahan suasana hati",
    "Menggunakan kata-kata yang sulit",
    "Tidak keberatan menjadi pusat perhatian",
    "Merasakan emosi orang lain",
    "Mengikuti jadwal",
    "Mudah tersinggung",
    "Meluangkan waktu untuk merenung",
    "Pendiam di antara orang asing",
    "Membuat orang merasa nyaman",
    "Teliti dalam pekerjaan",
    "Sering merasa murung",
    "Penuh dengan ide",
  ],
  uk: [
    "Я легко починаю розмову з незнайомими людьми.",
    "Я завжди виконую роботу вчасно.",
    "Я часто хвилююся через дрібниці.",
    "Мене цікавлять абстрактні ідеї.",
    "Я співчуваю тим, кому важко.",
    "Я тримаю свої речі в порядку.",
    "Я почуваюся спокійно в більшості ситуацій.",
    "Я маю багату уяву.",
    "Мені подобається бути в центрі уваги.",
    "Я рідко думаю про почуття інших.",
    "Я дотримуюся визначеного графіка.",
    "Я легко дратуюся.",
    "Я люблю пробувати щось нове й незвичне.",
    "Я охоче допомагаю іншим.",
    "Я мовчазний серед незнайомців.",
    "Я приділяю увагу деталям.",
    "Я часто відчуваю смуток без явної причини.",
    "Мені подобаються філософські розмови.",
    "Я поважаю чужу точку зору.",
    "Я заряджаюся енергією у великих компаніях.",
    "Я часто залишаю справи незавершеними.",
    "Я легко зберігаю спокій під тиском.",
    "Я захоплююся мистецтвом і музикою.",
    "Я схильний критикувати інших.",
    "Я говорю багато.",
    "Я ретельно готуюся до важливих справ.",
    "Я легко засмучуюся.",
    "Я люблю розмірковувати над складними питаннями.",
    "Я довіряю людям.",
    "Мені комфортніше наодинці, ніж у гурті.",
    "Я тримаю обіцянки.",
    "Настрій у мене часто змінюється.",
    "Я цікавлюся іншими культурами.",
    "Я намагаюся нікого не образити.",
    "Я беру на себе ініціативу в групі.",
    "Я відкладаю справи на потім.",
    "Я хвилююся перед важливими подіями.",
    "Я помічаю красу в буденних речах.",
    "Я готовий поступитися заради злагоди.",
    "Я почуваюся невимушено в новій компанії.",
    "Я працюю наполегливо, доки не завершу.",
    "Я рідко почуваюся пригніченим.",
    "Мені подобається вигадувати нові способи щось зробити.",
    "Я з розумінням ставлюся до чужих помилок.",
    "Я уникаю великих зібрань.",
    "Я планую наперед.",
    "Я легко переживаю невдачі.",
    "Мене приваблюють нові враження та подорожі.",
    "Я щиро радію чужим успіхам.",
    "Я почуваюся впевнено, виступаючи перед людьми.",
  ],
  bg: [
    "Лесно започвам разговор с непознати.",
    "Винаги завършвам работата си навреме.",
    "Често се тревожа за дреболии.",
    "Интересуват ме абстрактни идеи.",
    "Съчувствам на хората в затруднение.",
    "Държа нещата си подредени.",
    "Чувствам се спокоен в повечето ситуации.",
    "Имам богато въображение.",
    "Обичам да съм в центъра на вниманието.",
    "Рядко мисля за чувствата на другите.",
    "Придържам се към определен график.",
    "Дразня се лесно.",
    "Обичам да опитвам нови и необичайни неща.",
    "Помагам охотно на другите.",
    "Мълчалив съм сред непознати.",
    "Обръщам внимание на детайлите.",
    "Често се чувствам тъжен без явна причина.",
    "Харесвам философските разговори.",
    "Уважавам чуждата гледна точка.",
    "Зареждам се с енергия в големи компании.",
    "Често оставям нещата недовършени.",
    "Запазвам спокойствие под напрежение.",
    "Възхищавам се на изкуството и музиката.",
    "Склонен съм да критикувам другите.",
    "Говоря много.",
    "Подготвям се старателно за важни неща.",
    "Разстройвам се лесно.",
    "Обичам да размишлявам над сложни въпроси.",
    "Доверявам се на хората.",
    "По-удобно ми е сам, отколкото в група.",
    "Спазвам обещанията си.",
    "Настроението ми се променя често.",
    "Интересувам се от други култури.",
    "Старая се да не обидя никого.",
    "Поемам инициативата в група.",
    "Отлагам нещата за по-късно.",
    "Тревожа се преди важни събития.",
    "Забелязвам красотата в делничните неща.",
    "Готов съм да отстъпя заради разбирателството.",
    "Чувствам се непринудено в нова компания.",
    "Работя упорито, докато не завърша.",
    "Рядко се чувствам потиснат.",
    "Обичам да измислям нови начини да свърша нещо.",
    "Отнасям се с разбиране към чуждите грешки.",
    "Избягвам големи събирания.",
    "Планирам предварително.",
    "Преживявам трудно неуспехите.",
    "Привличат ме нови преживявания и пътувания.",
    "Радвам се искрено на чуждите успехи.",
    "Чувствам се уверен, когато говоря пред хора.",
  ],
  sr: [
    "Лако започињем разговор с непознатима.",
    "Увек завршавам посао на време.",
    "Често бринем због ситница.",
    "Занимају ме апстрактне идеје.",
    "Саосећам с онима којима је тешко.",
    "Држим своје ствари уредно.",
    "Осећам се смирено у већини ситуација.",
    "Имам богату машту.",
    "Волим да будем у центру пажње.",
    "Ретко размишљам о туђим осећањима.",
    "Држим се одређеног распореда.",
    "Лако се изнервирам.",
    "Волим да пробам нове и необичне ствари.",
    "Радо помажем другима.",
    "Ћутљив сам међу непознатима.",
    "Обраћам пажњу на детаље.",
    "Често се осећам тужно без јасног разлога.",
    "Волим филозофске разговоре.",
    "Поштујем туђе становиште.",
    "Пуним се енергијом у великом друштву.",
    "Често остављам ствари недовршене.",
    "Остајем смирен под притиском.",
    "Дивим се уметности и музици.",
    "Склон сам да критикујем друге.",
    "Много причам.",
    "Темељно се припремам за важне ствари.",
    "Лако се узнемирим.",
    "Волим да размишљам о сложеним питањима.",
    "Верујем људима.",
    "Пријатније ми је сам него у групи.",
    "Држим обећања.",
    "Расположење ми се често мења.",
    "Занимају ме друге културе.",
    "Трудим се да никога не увредим.",
    "Преузимам иницијативу у групи.",
    "Одлажем ствари за касније.",
    "Бринем пред важне догађаје.",
    "Примећујем лепоту у свакодневним стварима.",
    "Спреман сам да попустим ради слоге.",
    "Осећам се опуштено у новом друштву.",
    "Радим упорно док не завршим.",
    "Ретко се осећам потиштено.",
    "Волим да смишљам нове начине да нешто урадим.",
    "С разумевањем гледам на туђе грешке.",
    "Избегавам велика окупљања.",
    "Планирам унапред.",
    "Тешко подносим неуспехе.",
    "Привлаче ме нова искуства и путовања.",
    "Искрено се радујем туђим успесима.",
    "Осећам се сигурно кад говорим пред људима.",
  ],
  mk: [
    "Лесно започнувам разговор со непознати.",
    "Секогаш ја завршувам работата навреме.",
    "Често се грижам за ситници.",
    "Ме интересираат апстрактни идеи.",
    "Сочувствувам со оние на кои им е тешко.",
    "Ги држам своите работи уредни.",
    "Се чувствувам смирено во повеќето ситуации.",
    "Имам богата фантазија.",
    "Сакам да бидам во центарот на вниманието.",
    "Ретко размислувам за туѓите чувства.",
    "Се придржувам до определен распоред.",
    "Лесно се изнервирам.",
    "Сакам да пробам нови и необични работи.",
    "Радо им помагам на другите.",
    "Молчалив сум меѓу непознати.",
    "Обрнувам внимание на деталите.",
    "Често се чувствувам тажно без јасна причина.",
    "Ги сакам филозофските разговори.",
    "Го почитувам туѓото гледиште.",
    "Се полнам со енергија во големо друштво.",
    "Често оставам работи недовршени.",
    "Останувам смирен под притисок.",
    "Се восхитувам на уметноста и музиката.",
    "Склон сум да ги критикувам другите.",
    "Зборувам многу.",
    "Темелно се подготвувам за важни работи.",
    "Лесно се вознемирувам.",
    "Сакам да размислувам за сложени прашања.",
    "Им верувам на луѓето.",
    "Поудобно ми е сам отколку во група.",
    "Ги држам ветувањата.",
    "Расположението често ми се менува.",
    "Ме интересираат други култури.",
    "Се трудам никого да не навредам.",
    "Ја преземам иницијативата во група.",
    "Ги одложувам работите за подоцна.",
    "Се грижам пред важни настани.",
    "Ја забележувам убавината во секојдневните работи.",
    "Спремен сум да попуштам заради слога.",
    "Се чувствувам опуштено во ново друштво.",
    "Работам упорно додека не завршам.",
    "Ретко се чувствувам потиштено.",
    "Сакам да смислувам нови начини нешто да сработам.",
    "Со разбирање гледам на туѓите грешки.",
    "Избегнувам големи собири.",
    "Планирам однапред.",
    "Тешко ги поднесувам неуспесите.",
    "Ме привлекуваат нови искуства и патувања.",
    "Искрено се радувам на туѓите успеси.",
    "Се чувствувам сигурно кога зборувам пред луѓе.",
  ],
  el: [
    "Ξεκινάω εύκολα κουβέντα με αγνώστους.",
    "Τελειώνω πάντα τη δουλειά μου στην ώρα της.",
    "Ανησυχώ συχνά για μικροπράγματα.",
    "Με ενδιαφέρουν οι αφηρημένες ιδέες.",
    "Συμπονώ όσους δυσκολεύονται.",
    "Κρατάω τα πράγματά μου τακτοποιημένα.",
    "Νιώθω ήρεμος στις περισσότερες καταστάσεις.",
    "Έχω πλούσια φαντασία.",
    "Μου αρέσει να είμαι στο επίκεντρο της προσοχής.",
    "Σπάνια σκέφτομαι τα συναισθήματα των άλλων.",
    "Ακολουθώ συγκεκριμένο πρόγραμμα.",
    "Εκνευρίζομαι εύκολα.",
    "Μου αρέσει να δοκιμάζω καινούργια και ασυνήθιστα πράγματα.",
    "Βοηθάω πρόθυμα τους άλλους.",
    "Είμαι σιωπηλός ανάμεσα σε αγνώστους.",
    "Δίνω προσοχή στις λεπτομέρειες.",
    "Νιώθω συχνά λύπη χωρίς εμφανή λόγο.",
    "Μου αρέσουν οι φιλοσοφικές συζητήσεις.",
    "Σέβομαι την άποψη των άλλων.",
    "Παίρνω ενέργεια από τις μεγάλες παρέες.",
    "Αφήνω συχνά πράγματα μισοτελειωμένα.",
    "Παραμένω ήρεμος υπό πίεση.",
    "Θαυμάζω την τέχνη και τη μουσική.",
    "Έχω τάση να κρίνω τους άλλους.",
    "Μιλάω πολύ.",
    "Προετοιμάζομαι σχολαστικά για τα σημαντικά.",
    "Αναστατώνομαι εύκολα.",
    "Μου αρέσει να στοχάζομαι πάνω σε σύνθετα ζητήματα.",
    "Εμπιστεύομαι τους ανθρώπους.",
    "Νιώθω πιο άνετα μόνος παρά σε ομάδα.",
    "Κρατάω τις υποσχέσεις μου.",
    "Η διάθεσή μου αλλάζει συχνά.",
    "Με ενδιαφέρουν άλλοι πολιτισμοί.",
    "Προσπαθώ να μην προσβάλλω κανέναν.",
    "Αναλαμβάνω πρωτοβουλία σε ομάδα.",
    "Αναβάλλω τα πράγματα για αργότερα.",
    "Αγχώνομαι πριν από σημαντικά γεγονότα.",
    "Παρατηρώ την ομορφιά στα καθημερινά πράγματα.",
    "Είμαι έτοιμος να υποχωρήσω για χάρη της αρμονίας.",
    "Νιώθω άνετα σε καινούργια παρέα.",
    "Δουλεύω επίμονα μέχρι να τελειώσω.",
    "Σπάνια νιώθω καταβεβλημένος.",
    "Μου αρέσει να επινοώ νέους τρόπους να κάνω κάτι.",
    "Βλέπω με κατανόηση τα λάθη των άλλων.",
    "Αποφεύγω τις μεγάλες συγκεντρώσεις.",
    "Σχεδιάζω από πριν.",
    "Παίρνω δύσκολα τις αποτυχίες.",
    "Με ελκύουν νέες εμπειρίες και ταξίδια.",
    "Χαίρομαι ειλικρινά για τις επιτυχίες των άλλων.",
    "Νιώθω σίγουρος όταν μιλάω μπροστά σε κόσμο.",
  ],
  cs: [
    "Snadno začnu rozhovor s neznámými lidmi.",
    "Práci vždycky dokončím včas.",
    "Často se trápím kvůli maličkostem.",
    "Zajímají mě abstraktní myšlenky.",
    "Soucítím s těmi, kdo to mají těžké.",
    "Udržuji své věci v pořádku.",
    "Ve většině situací se cítím klidně.",
    "Mám bohatou představivost.",
    "Rád jsem středem pozornosti.",
    "Málokdy myslím na pocity druhých.",
    "Držím se určitého rozvrhu.",
    "Snadno se rozčílím.",
    "Rád zkouším nové a neobvyklé věci.",
    "Ochotně pomáhám druhým.",
    "Mezi neznámými lidmi mlčím.",
    "Věnuji pozornost detailům.",
    "Často se cítím smutně bez zjevného důvodu.",
    "Mám rád filozofické rozhovory.",
    "Respektuji cizí názor.",
    "Ve velké společnosti načerpám energii.",
    "Často nechávám věci nedodělané.",
    "Pod tlakem zůstávám klidný.",
    "Obdivuji umění a hudbu.",
    "Mám sklon kritizovat druhé.",
    "Hodně mluvím.",
    "Na důležité věci se pečlivě připravuji.",
    "Snadno se rozruším.",
    "Rád přemýšlím o složitých otázkách.",
    "Věřím lidem.",
    "Sám se cítím pohodlněji než ve skupině.",
    "Své sliby dodržuji.",
    "Nálada se mi často mění.",
    "Zajímají mě jiné kultury.",
    "Snažím se nikoho neurazit.",
    "Ve skupině přebírám iniciativu.",
    "Odkládám věci na později.",
    "Před důležitými událostmi mám obavy.",
    "Všímám si krásy v obyčejných věcech.",
    "Jsem ochotný ustoupit kvůli shodě.",
    "V nové společnosti se cítím uvolněně.",
    "Pracuji vytrvale, dokud nedokončím.",
    "Málokdy se cítím sklíčeně.",
    "Rád vymýšlím nové způsoby, jak něco udělat.",
    "Na cizí chyby hledím s pochopením.",
    "Vyhýbám se velkým shromážděním.",
    "Plánuji dopředu.",
    "Neúspěchy nesu těžce.",
    "Lákají mě nové zážitky a cestování.",
    "Z úspěchů druhých mám upřímnou radost.",
    "Cítím se jistě, když mluvím před lidmi.",
  ],
  hr: [
    "Lako započinjem razgovor s nepoznatima.",
    "Posao uvijek završim na vrijeme.",
    "Često se brinem zbog sitnica.",
    "Zanimaju me apstraktne ideje.",
    "Suosjećam s onima kojima je teško.",
    "Svoje stvari držim uredno.",
    "U većini se situacija osjećam smireno.",
    "Imam bogatu maštu.",
    "Volim biti u središtu pažnje.",
    "Rijetko razmišljam o tuđim osjećajima.",
    "Držim se određenog rasporeda.",
    "Lako se iznerviram.",
    "Volim isprobavati nove i neobične stvari.",
    "Rado pomažem drugima.",
    "Šutljiv sam među nepoznatima.",
    "Obraćam pažnju na detalje.",
    "Često se osjećam tužno bez jasnog razloga.",
    "Volim filozofske razgovore.",
    "Poštujem tuđe stajalište.",
    "U velikom se društvu punim energijom.",
    "Često ostavljam stvari nedovršene.",
    "Pod pritiskom ostajem smiren.",
    "Divim se umjetnosti i glazbi.",
    "Sklon sam kritizirati druge.",
    "Mnogo govorim.",
    "Za važne se stvari temeljito pripremam.",
    "Lako se uznemirim.",
    "Volim razmišljati o složenim pitanjima.",
    "Vjerujem ljudima.",
    "Ugodnije mi je samom nego u skupini.",
    "Držim obećanja.",
    "Raspoloženje mi se često mijenja.",
    "Zanimaju me druge kulture.",
    "Trudim se nikoga ne uvrijediti.",
    "U skupini preuzimam inicijativu.",
    "Odgađam stvari za poslije.",
    "Brinem se prije važnih događaja.",
    "Primjećujem ljepotu u svakodnevnim stvarima.",
    "Spreman sam popustiti radi sloge.",
    "U novom se društvu osjećam opušteno.",
    "Radim ustrajno dok ne završim.",
    "Rijetko se osjećam potišteno.",
    "Volim smišljati nove načine da nešto napravim.",
    "Na tuđe pogreške gledam s razumijevanjem.",
    "Izbjegavam velika okupljanja.",
    "Planiram unaprijed.",
    "Neuspjehe teško podnosim.",
    "Privlače me nova iskustva i putovanja.",
    "Iskreno se radujem tuđim uspjesima.",
    "Osjećam se sigurno kad govorim pred ljudima.",
  ],
  sk: [
    "Ľahko začnem rozhovor s neznámymi ľuďmi.",
    "Prácu vždy dokončím včas.",
    "Často sa trápim pre maličkosti.",
    "Zaujímajú ma abstraktné myšlienky.",
    "Súcítim s tými, ktorí to majú ťažké.",
    "Svoje veci udržiavam v poriadku.",
    "Vo väčšine situácií sa cítim pokojne.",
    "Mám bohatú predstavivosť.",
    "Rád som stredobodom pozornosti.",
    "Málokedy myslím na pocity druhých.",
    "Držím sa určitého rozvrhu.",
    "Ľahko sa nahnevám.",
    "Rád skúšam nové a nezvyčajné veci.",
    "Ochotne pomáham druhým.",
    "Medzi neznámymi ľuďmi mlčím.",
    "Venujem pozornosť detailom.",
    "Často sa cítim smutne bez zjavného dôvodu.",
    "Mám rád filozofické rozhovory.",
    "Rešpektujem cudzí názor.",
    "Vo veľkej spoločnosti načerpám energiu.",
    "Často nechávam veci nedokončené.",
    "Pod tlakom zostávam pokojný.",
    "Obdivujem umenie a hudbu.",
    "Mám sklon kritizovať druhých.",
    "Veľa hovorím.",
    "Na dôležité veci sa dôkladne pripravujem.",
    "Ľahko sa rozruším.",
    "Rád premýšľam o zložitých otázkach.",
    "Verím ľuďom.",
    "Sám sa cítim pohodlnejšie než v skupine.",
    "Svoje sľuby dodržiavam.",
    "Nálada sa mi často mení.",
    "Zaujímajú ma iné kultúry.",
    "Snažím sa nikoho neuraziť.",
    "V skupine preberám iniciatívu.",
    "Odkladám veci na neskôr.",
    "Pred dôležitými udalosťami mám obavy.",
    "Všímam si krásu v obyčajných veciach.",
    "Som ochotný ustúpiť kvôli zhode.",
    "V novej spoločnosti sa cítim uvoľnene.",
    "Pracujem vytrvalo, kým nedokončím.",
    "Málokedy sa cítim skľúčene.",
    "Rád vymýšľam nové spôsoby, ako niečo urobiť.",
    "Na cudzie chyby hľadím s pochopením.",
    "Vyhýbam sa veľkým zhromaždeniam.",
    "Plánujem dopredu.",
    "Neúspechy znášam ťažko.",
    "Lákajú ma nové zážitky a cestovanie.",
    "Z úspechov druhých mám úprimnú radosť.",
    "Cítim sa isto, keď hovorím pred ľuďmi.",
  ],
  sl: [
    "Z neznanci zlahka začnem pogovor.",
    "Delo vedno dokončam pravočasno.",
    "Pogosto me skrbijo malenkosti.",
    "Zanimajo me abstraktne zamisli.",
    "Sočustvujem s tistimi, ki jim je težko.",
    "Svoje stvari imam urejene.",
    "V večini položajev se počutim mirno.",
    "Imam bogato domišljijo.",
    "Rad sem v središču pozornosti.",
    "Redko pomislim na občutke drugih.",
    "Držim se določenega urnika.",
    "Hitro se razjezim.",
    "Rad preizkušam nove in nenavadne stvari.",
    "Drugim rad pomagam.",
    "Med neznanci sem tih.",
    "Pozoren sem na podrobnosti.",
    "Pogosto sem žalosten brez očitnega razloga.",
    "Rad imam filozofske pogovore.",
    "Spoštujem tuje stališče.",
    "V veliki družbi se napolnim z energijo.",
    "Pogosto puščam stvari nedokončane.",
    "Pod pritiskom ostanem miren.",
    "Občudujem umetnost in glasbo.",
    "Nagnjen sem k temu, da druge kritiziram.",
    "Veliko govorim.",
    "Na pomembne stvari se temeljito pripravim.",
    "Hitro se vznemirim.",
    "Rad razmišljam o zapletenih vprašanjih.",
    "Ljudem zaupam.",
    "Sam se počutim udobneje kot v skupini.",
    "Obljube držim.",
    "Razpoloženje se mi pogosto spreminja.",
    "Zanimajo me druge kulture.",
    "Trudim se nikogar ne užaliti.",
    "V skupini prevzamem pobudo.",
    "Stvari odlašam na pozneje.",
    "Pred pomembnimi dogodki sem v skrbeh.",
    "Opazim lepoto v vsakdanjih stvareh.",
    "Pripravljen sem popustiti zaradi sloge.",
    "V novi družbi se počutim sproščeno.",
    "Delam vztrajno, dokler ne dokončam.",
    "Redko sem potrt.",
    "Rad si izmišljam nove načine, kako kaj narediti.",
    "Na tuje napake gledam z razumevanjem.",
    "Izogibam se velikim srečanjem.",
    "Načrtujem vnaprej.",
    "Neuspehe težko prenašam.",
    "Privlačijo me nova doživetja in potovanja.",
    "Tujim uspehom se iskreno veselim.",
    "Počutim se samozavestno, ko govorim pred ljudmi.",
  ],
  hu: [
    "Könnyen kezdek beszélgetést ismeretlenekkel.",
    "A munkámat mindig időben befejezem.",
    "Gyakran aggódom apróságok miatt.",
    "Érdekelnek az elvont gondolatok.",
    "Együttérzek azokkal, akiknek nehéz.",
    "Rendben tartom a dolgaimat.",
    "A legtöbb helyzetben nyugodtnak érzem magam.",
    "Gazdag a képzeletem.",
    "Szeretek a figyelem középpontjában lenni.",
    "Ritkán gondolok mások érzéseire.",
    "Tartom magam egy meghatározott beosztáshoz.",
    "Könnyen felbosszantom magam.",
    "Szeretek új és szokatlan dolgokat kipróbálni.",
    "Szívesen segítek másokon.",
    "Ismeretlenek között hallgatag vagyok.",
    "Odafigyelek a részletekre.",
    "Gyakran vagyok szomorú látható ok nélkül.",
    "Szeretem a filozofikus beszélgetéseket.",
    "Tiszteletben tartom mások álláspontját.",
    "Nagy társaságban feltöltődöm.",
    "Gyakran hagyok dolgokat befejezetlenül.",
    "Nyomás alatt is nyugodt maradok.",
    "Csodálom a művészetet és a zenét.",
    "Hajlamos vagyok bírálni másokat.",
    "Sokat beszélek.",
    "A fontos dolgokra alaposan felkészülök.",
    "Könnyen felzaklatom magam.",
    "Szeretek összetett kérdéseken gondolkodni.",
    "Bízom az emberekben.",
    "Egyedül kényelmesebben érzem magam, mint csoportban.",
    "Megtartom az ígéreteimet.",
    "A hangulatom gyakran változik.",
    "Érdekelnek más kultúrák.",
    "Igyekszem senkit sem megbántani.",
    "Csoportban átveszem a kezdeményezést.",
    "Halogatom a dolgokat.",
    "Fontos események előtt izgulok.",
    "Észreveszem a szépséget a hétköznapi dolgokban.",
    "Hajlandó vagyok engedni az egyetértés kedvéért.",
    "Új társaságban fesztelenül érzem magam.",
    "Kitartóan dolgozom, amíg be nem fejezem.",
    "Ritkán érzem magam levertnek.",
    "Szeretek új módszereket kitalálni valamire.",
    "Megértéssel tekintek mások hibáira.",
    "Kerülöm a nagy összejöveteleket.",
    "Előre tervezek.",
    "Nehezen viselem a kudarcokat.",
    "Vonzanak az új élmények és az utazás.",
    "Őszintén örülök mások sikereinek.",
    "Magabiztosnak érzem magam, amikor emberek előtt beszélek.",
  ],
  lt: [
    "Lengvai pradedu pokalbį su nepažįstamais.",
    "Darbą visada baigiu laiku.",
    "Dažnai nerimauju dėl smulkmenų.",
    "Mane domina abstrakčios idėjos.",
    "Užjaučiu tuos, kuriems sunku.",
    "Laikau savo daiktus tvarkingai.",
    "Daugumoje situacijų jaučiuosi ramus.",
    "Turiu turtingą vaizduotę.",
    "Man patinka būti dėmesio centre.",
    "Retai galvoju apie kitų jausmus.",
    "Laikausi tam tikro grafiko.",
    "Lengvai suerzinu.",
    "Man patinka išbandyti naujus ir neįprastus dalykus.",
    "Noriai padedu kitiems.",
    "Tarp nepažįstamų būnu tylus.",
    "Kreipiu dėmesį į smulkmenas.",
    "Dažnai jaučiuosi liūdnas be aiškios priežasties.",
    "Man patinka filosofiniai pokalbiai.",
    "Gerbiu kitų požiūrį.",
    "Didelėje kompanijoje pasikrauna energijos.",
    "Dažnai palieku darbus nebaigtus.",
    "Spaudžiamas išlieku ramus.",
    "Žaviuosi menu ir muzika.",
    "Esu linkęs kritikuoti kitus.",
    "Daug kalbu.",
    "Svarbiems dalykams kruopščiai ruošiuosi.",
    "Lengvai nusimenu.",
    "Man patinka mąstyti apie sudėtingus klausimus.",
    "Pasitikiu žmonėmis.",
    "Vienam man patogiau nei grupėje.",
    "Laikausi pažadų.",
    "Nuotaika man dažnai keičiasi.",
    "Mane domina kitos kultūros.",
    "Stengiuosi nieko neįžeisti.",
    "Grupėje imuosi iniciatyvos.",
    "Atidedu reikalus vėlesniam laikui.",
    "Nerimauju prieš svarbius įvykius.",
    "Pastebiu grožį kasdieniuose dalykuose.",
    "Esu pasiruošęs nusileisti dėl santarvės.",
    "Naujoje kompanijoje jaučiuosi laisvai.",
    "Dirbu atkakliai, kol pabaigiu.",
    "Retai jaučiuosi prislėgtas.",
    "Man patinka sugalvoti naujų būdų ką nors padaryti.",
    "Į kitų klaidas žiūriu su supratimu.",
    "Vengiu didelių susibūrimų.",
    "Planuoju iš anksto.",
    "Nesėkmes išgyvenu sunkiai.",
    "Mane traukia nauji potyriai ir kelionės.",
    "Nuoširdžiai džiaugiuosi kitų sėkme.",
    "Jaučiuosi užtikrintai kalbėdamas prieš žmones.",
  ],
  lv: [
    "Viegli uzsāku sarunu ar svešiniekiem.",
    "Darbu vienmēr pabeidzu laikā.",
    "Bieži uztraucos par sīkumiem.",
    "Mani interesē abstraktas idejas.",
    "Jūtu līdzi tiem, kam ir grūti.",
    "Turu savas lietas kārtībā.",
    "Vairumā situāciju jūtos mierīgs.",
    "Man ir bagāta iztēle.",
    "Man patīk būt uzmanības centrā.",
    "Reti domāju par citu jūtām.",
    "Turos pie noteikta grafika.",
    "Viegli sadusmojos.",
    "Man patīk izmēģināt jaunas un neparastas lietas.",
    "Labprāt palīdzu citiem.",
    "Svešinieku vidū esmu klusējošs.",
    "Pievēršu uzmanību detaļām.",
    "Bieži jūtos skumjš bez redzama iemesla.",
    "Man patīk filozofiskas sarunas.",
    "Cienu citu viedokli.",
    "Lielā sabiedrībā uzlādējos ar enerģiju.",
    "Bieži atstāju lietas nepabeigtas.",
    "Zem spiediena saglabāju mieru.",
    "Apbrīnoju mākslu un mūziku.",
    "Man ir tieksme kritizēt citus.",
    "Es daudz runāju.",
    "Svarīgām lietām rūpīgi gatavojos.",
    "Viegli satraucos.",
    "Man patīk domāt par sarežģītiem jautājumiem.",
    "Uzticos cilvēkiem.",
    "Vienam man ir ērtāk nekā grupā.",
    "Turu solījumus.",
    "Mans garastāvoklis bieži mainās.",
    "Mani interesē citas kultūras.",
    "Cenšos nevienu neaizvainot.",
    "Grupā uzņemos iniciatīvu.",
    "Atlieku lietas uz vēlāku laiku.",
    "Pirms svarīgiem notikumiem uztraucos.",
    "Pamanu skaistumu ikdienišķās lietās.",
    "Esmu gatavs piekāpties saskaņas dēļ.",
    "Jaunā sabiedrībā jūtos brīvi.",
    "Strādāju neatlaidīgi, līdz pabeidzu.",
    "Reti jūtos nomākts.",
    "Man patīk izdomāt jaunus veidus, kā kaut ko paveikt.",
    "Uz citu kļūdām raugos ar sapratni.",
    "Izvairos no lielām sanākšanām.",
    "Plānoju iepriekš.",
    "Neveiksmes pārdzīvoju smagi.",
    "Mani vilina jauni pārdzīvojumi un ceļojumi.",
    "Par citu panākumiem priecājos patiesi.",
    "Jūtos droši, runājot cilvēku priekšā.",
  ],
  et: [
    "Alustan võõrastega hõlpsasti vestlust.",
    "Lõpetan töö alati õigeks ajaks.",
    "Muretsen sageli pisiasjade pärast.",
    "Mind huvitavad abstraktsed ideed.",
    "Tunnen kaasa neile, kellel on raske.",
    "Hoian oma asju korras.",
    "Enamikus olukordades tunnen end rahulikuna.",
    "Mul on rikkalik kujutlusvõime.",
    "Mulle meeldib olla tähelepanu keskpunktis.",
    "Mõtlen harva teiste tunnetele.",
    "Pean kinni kindlast ajakavast.",
    "Ärritun kergesti.",
    "Mulle meeldib proovida uusi ja ebatavalisi asju.",
    "Aitan teisi meelsasti.",
    "Võõraste seas olen vaikne.",
    "Pööran tähelepanu üksikasjadele.",
    "Tunnen end sageli kurvana ilma nähtava põhjuseta.",
    "Mulle meeldivad filosoofilised vestlused.",
    "Austan teiste seisukohti.",
    "Suures seltskonnas laen end energiaga.",
    "Jätan asju sageli lõpetamata.",
    "Surve all jään rahulikuks.",
    "Imetlen kunsti ja muusikat.",
    "Mul on kalduvus teisi kritiseerida.",
    "Räägin palju.",
    "Valmistun tähtsateks asjadeks põhjalikult.",
    "Ärritun kergesti.",
    "Mulle meeldib mõelda keeruliste küsimuste üle.",
    "Usaldan inimesi.",
    "Üksi on mul mugavam kui rühmas.",
    "Pean lubadustest kinni.",
    "Mu meeleolu muutub sageli.",
    "Mind huvitavad teised kultuurid.",
    "Püüan mitte kedagi solvata.",
    "Rühmas võtan initsiatiivi.",
    "Lükkan asju edasi.",
    "Enne tähtsaid sündmusi olen ärev.",
    "Märkan ilu igapäevastes asjades.",
    "Olen valmis järele andma kokkuleppe nimel.",
    "Uues seltskonnas tunnen end vabalt.",
    "Töötan visalt, kuni lõpetan.",
    "Tunnen end harva rõhutuna.",
    "Mulle meeldib välja mõelda uusi viise millegi tegemiseks.",
    "Vaatan teiste vigadele mõistvalt.",
    "Väldin suuri kokkusaamisi.",
    "Planeerin ette.",
    "Ebaõnnestumisi talun raskelt.",
    "Mind tõmbavad uued elamused ja reisimine.",
    "Rõõmustan siiralt teiste edu üle.",
    "Tunnen end kindlalt, kui räägin inimeste ees.",
  ],
  ar: [
    "أبدأ الحديث مع الغرباء بسهولة.",
    "أنجز عملي دائمًا في وقته.",
    "كثيرًا ما أقلق بشأن أمور صغيرة.",
    "تستهويني الأفكار المجردة.",
    "أتعاطف مع من يمرّون بضيق.",
    "أحافظ على ترتيب أغراضي.",
    "أشعر بالهدوء في معظم المواقف.",
    "أتمتع بخيال واسع.",
    "أحب أن أكون محط الأنظار.",
    "نادرًا ما أفكر في مشاعر الآخرين.",
    "ألتزم بجدول محدد.",
    "أنفعل بسرعة.",
    "أحب تجربة أشياء جديدة وغير مألوفة.",
    "أساعد الآخرين عن طيب خاطر.",
    "أميل إلى الصمت بين الغرباء.",
    "أنتبه إلى التفاصيل.",
    "كثيرًا ما أشعر بالحزن دون سبب واضح.",
    "أستمتع بالأحاديث الفلسفية.",
    "أحترم وجهة نظر غيري.",
    "أستمد طاقتي من التجمعات الكبيرة.",
    "كثيرًا ما أترك الأمور دون إنجاز.",
    "أبقى هادئًا تحت الضغط.",
    "أُعجب بالفن والموسيقى.",
    "أميل إلى انتقاد الآخرين.",
    "أتحدث كثيرًا.",
    "أستعد للأمور المهمة استعدادًا دقيقًا.",
    "أنزعج بسهولة.",
    "أحب التفكير في المسائل المعقّدة.",
    "أثق بالناس.",
    "أرتاح وحدي أكثر من ارتياحي في مجموعة.",
    "أفي بوعودي.",
    "يتغيّر مزاجي كثيرًا.",
    "تستهويني الثقافات الأخرى.",
    "أحرص على ألا أجرح أحدًا.",
    "أبادر بالقيادة في المجموعة.",
    "أؤجل الأمور إلى وقت لاحق.",
    "أتوتر قبل المناسبات المهمة.",
    "ألاحظ الجمال في الأشياء اليومية.",
    "أتنازل من أجل الوفاق.",
    "أشعر بالارتياح في صحبة جديدة.",
    "أعمل بمثابرة حتى أنتهي.",
    "نادرًا ما أشعر بالإحباط.",
    "أحب ابتكار طرق جديدة لإنجاز الأمور.",
    "أنظر إلى أخطاء الآخرين بتفهّم.",
    "أتجنب التجمعات الكبيرة.",
    "أخطط مسبقًا.",
    "أتأثر بالإخفاقات كثيرًا.",
    "تجذبني التجارب الجديدة والسفر.",
    "أفرح بصدق لنجاح الآخرين.",
    "أشعر بالثقة حين أتحدث أمام الناس.",
  ],
  he: [
    "אני פותח בשיחה עם זרים בקלות.",
    "אני תמיד מסיים את עבודתי בזמן.",
    "אני דואג לעתים קרובות בגלל דברים קטנים.",
    "רעיונות מופשטים מעניינים אותי.",
    "אני מזדהה עם מי שקשה לו.",
    "אני שומר על סדר בחפציי.",
    "ברוב המצבים אני מרגיש רגוע.",
    "יש לי דמיון עשיר.",
    "אני אוהב להיות במרכז תשומת הלב.",
    "אני ממעט לחשוב על רגשות של אחרים.",
    "אני מקפיד על לוח זמנים מסוים.",
    "אני מתעצבן בקלות.",
    "אני אוהב לנסות דברים חדשים ולא שגרתיים.",
    "אני עוזר לאחרים ברצון.",
    "בין זרים אני שתקן.",
    "אני שם לב לפרטים.",
    "לעתים קרובות אני עצוב בלי סיבה נראית לעין.",
    "אני נהנה משיחות פילוסופיות.",
    "אני מכבד את נקודת המבט של אחרים.",
    "בחברה גדולה אני נטען באנרגיה.",
    "לעתים קרובות אני משאיר דברים לא גמורים.",
    "תחת לחץ אני נשאר רגוע.",
    "אני מתפעל מאמנות ומוזיקה.",
    "יש לי נטייה לבקר אחרים.",
    "אני מדבר הרבה.",
    "לדברים חשובים אני מתכונן ביסודיות.",
    "אני נסער בקלות.",
    "אני אוהב לחשוב על שאלות מורכבות.",
    "אני נותן אמון באנשים.",
    "נוח לי לבד יותר מאשר בקבוצה.",
    "אני עומד בהבטחות שלי.",
    "מצב הרוח שלי משתנה לעתים קרובות.",
    "תרבויות אחרות מעניינות אותי.",
    "אני משתדל לא לפגוע באיש.",
    "בקבוצה אני לוקח יוזמה.",
    "אני דוחה דברים למועד מאוחר יותר.",
    "לפני אירועים חשובים אני חרד.",
    "אני מבחין ביופי שבדברים יומיומיים.",
    "אני מוכן לוותר למען הסכמה.",
    "בחברה חדשה אני מרגיש בנוח.",
    "אני עובד בהתמדה עד שאני מסיים.",
    "אני ממעט להרגיש מדוכדך.",
    "אני אוהב להמציא דרכים חדשות לעשות משהו.",
    "אני מביט בטעויות של אחרים בהבנה.",
    "אני נמנע מהתכנסויות גדולות.",
    "אני מתכנן מראש.",
    "כישלונות קשים לי.",
    "חוויות חדשות ונסיעות מושכות אותי.",
    "אני שמח בכנות בהצלחות של אחרים.",
    "אני מרגיש בטוח כשאני מדבר מול אנשים.",
  ],
  fa: [
    "به‌آسانی با ناآشنایان سر صحبت را باز می‌کنم.",
    "کارم را همیشه به‌موقع به پایان می‌رسانم.",
    "اغلب بابت چیزهای کوچک نگران می‌شوم.",
    "اندیشه‌های انتزاعی برایم جذاب‌اند.",
    "با کسانی که در تنگنا هستند همدلی می‌کنم.",
    "وسایلم را مرتب نگه می‌دارم.",
    "در بیشتر موقعیت‌ها آرام هستم.",
    "خیال پرباری دارم.",
    "دوست دارم کانون توجه باشم.",
    "به‌ندرت به احساس دیگران می‌اندیشم.",
    "به برنامهٔ مشخصی پایبندم.",
    "زود از کوره در می‌روم.",
    "دوست دارم چیزهای تازه و غیرمعمول را بیازمایم.",
    "با میل به دیگران کمک می‌کنم.",
    "میان ناآشنایان کم‌حرفم.",
    "به جزئیات توجه می‌کنم.",
    "اغلب بی‌دلیل روشن غمگین می‌شوم.",
    "از گفت‌وگوهای فلسفی لذت می‌برم.",
    "دیدگاه دیگران را محترم می‌شمارم.",
    "در جمع‌های بزرگ سرشار از انرژی می‌شوم.",
    "اغلب کارها را ناتمام رها می‌کنم.",
    "زیر فشار آرام می‌مانم.",
    "شیفتهٔ هنر و موسیقی‌ام.",
    "گرایش دارم از دیگران انتقاد کنم.",
    "زیاد حرف می‌زنم.",
    "برای کارهای مهم به‌دقت آماده می‌شوم.",
    "زود آشفته می‌شوم.",
    "دوست دارم دربارهٔ پرسش‌های پیچیده بیندیشم.",
    "به مردم اعتماد می‌کنم.",
    "تنهایی برایم راحت‌تر از بودن در گروه است.",
    "به قول‌هایم پایبندم.",
    "حال و هوایم زود دگرگون می‌شود.",
    "فرهنگ‌های دیگر برایم جذاب‌اند.",
    "می‌کوشم دل کسی را نشکنم.",
    "در گروه ابتکار عمل را به دست می‌گیرم.",
    "کارها را به بعد وامی‌گذارم.",
    "پیش از رویدادهای مهم دلشوره دارم.",
    "زیبایی را در چیزهای روزمره می‌بینم.",
    "برای حفظ سازگاری کوتاه می‌آیم.",
    "در جمع تازه راحتم.",
    "با پشتکار کار می‌کنم تا تمام شود.",
    "به‌ندرت افسرده می‌شوم.",
    "دوست دارم راه‌های تازه‌ای برای انجام کارها بیابم.",
    "به خطای دیگران با درک می‌نگرم.",
    "از گردهمایی‌های بزرگ دوری می‌کنم.",
    "از پیش برنامه می‌ریزم.",
    "شکست‌ها را سخت تاب می‌آورم.",
    "تجربه‌های تازه و سفر مرا می‌کشاند.",
    "از کامیابی دیگران صمیمانه شاد می‌شوم.",
    "هنگام سخن‌گفتن پیش مردم اعتماد به نفس دارم.",
  ],
  hi: [
    "मैं अजनबियों से आसानी से बातचीत शुरू कर लेता हूँ।",
    "मैं अपना काम हमेशा समय पर पूरा करता हूँ।",
    "मैं अक्सर छोटी-छोटी बातों की चिंता करता हूँ।",
    "मुझे अमूर्त विचार रुचिकर लगते हैं।",
    "जिन्हें कठिनाई हो, उनसे मुझे सहानुभूति होती है।",
    "मैं अपनी चीज़ें व्यवस्थित रखता हूँ।",
    "अधिकतर स्थितियों में मैं शांत रहता हूँ।",
    "मेरी कल्पनाशक्ति समृद्ध है।",
    "मुझे ध्यान का केंद्र बनना अच्छा लगता है।",
    "मैं दूसरों की भावनाओं के बारे में कम ही सोचता हूँ।",
    "मैं एक तय दिनचर्या का पालन करता हूँ।",
    "मुझे जल्दी ग़ुस्सा आ जाता है।",
    "मुझे नई और अनोखी चीज़ें आज़माना पसंद है।",
    "मैं दूसरों की सहर्ष मदद करता हूँ।",
    "अजनबियों के बीच मैं चुप रहता हूँ।",
    "मैं बारीकियों पर ध्यान देता हूँ।",
    "बिना स्पष्ट कारण के मुझे अक्सर उदासी घेर लेती है।",
    "मुझे दार्शनिक बातचीत अच्छी लगती है।",
    "मैं दूसरों के दृष्टिकोण का आदर करता हूँ।",
    "बड़े समूह में मुझे ऊर्जा मिलती है।",
    "मैं अक्सर काम अधूरा छोड़ देता हूँ।",
    "दबाव में भी मैं शांत रहता हूँ।",
    "मैं कला और संगीत की सराहना करता हूँ।",
    "मेरा झुकाव दूसरों की आलोचना की ओर रहता है।",
    "मैं बहुत बोलता हूँ।",
    "महत्त्वपूर्ण कामों की मैं अच्छी तैयारी करता हूँ।",
    "मैं जल्दी विचलित हो जाता हूँ।",
    "मुझे जटिल प्रश्नों पर सोचना अच्छा लगता है।",
    "मैं लोगों पर भरोसा करता हूँ।",
    "समूह से अधिक मुझे अकेले सहज लगता है।",
    "मैं अपने वादे निभाता हूँ।",
    "मेरा मिज़ाज अक्सर बदलता रहता है।",
    "मुझे दूसरी संस्कृतियों में रुचि है।",
    "मैं कोशिश करता हूँ कि किसी को ठेस न पहुँचे।",
    "समूह में मैं पहल करता हूँ।",
    "मैं काम बाद के लिए टाल देता हूँ।",
    "महत्त्वपूर्ण अवसरों से पहले मैं घबरा जाता हूँ।",
    "रोज़मर्रा की चीज़ों में भी मुझे सुंदरता दिखती है।",
    "सामंजस्य के लिए मैं झुकने को तैयार रहता हूँ।",
    "नई संगत में मैं सहज महसूस करता हूँ।",
    "जब तक पूरा न हो जाए मैं लगन से काम करता हूँ।",
    "मैं कम ही निराश होता हूँ।",
    "मुझे कुछ करने के नए तरीक़े सोचना अच्छा लगता है।",
    "दूसरों की भूलों को मैं समझ के साथ देखता हूँ।",
    "मैं बड़े जमावड़ों से बचता हूँ।",
    "मैं पहले से योजना बनाता हूँ।",
    "असफलताएँ मुझे भारी पड़ती हैं।",
    "नए अनुभव और यात्रा मुझे खींचते हैं।",
    "दूसरों की सफलता पर मुझे सच्ची ख़ुशी होती है।",
    "लोगों के सामने बोलते समय मैं आश्वस्त रहता हूँ।",
  ],
  ja: [
    "初対面の人にも気軽に話しかけられる。",
    "仕事はいつも期限までに終える。",
    "小さなことをよく気に病む。",
    "抽象的な考えに関心がある。",
    "つらい立場の人に共感する。",
    "身のまわりを整えている。",
    "たいていの場面で落ち着いていられる。",
    "想像力が豊かだ。",
    "注目の的になるのが好きだ。",
    "他人の気持ちをあまり考えない。",
    "決まった予定に沿って動く。",
    "すぐに苛立つ。",
    "新しく変わったことを試すのが好きだ。",
    "進んで人を手伝う。",
    "知らない人の中では口数が少ない。",
    "細かい点に気を配る。",
    "はっきりした理由もなく気分が沈むことが多い。",
    "考えを深める話し合いが好きだ。",
    "相手の見方を尊重する。",
    "大勢の中にいると元気が出る。",
    "やりかけのまま放っておくことが多い。",
    "重圧の中でも落ち着いていられる。",
    "芸術や音楽に心を動かされる。",
    "人を批判しがちだ。",
    "よく喋るほうだ。",
    "大事なことには入念に備える。",
    "動揺しやすい。",
    "込み入った問いについて考えるのが好きだ。",
    "人を信頼する。",
    "集団の中より一人のほうが気楽だ。",
    "約束は守る。",
    "気分がよく変わる。",
    "他の文化に関心がある。",
    "誰も傷つけないよう気を配る。",
    "集団では自分から動く。",
    "物事を後回しにする。",
    "大事な場面の前は緊張する。",
    "何気ないものの中に美しさを見つける。",
    "丸く収めるために譲ることができる。",
    "新しい集まりでも気後れしない。",
    "終わるまで粘り強く続ける。",
    "気分が塞ぐことは少ない。",
    "新しいやり方を考えるのが好きだ。",
    "人の失敗を大目に見る。",
    "大きな集まりは避ける。",
    "前もって計画を立てる。",
    "失敗をひきずりやすい。",
    "新しい経験や旅に惹かれる。",
    "人の成功を心から喜べる。",
    "人前で話すときも落ち着いていられる。",
  ],
  vi: [
    "Là linh hồn của bữa tiệc",
    "Ít quan tâm đến người khác",
    "Luôn chuẩn bị sẵn sàng",
    "Dễ bị căng thẳng",
    "Có vốn từ phong phú",
    "Không nói nhiều",
    "Quan tâm đến mọi người",
    "Để đồ đạc bừa bãi",
    "Thư thái phần lớn thời gian",
    "Khó hiểu những ý tưởng trừu tượng",
    "Thấy thoải mái khi ở cạnh mọi người",
    "Nói lời xúc phạm người khác",
    "Chú ý đến từng chi tiết",
    "Hay lo lắng về mọi thứ",
    "Có trí tưởng tượng sống động",
    "Thường giữ mình ở phía sau",
    "Đồng cảm với cảm xúc của người khác",
    "Làm mọi thứ rối tung lên",
    "Hiếm khi thấy buồn",
    "Không hứng thú với những ý tưởng trừu tượng",
    "Chủ động bắt chuyện",
    "Không thực sự quan tâm đến người khác",
    "Hoàn thành việc nhà ngay lập tức",
    "Dễ buồn bực",
    "Có những ý tưởng xuất sắc",
    "Ít có điều để nói",
    "Có trái tim mềm yếu",
    "Thường quên để đồ vật về đúng chỗ",
    "Không dễ bị điều gì làm phiền",
    "Không có trí tưởng tượng tốt",
    "Trò chuyện với nhiều người khác nhau trong các bữa tiệc",
    "Không mấy để tâm đến chuyện của người khác",
    "Thích sự ngăn nắp",
    "Tâm trạng thay đổi nhiều",
    "Nhanh hiểu vấn đề",
    "Không thích thu hút sự chú ý về mình",
    "Dành thời gian cho người khác",
    "Trốn tránh trách nhiệm của mình",
    "Tâm trạng thay đổi thất thường",
    "Dùng những từ ngữ khó",
    "Không ngại làm trung tâm của sự chú ý",
    "Cảm nhận được cảm xúc của người khác",
    "Tuân theo lịch trình đã định",
    "Dễ cáu kỉnh",
    "Dành thời gian suy ngẫm về mọi việc",
    "Ít nói khi ở cạnh người lạ",
    "Khiến mọi người thấy dễ chịu",
    "Tỉ mỉ trong công việc",
    "Thường thấy buồn",
    "Đầy ắp ý tưởng",
  ],
  ms: [
    "Menjadi tumpuan dalam majlis",
    "Kurang mengambil berat tentang orang lain",
    "Sentiasa bersedia",
    "Mudah berasa tertekan",
    "Mempunyai perbendaharaan kata yang kaya",
    "Tidak banyak bercakap",
    "Berminat dengan orang ramai",
    "Membiarkan barang saya bersepah",
    "Berasa tenang hampir sepanjang masa",
    "Sukar memahami idea abstrak",
    "Berasa selesa ketika bersama orang lain",
    "Menghina orang lain",
    "Memberi perhatian kepada perincian",
    "Sering risau tentang banyak perkara",
    "Mempunyai imaginasi yang hidup",
    "Kekal di belakang tabir",
    "Bersimpati dengan perasaan orang lain",
    "Merumitkan keadaan",
    "Jarang berasa murung",
    "Tidak berminat dengan idea abstrak",
    "Memulakan perbualan",
    "Tidak begitu berminat dengan orang lain",
    "Menyiapkan kerja rumah dengan segera",
    "Mudah berkecil hati",
    "Mempunyai idea yang cemerlang",
    "Tidak banyak yang hendak dikatakan",
    "Mempunyai hati yang lembut",
    "Sering lupa meletakkan barang di tempat asalnya",
    "Tidak mudah diganggu oleh sesuatu",
    "Tidak mempunyai imaginasi yang baik",
    "Bercakap dengan ramai orang berbeza dalam majlis",
    "Kurang mengambil peduli hal orang lain",
    "Suka keteraturan",
    "Kerap berubah perasaan",
    "Cepat memahami sesuatu",
    "Tidak suka menarik perhatian kepada diri sendiri",
    "Meluangkan masa untuk orang lain",
    "Mengelak tanggungjawab saya",
    "Kerap mengalami perubahan mood",
    "Menggunakan perkataan yang sukar",
    "Tidak kisah menjadi tumpuan perhatian",
    "Merasai emosi orang lain",
    "Mengikut jadual",
    "Mudah berasa jengkel",
    "Meluangkan masa merenung sesuatu",
    "Pendiam ketika bersama orang yang tidak dikenali",
    "Membuatkan orang berasa selesa",
    "Sangat teliti dalam kerja saya",
    "Sering berasa murung",
    "Penuh dengan idea",
  ],
  tl: [
    "Ako ang buhay ng handaan",
    "Kaunti lang ang malasakit ko sa iba",
    "Lagi akong handa",
    "Madali akong ma-stress",
    "May malawak akong bokabularyo",
    "Hindi ako masyadong madaldal",
    "Interesado ako sa mga tao",
    "Nagkakalat ako ng aking gamit",
    "Kalmado ako halos palagi",
    "Nahihirapan akong umunawa ng abstraktong ideya",
    "Komportable ako kapag kasama ang ibang tao",
    "Nakakasakit ako ng damdamin ng iba",
    "Pinapansin ko ang maliliit na detalye",
    "Madalas akong mag-alala sa mga bagay",
    "May matingkad akong imahinasyon",
    "Nananatili ako sa likuran",
    "Nakikiramay ako sa damdamin ng iba",
    "Ginugulo ko ang mga bagay-bagay",
    "Bihira akong malungkot",
    "Hindi ako interesado sa abstraktong ideya",
    "Ako ang nagsisimula ng usapan",
    "Hindi talaga ako interesado sa iba",
    "Agad kong tinatapos ang gawaing bahay",
    "Madali akong mainis",
    "May mahuhusay akong ideya",
    "Kakaunti ang masasabi ko",
    "May malambot akong puso",
    "Madalas kong nakakalimutang ibalik ang gamit sa tamang lugar",
    "Hindi ako madaling maistorbo",
    "Wala akong magandang imahinasyon",
    "Nakikipag-usap ako sa iba't ibang tao sa mga handaan",
    "Hindi ko masyadong pinapansin ang buhay ng iba",
    "Gusto ko ang kaayusan",
    "Madalas magbago ang aking timpla",
    "Mabilis akong umunawa ng mga bagay",
    "Ayaw kong maging sentro ng pansin",
    "Naglalaan ako ng oras para sa iba",
    "Iniiwasan ko ang aking mga tungkulin",
    "Madalas magbago-bago ang aking damdamin",
    "Gumagamit ako ng malalalim na salita",
    "Hindi ako tutol na maging sentro ng pansin",
    "Nararamdaman ko ang emosyon ng iba",
    "Sumusunod ako sa iskedyul",
    "Madali akong mairita",
    "Naglalaan ako ng oras para magmuni-muni",
    "Tahimik ako kapag kasama ang mga hindi kakilala",
    "Napapadali ko ang pakiramdam ng mga tao",
    "Maingat ako sa aking trabaho",
    "Madalas akong malungkot",
    "Puno ako ng ideya",
  ],
  af: [
    "Is die middelpunt van die partytjie",
    "Gee min om vir ander",
    "Is altyd voorbereid",
    "Raak maklik gestres",
    "Het 'n ryk woordeskat",
    "Praat nie baie nie",
    "Stel belang in mense",
    "Los my goed rond",
    "Is die meeste van die tyd ontspanne",
    "Sukkel om abstrakte idees te verstaan",
    "Voel gemaklik tussen mense",
    "Beledig mense",
    "Gee aandag aan besonderhede",
    "Bekommer my oor dinge",
    "Het 'n lewendige verbeelding",
    "Bly op die agtergrond",
    "Voel saam met ander se gevoelens",
    "Maak 'n gemors van dinge",
    "Voel selde neerslagtig",
    "Stel nie belang in abstrakte idees nie",
    "Begin gesprekke",
    "Stel nie regtig in ander belang nie",
    "Kry huistake dadelik gedoen",
    "Raak maklik ontsteld",
    "Het uitstekende idees",
    "Het min om te sê",
    "Het 'n sagte hart",
    "Vergeet dikwels om dinge terug te sit op hul plek",
    "Word nie maklik deur dinge gepla nie",
    "Het nie 'n goeie verbeelding nie",
    "Praat met baie verskillende mense by partytjies",
    "Gee nie regtig om oor ander se sake nie",
    "Hou van orde",
    "Verander baie van bui",
    "Verstaan dinge vinnig",
    "Hou nie daarvan om aandag op myself te vestig nie",
    "Maak tyd vir ander",
    "Ontduik my pligte",
    "Het gereelde buiwisselings",
    "Gebruik moeilike woorde",
    "Gee nie om om die middelpunt van aandag te wees nie",
    "Voel ander se emosies aan",
    "Volg 'n skedule",
    "Raak maklik geïrriteerd",
    "Bestee tyd daaraan om oor dinge na te dink",
    "Is stil tussen vreemdelinge",
    "Laat mense op hul gemak voel",
    "Is presies in my werk",
    "Voel dikwels neerslagtig",
    "Is vol idees",
  ],
  sq: [
    "Jam shpirti i festës",
    "Shqetësohem pak për të tjerët",
    "Jam gjithmonë i përgatitur",
    "Stresohem lehtë",
    "Kam fjalor të pasur",
    "Nuk flas shumë",
    "Interesohem për njerëzit",
    "I lë sendet e mia rrëmujë",
    "Jam i qetë pjesën më të madhe të kohës",
    "E kam të vështirë të kuptoj idetë abstrakte",
    "Ndihem rehat pranë njerëzve",
    "Fyej njerëzit",
    "I kushtoj vëmendje detajeve",
    "Shqetësohem për gjërat",
    "Kam imagjinatë të gjallë",
    "Qëndroj në prapaskenë",
    "Ndiej dhembshuri për ndjenjat e të tjerëve",
    "I ngatërroj gjërat",
    "Rrallë ndihem i trishtuar",
    "Nuk interesohem për idetë abstrakte",
    "Nis bisedat",
    "Nuk interesohem vërtet për të tjerët",
    "I kryej punët e shtëpisë menjëherë",
    "Mërzitem lehtë",
    "Kam ide të shkëlqyera",
    "Kam pak për të thënë",
    "Kam zemër të butë",
    "Shpesh harroj t'i vendos sendet në vendin e duhur",
    "Nuk shqetësohem lehtë nga gjërat",
    "Nuk kam imagjinatë të mirë",
    "Flas me shumë njerëz të ndryshëm në festa",
    "Nuk merrem shumë me punët e të tjerëve",
    "Më pëlqen rregulli",
    "Ndryshoj shpesh humor",
    "I kuptoj gjërat shpejt",
    "Nuk më pëlqen të tërheq vëmendjen te vetja",
    "Gjej kohë për të tjerët",
    "I shmangem detyrave të mia",
    "Kam luhatje të shpeshta humori",
    "Përdor fjalë të vështira",
    "Nuk më prish punë të jem në qendër të vëmendjes",
    "I ndiej emocionet e të tjerëve",
    "Ndjek një orar",
    "Nervozohem lehtë",
    "Kaloj kohë duke reflektuar mbi gjërat",
    "Jam i heshtur pranë të panjohurve",
    "I bëj njerëzit të ndihen rehat",
    "Jam i përpiktë në punën time",
    "Shpesh ndihem i trishtuar",
    "Jam plot ide",
  ],
  sw: [
    "Mimi ni roho ya sherehe",
    "Sijali sana kuhusu wengine",
    "Mimi huwa tayari daima",
    "Napata msongo kwa urahisi",
    "Nina msamiati mpana",
    "Siongei sana",
    "Ninawajali watu",
    "Naacha vitu vyangu vitapakae",
    "Nimetulia muda mwingi",
    "Ninapata ugumu kuelewa mawazo dhahania",
    "Najisikia huru nikiwa na watu",
    "Ninawatukana watu",
    "Nazingatia maelezo madogo",
    "Nina wasiwasi kuhusu mambo",
    "Nina mawazo ya kina",
    "Nabaki nyuma",
    "Nahurumia hisia za wengine",
    "Nachafua mambo",
    "Mara chache huhisi huzuni",
    "Sipendi mawazo dhahania",
    "Naanzisha mazungumzo",
    "Sina hamu kubwa na wengine",
    "Namaliza kazi za nyumbani mara moja",
    "Naudhika kwa urahisi",
    "Nina mawazo bora",
    "Nina machache ya kusema",
    "Nina moyo laini",
    "Mara nyingi nasahau kurudisha vitu mahali pake",
    "Sisumbuliwi kwa urahisi na mambo",
    "Sina mawazo mazuri ya ubunifu",
    "Naongea na watu wengi tofauti kwenye sherehe",
    "Sijishughulishi sana na mambo ya wengine",
    "Napenda mpangilio",
    "Hisia zangu hubadilika sana",
    "Naelewa mambo haraka",
    "Sipendi kuvutia hisia kwangu",
    "Natenga muda kwa ajili ya wengine",
    "Nakwepa majukumu yangu",
    "Hisia zangu hubadilika mara kwa mara",
    "Natumia maneno magumu",
    "Sijali kuwa kitovu cha uangalifu",
    "Nahisi hisia za wengine",
    "Nafuata ratiba",
    "Nakasirika kwa urahisi",
    "Natumia muda kutafakari mambo",
    "Nimetulia nikiwa na wageni",
    "Nawafanya watu wajisikie huru",
    "Nina umakini mkubwa katika kazi yangu",
    "Mara nyingi nahisi huzuni",
    "Nimejaa mawazo",
  ],
  th: [
    "เป็นศูนย์กลางของงานเลี้ยง",
    "ไม่ค่อยใส่ใจผู้อื่น",
    "เตรียมพร้อมเสมอ",
    "เครียดง่าย",
    "มีคลังคำศัพท์กว้างขวาง",
    "ไม่ค่อยพูดมาก",
    "สนใจในตัวผู้คน",
    "วางของทิ้งไว้เกลื่อนกลาด",
    "ผ่อนคลายเกือบตลอดเวลา",
    "เข้าใจความคิดเชิงนามธรรมได้ยาก",
    "รู้สึกสบายใจเมื่ออยู่กับผู้คน",
    "พูดจาดูถูกผู้อื่น",
    "ใส่ใจในรายละเอียด",
    "กังวลกับเรื่องต่างๆ",
    "มีจินตนาการแจ่มชัด",
    "ชอบอยู่เบื้องหลัง",
    "เห็นอกเห็นใจความรู้สึกของผู้อื่น",
    "ทำเรื่องต่างๆ ให้ยุ่งเหยิง",
    "ไม่ค่อยรู้สึกหดหู่",
    "ไม่สนใจความคิดเชิงนามธรรม",
    "เป็นฝ่ายเริ่มบทสนทนา",
    "ไม่ได้สนใจผู้อื่นจริงจัง",
    "ทำงานบ้านให้เสร็จทันที",
    "ขุ่นเคืองใจง่าย",
    "มีความคิดที่ยอดเยี่ยม",
    "มีเรื่องจะพูดไม่มากนัก",
    "มีจิตใจอ่อนโยน",
    "มักลืมเก็บของกลับเข้าที่",
    "ไม่ค่อยถูกรบกวนใจโดยง่าย",
    "ไม่มีจินตนาการที่ดีนัก",
    "พูดคุยกับผู้คนหลากหลายในงานเลี้ยง",
    "ไม่ค่อยสนใจเรื่องราวของคนอื่น",
    "ชอบความเป็นระเบียบ",
    "อารมณ์เปลี่ยนแปลงบ่อย",
    "เข้าใจสิ่งต่างๆ ได้เร็ว",
    "ไม่ชอบดึงความสนใจมาที่ตัวเอง",
    "เจียดเวลาให้ผู้อื่น",
    "หลีกเลี่ยงหน้าที่ของตน",
    "อารมณ์แปรปรวนบ่อยครั้ง",
    "ใช้คำยากๆ",
    "ไม่รังเกียจที่จะเป็นจุดสนใจ",
    "รับรู้อารมณ์ของผู้อื่นได้",
    "ทำตามตารางเวลา",
    "หงุดหงิดง่าย",
    "ใช้เวลาไตร่ตรองเรื่องต่างๆ",
    "เงียบขรึมเมื่ออยู่กับคนแปลกหน้า",
    "ทำให้ผู้คนรู้สึกผ่อนคลาย",
    "พิถีพิถันในงานของตน",
    "มักรู้สึกหดหู่",
    "เต็มไปด้วยความคิด",
  ],
  ko: [
    "모임에서 분위기를 이끄는 편이다",
    "다른 사람에게 별로 관심이 없다",
    "항상 준비가 되어 있다",
    "쉽게 스트레스를 받는다",
    "어휘가 풍부하다",
    "말수가 적은 편이다",
    "사람들에게 관심이 많다",
    "물건을 여기저기 늘어놓는다",
    "대체로 마음이 편안하다",
    "추상적인 개념을 이해하기 어렵다",
    "사람들과 있을 때 편안하다",
    "남에게 상처 주는 말을 한다",
    "세부 사항에 주의를 기울인다",
    "이런저런 걱정이 많다",
    "상상력이 생생하다",
    "뒤에 물러나 있는 편이다",
    "타인의 감정에 공감한다",
    "일을 엉망으로 만들곤 한다",
    "우울함을 느끼는 일이 드물다",
    "추상적인 생각에는 흥미가 없다",
    "먼저 대화를 시작한다",
    "사실 다른 사람에게 관심이 없다",
    "집안일을 바로 끝낸다",
    "쉽게 기분이 상한다",
    "뛰어난 아이디어를 낸다",
    "할 말이 별로 없다",
    "마음이 여린 편이다",
    "물건을 제자리에 두는 것을 자주 잊는다",
    "웬만한 일에는 흔들리지 않는다",
    "상상력이 그리 좋지 않다",
    "모임에서 여러 사람과 두루 이야기한다",
    "남의 일에는 그다지 신경 쓰지 않는다",
    "질서 있는 것을 좋아한다",
    "기분이 자주 바뀐다",
    "이해가 빠른 편이다",
    "내게 관심이 쏠리는 것을 좋아하지 않는다",
    "다른 사람을 위해 시간을 낸다",
    "맡은 일을 회피한다",
    "감정 기복이 잦다",
    "어려운 낱말을 쓴다",
    "주목받는 것이 싫지 않다",
    "타인의 감정을 잘 느낀다",
    "정해진 일정을 지킨다",
    "쉽게 짜증이 난다",
    "이런저런 생각을 곱씹는 시간을 갖는다",
    "낯선 사람 앞에서는 조용하다",
    "사람들을 편안하게 해 준다",
    "일할 때 꼼꼼하다",
    "자주 우울함을 느낀다",
    "아이디어가 넘친다",
  ],
  zh: [
    "是聚会中的活跃人物",
    "不太关心他人",
    "总是做好准备",
    "容易感到压力",
    "词汇量丰富",
    "话不多",
    "对人感兴趣",
    "东西随手乱放",
    "大部分时候都很放松",
    "难以理解抽象概念",
    "和人相处时感到自在",
    "会说伤人的话",
    "注重细节",
    "常常为事情担忧",
    "想象力生动",
    "习惯待在幕后",
    "能体谅他人的感受",
    "常把事情弄得一团糟",
    "很少感到低落",
    "对抽象观念不感兴趣",
    "会主动开启话题",
    "其实并不太在意别人",
    "家务总是立刻做完",
    "容易心情不好",
    "常有很棒的点子",
    "没有太多话要说",
    "心肠很软",
    "经常忘记把东西放回原处",
    "不容易被事情困扰",
    "想象力并不好",
    "在聚会上会和很多不同的人交谈",
    "不太留意别人的事",
    "喜欢井然有序",
    "情绪变化很大",
    "理解事情很快",
    "不喜欢把注意力引到自己身上",
    "愿意为别人腾出时间",
    "会逃避自己的责任",
    "情绪起伏频繁",
    "会使用生僻的词",
    "不介意成为关注的焦点",
    "能感受到他人的情绪",
    "按照计划表行事",
    "容易被激怒",
    "会花时间反思事情",
    "面对陌生人时很安静",
    "能让人感到自在",
    "工作上一丝不苟",
    "经常感到低落",
    "脑子里满是想法",
  ],
};

function itemsFor(lang){
  const t = ITEMS_I18N[lang];
  if (!t) return ITEMS_EN;
  // keep the trait/branch coding from the English master, swap only the text
  return ITEMS_EN.map((it, i) => [t[i] != null ? t[i] : it[0], it[1], it[2]]);
}
let ITEMS = itemsFor(window.I18n?.lang || window.PAGE_LANG || 'en');
document.addEventListener('DOMContentLoaded', () => {
  ITEMS = itemsFor(window.I18n?.lang || window.PAGE_LANG || 'en');
});

const TRAIT_INFO={
  E:{name:'Extraversion',       color:'#f59e0b',low:'Reserved & reflective — you gain energy from solitude and deep one-on-one connections.',     high:'Outgoing & energized by social interaction. You thrive in groups and love being the center of attention.'},
  A:{name:'Agreeableness',      color:'#10b981',low:'Analytical and objective — you prioritize facts over feelings and can be bluntly honest.',   high:'Warm, cooperative, and empathetic — you value harmony and the wellbeing of others.'},
  C:{name:'Conscientiousness',  color:'#6366f1',low:'Flexible and spontaneous — you adapt on the fly rather than following strict plans.',         high:'Organized, reliable, and goal-driven. You take your commitments seriously.'},
  N:{name:'Neuroticism',        color:'#ef4444',low:'Emotionally stable and resilient — you stay calm under pressure and recover quickly from stress.', high:'More emotionally reactive — you experience stress, anxiety, and mood shifts more intensely.'},
  O:{name:'Openness',           color:'#8b5cf6',low:'Practical and conventional — you prefer established methods and concrete, familiar ideas.',    high:'Curious, imaginative, and open to new experiences. You love exploring ideas and aesthetics.'}
};

const TRAIT_ORDER=['O','C','E','A','N'];
let current=0, answers={};

function pct(raw){ // raw 10-50 per trait → percentile (based on normative data)
  const t=(raw-10)/40; return Math.round(t*94+3);
}

function renderShell(){
  document.getElementById('test-root').innerHTML=`
  <div class="instruction-card">
    <h3>${_t('b5_how_title',"How It Works")}</h3>
    <ul>
      <li>${_t('b5_how0',"{n} short statements. Rate how accurately each describes you.").replace('{n}',ITEMS.length)}</li>
      <li>${_t('b5_how1',"There are no right or wrong answers — be honest for the most accurate result.")}</li>
      <li>${_t('b5_how2',"Takes about 7 minutes.")}</li>
    </ul>
  </div>
  <div class="test-card-ui">
    <div class="test-ui-header">
      <span class="test-ui-title">🪄 ${_t('b5_title',"Big Five Personality Test")}</span>
      <span id="b5-counter" class="q-counter">Q1 / ${ITEMS.length}</span>
    </div>
    <div class="test-ui-body" id="b5-body">
      <p style="color:var(--text-2)">${_t('b5_start_desc',"The most accurate personality model in psychology, used by researchers worldwide.")}</p>
      <button class="btn btn-primary" onclick="B5Test.start()">Start Test</button>
    </div>
    <div style="padding:12px 24px;border-top:1px solid var(--border)">
      <div class="q-progress-bar"><div class="q-progress-fill" id="b5-prog" style="width:0%"></div></div>
    </div>
  </div>
  <div class="results-panel" id="b5-results"></div>`;
}

function renderQ(){
  const [text,,] = ITEMS[current];
  document.getElementById('b5-counter').textContent=`Q${current+1} / ${ITEMS.length}`;
  document.getElementById('b5-prog').style.width=`${(current/ITEMS.length)*100}%`;
  const labels=[1,2,3,4,5].map(n=>[String(n), _t('likert_'+n)]);
  const btns=labels.map(([n,l],i)=>`
    <button class="likert-btn" onclick="B5Test.answer(${i+1})">
      <span class="likert-num">${n}</span>
      <span class="likert-label">${l.replace('\n','<br>')}</span>
    </button>`).join('');
  document.getElementById('b5-body').innerHTML=`
    <p class="q-counter" style="margin-bottom:4px">Q${current+1} / ${ITEMS.length}</p>
    <p class="question-text">"${text}"</p>
    <div class="likert">${btns}</div>`;
}

function calcScores(){
  const raw={E:0,A:0,C:0,N:0,O:0};
  ITEMS.forEach(([,trait,rev],i)=>{
    const ans=answers[i]||3;
    raw[trait]+= rev?(6-ans):ans;
  });
  return raw;
}

function showResults(){
  const raw=calcScores();
  const pcts={};
  TRAIT_ORDER.forEach(t=>{ pcts[t]=pct(raw[t]); });

  const bars=TRAIT_ORDER.map(t=>{
    const info=TRAIT_INFO[t];
    const p=pcts[t];
    const desc=p>=60?info.high:p<=40?info.low:`A balanced mix of both ends of ${info.name}.`;
    return `<div class="trait-bar-item">
      <div class="trait-bar-top">
        <span class="trait-name" style="color:${info.color}">${info.name}</span>
        <span class="trait-pct">${(window.ordinal?window.ordinal(p):p+'th')} percentile</span>
      </div>
      <div class="trait-bar-track"><div class="trait-bar-fill" style="width:${p}%;background:${info.color}"></div></div>
      <p style="font-size:.78rem;color:var(--text-2);margin-top:6px;line-height:1.5">${desc}</p>
    </div>`;
  }).join('');

  // dominant trait
  const dom=TRAIT_ORDER.reduce((a,b)=>pcts[a]>pcts[b]?a:b);
  const domInfo=TRAIT_INFO[dom];

  document.getElementById('b5-results').innerHTML=`
  <div style="text-align:center;margin-bottom:24px">
    <h2 style="font-size:1.4rem;font-weight:800">${_t('b5_profile',"Your Personality Profile")}</h2>
    <p style="color:var(--text-2);font-size:.9rem;margin-top:6px">${_t('b5_dominant',"Dominant trait:")} <strong style="color:${domInfo.color}">${domInfo.name}</strong></p>
  </div>
  <div class="trait-bars">${bars}</div>
  <canvas id="b5-radar" style="max-width:320px;width:100%;display:block;margin:24px auto"></canvas>
  <div class="share-row" style="margin-top:8px">
    <button class="share-btn" id="share-copy" onclick="B5Test.copy()">📋 Copy Result</button>
    <button class="share-btn" onclick="B5Test.tweet()">𝕏 Share on X</button>
  </div>
  <div style="text-align:center;margin-top:20px"><button class="btn btn-secondary" onclick="B5Test.reset()">↺ Retake</button></div>`;
  document.getElementById('b5-results').classList.add('show');
  window._b5Result={pcts, dom:domInfo.name};

  // animate bars
  setTimeout(()=>{
    document.querySelectorAll('.trait-bar-fill').forEach(b=>{
      const w=b.style.width; b.style.width='0';
      setTimeout(()=>{b.style.transition='width 1s cubic-bezier(.4,0,.2,1)';b.style.width=w;},50);
    });
    drawRadar();
  },100);
}

function drawRadar(){
  const canvas=document.getElementById('b5-radar');
  if(!canvas||!window._b5Result) return;
  const {pcts}=window._b5Result;
  const size=320; canvas.width=size*window.devicePixelRatio; canvas.height=size*window.devicePixelRatio;
  const ctx=canvas.getContext('2d'); ctx.scale(window.devicePixelRatio,window.devicePixelRatio);
  const cx=size/2, cy=size/2, r=size*0.38;
  const traits=TRAIT_ORDER;
  const angles=traits.map((_,i)=>(-Math.PI/2)+(2*Math.PI*i/traits.length));
  const isDark=document.documentElement.getAttribute('data-theme')==='dark';
  const gridC=isDark?'rgba(255,255,255,.08)':'rgba(0,0,0,.08)';
  const textC=isDark?'rgba(255,255,255,.5)':'rgba(0,0,0,.45)';

  // grid
  [.25,.5,.75,1].forEach(f=>{
    ctx.beginPath(); ctx.strokeStyle=gridC; ctx.lineWidth=1;
    angles.forEach((a,i)=>{ const x=cx+Math.cos(a)*r*f, y=cy+Math.sin(a)*r*f; i===0?ctx.moveTo(x,y):ctx.lineTo(x,y); });
    ctx.closePath(); ctx.stroke();
  });
  // spokes
  angles.forEach(a=>{ ctx.beginPath(); ctx.strokeStyle=gridC; ctx.moveTo(cx,cy); ctx.lineTo(cx+Math.cos(a)*r, cy+Math.sin(a)*r); ctx.stroke(); });

  // data
  ctx.beginPath(); ctx.fillStyle='rgba(99,102,241,.18)'; ctx.strokeStyle='#6366f1'; ctx.lineWidth=2;
  angles.forEach((a,i)=>{
    const val=pcts[traits[i]]/100;
    const x=cx+Math.cos(a)*r*val, y=cy+Math.sin(a)*r*val;
    i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);
  });
  ctx.closePath(); ctx.fill(); ctx.stroke();

  // points
  angles.forEach((a,i)=>{
    const val=pcts[traits[i]]/100, x=cx+Math.cos(a)*r*val, y=cy+Math.sin(a)*r*val;
    ctx.beginPath(); ctx.fillStyle=TRAIT_INFO[traits[i]].color; ctx.arc(x,y,5,0,Math.PI*2); ctx.fill();
  });

  // labels
  ctx.fillStyle=textC; ctx.font=`bold ${11*window.devicePixelRatio/window.devicePixelRatio}px Inter, sans-serif`; ctx.textAlign='center';
  angles.forEach((a,i)=>{
    const lx=cx+Math.cos(a)*(r+22), ly=cy+Math.sin(a)*(r+22)+4;
    ctx.fillText(TRAIT_INFO[traits[i]].name.slice(0,3),lx,ly);
  });
}

window.B5Test={
  start(){current=0;answers={};renderQ();},
  answer(val){
    answers[current]=val;
    // flash selected
    document.querySelectorAll('.likert-btn').forEach((b,i)=>{ if(i===val-1) b.classList.add('selected'); });
    setTimeout(()=>{
      current++;
      if(current>=ITEMS.length) showResults();
      else renderQ();
    },280);
  },
  reset(){answers={};current=0;renderShell();},
  copy(){
    const r=window._b5Result;if(!r)return;
    const txt=TRAIT_ORDER.map(t=>`${TRAIT_INFO[t].name.slice(0,3)}:${r.pcts[t]}%`).join(' | ');
    navigator.clipboard?.writeText(`Big Five: ${txt} 🪄 Test yours: coreskillai.com`);
  },
  tweet(){
    const r=window._b5Result;if(!r)return;
    const txt=`My Big Five: Dominant trait is ${r.dom}. ${TRAIT_ORDER.map(t=>`${t}:${r.pcts[t]}%`).join(' ')} 🪄`;
    window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(txt)}&url=${encodeURIComponent(location.href)}`,'_blank','noopener');
  }
};
document.addEventListener('DOMContentLoaded',renderShell);
})();
