/* CoreSkillAI — Emotional Intelligence Test (4-Branch Model) */
(function(){
function _t(k,fb){return window.I18n?.t(k)||fb||k;}
// 28 questions across 4 branches of Mayer-Salovey-Caruso EI model
// English master list. Translations live in ITEMS_I18N below; a market with
// no entry falls back to English. Note this is a FALLBACK, not a feature:
// a personality item a reader cannot understand produces a meaningless answer.
const ITEMS_EN=[
  // Branch 1: Perceiving Emotions (7 items)
  ["I can tell how someone is feeling just by looking at their face.","P",false],
  ["I notice when friends are upset even when they don't say so.","P",false],
  ["I find it hard to read the emotional tone in a room.","P",true],
  ["I can usually tell what kind of mood someone is in from their voice.","P",false],
  ["I often miss subtle emotional cues in conversations.","P",true],
  ["I'm good at understanding what people are feeling through their body language.","P",false],
  ["I can accurately identify emotions in art, music, or stories.","P",false],
  // Branch 2: Using Emotions (7 items)
  ["When I'm in a good mood, I tend to come up with more creative ideas.","U",false],
  ["I use my feelings to help me decide what to focus on.","U",false],
  ["I find it hard to use my emotions to motivate myself.","U",true],
  ["My emotions help me think more clearly about complex problems.","U",false],
  ["I struggle to let positive emotions energize my work.","U",true],
  ["I match my emotional state to the task I need to do (e.g., calm for precision work).","U",false],
  ["I can channel excitement or enthusiasm to boost my performance.","U",false],
  // Branch 3: Understanding Emotions (7 items)
  ["I understand how emotions tend to progress over time (e.g., annoyance → anger).","N",false],
  ["I can explain why a complex emotion like jealousy arises.","N",false],
  ["I find it hard to explain what causes mixed emotions in people.","N",true],
  ["I understand how emotions like pride and shame relate to self-image.","N",false],
  ["I often don't understand why people feel the way they do.","N",true],
  ["I can accurately label subtle distinctions between emotions (e.g., uneasy vs. anxious).","N",false],
  ["I understand how background emotions (like mild worry) affect thinking over time.","N",false],
  // Branch 4: Managing Emotions (7 items)
  ["When I'm upset, I can calm myself down relatively quickly.","M",false],
  ["I know how to lift someone else's mood when they're sad.","M",false],
  ["I tend to ruminate and stay stuck in bad moods.","M",true],
  ["I can stay composed and think clearly even under pressure.","M",false],
  ["I have trouble helping others manage their negative emotions.","M",true],
  ["I can resolve conflicts in a way that satisfies all parties.","M",false],
  ["I feel overwhelmed by strong negative emotions and can't manage them well.","M",true],
];

const ITEMS_I18N = {
  de: [
    "Ich erkenne an einem Gesicht, wie sich jemand fühlt.",
    "Ich merke, wenn Freunde bedrückt sind, auch wenn sie nichts sagen.",
    "Es fällt mir schwer, die Stimmung in einem Raum zu erfassen.",
    "An der Stimme höre ich meist, in welcher Stimmung jemand ist.",
    "Feine emotionale Signale im Gespräch entgehen mir oft.",
    "Ich lese Gefühle gut an der Körpersprache ab.",
    "Ich erkenne Gefühle in Kunst, Musik oder Geschichten treffsicher.",
    "Bei guter Laune habe ich mehr kreative Einfälle.",
    "Ich nutze meine Gefühle, um zu entscheiden, worauf ich mich konzentriere.",
    "Es fällt mir schwer, mich über meine Gefühle zu motivieren.",
    "Meine Gefühle helfen mir, komplexe Probleme klarer zu durchdenken.",
    "Ich schaffe es kaum, positive Gefühle in Arbeitsenergie umzusetzen.",
    "Ich stimme meine Stimmung auf die Aufgabe ab, etwa Ruhe für Präzisionsarbeit.",
    "Ich kann Begeisterung gezielt in Leistung umsetzen.",
    "Ich verstehe, wie Gefühle sich mit der Zeit entwickeln, etwa von Ärger zu Wut.",
    "Ich kann erklären, warum ein komplexes Gefühl wie Eifersucht entsteht.",
    "Es fällt mir schwer zu erklären, wodurch gemischte Gefühle entstehen.",
    "Ich verstehe, wie Stolz und Scham mit dem Selbstbild zusammenhängen.",
    "Oft verstehe ich nicht, warum Menschen so fühlen, wie sie fühlen.",
    "Ich benenne feine Unterschiede zwischen Gefühlen genau, etwa unruhig und ängstlich.",
    "Ich verstehe, wie leise Hintergrundgefühle wie Sorge das Denken mit der Zeit beeinflussen.",
    "Wenn ich aufgewühlt bin, beruhige ich mich recht schnell.",
    "Ich weiß, wie ich jemanden aufheitere, der traurig ist.",
    "Ich grüble und bleibe in schlechter Stimmung hängen.",
    "Auch unter Druck bleibe ich gefasst und denke klar.",
    "Es fällt mir schwer, anderen mit ihren negativen Gefühlen zu helfen.",
    "Ich löse Konflikte so, dass alle Beteiligten zufrieden sind.",
    "Starke negative Gefühle überwältigen mich und ich komme schlecht damit zurecht.",
  ],
  es: [
    "Sé cómo se siente alguien con solo mirarle la cara.",
    "Noto cuando un amigo está mal aunque no lo diga.",
    "Me cuesta captar el clima emocional de una sala.",
    "Por la voz suelo saber de qué humor está alguien.",
    "A menudo se me escapan las señales emocionales sutiles en una conversación.",
    "Se me da bien entender lo que sienten los demás por su lenguaje corporal.",
    "Identifico con precisión las emociones en el arte, la música o los relatos.",
    "Cuando estoy de buen humor se me ocurren más ideas creativas.",
    "Uso mis emociones para decidir en qué centrarme.",
    "Me cuesta usar mis emociones para motivarme.",
    "Mis emociones me ayudan a pensar con más claridad en problemas complejos.",
    "Me cuesta convertir las emociones positivas en energía para trabajar.",
    "Ajusto mi estado de ánimo a la tarea, por ejemplo calma para un trabajo de precisión.",
    "Sé canalizar el entusiasmo para rendir más.",
    "Entiendo cómo evolucionan las emociones con el tiempo, por ejemplo del fastidio a la ira.",
    "Sé explicar por qué surge una emoción compleja como los celos.",
    "Me cuesta explicar qué provoca las emociones mezcladas.",
    "Entiendo cómo el orgullo y la vergüenza se relacionan con la imagen de uno mismo.",
    "A menudo no entiendo por qué la gente siente lo que siente.",
    "Distingo con precisión matices entre emociones, por ejemplo inquietud y ansiedad.",
    "Entiendo cómo las emociones de fondo, como una preocupación leve, afectan al pensamiento con el tiempo.",
    "Cuando me altero, me calmo con bastante rapidez.",
    "Sé cómo animar a alguien que está triste.",
    "Tiendo a darle vueltas y quedarme atrapado en el mal humor.",
    "Mantengo la calma y pienso con claridad incluso bajo presión.",
    "Me cuesta ayudar a otros a manejar sus emociones negativas.",
    "Resuelvo conflictos de forma que todas las partes queden satisfechas.",
    "Las emociones negativas intensas me desbordan y no las gestiono bien.",
  ],
  fr: [
    "Je devine ce que quelqu'un ressent rien qu'en regardant son visage.",
    "Je remarque qu'un ami ne va pas bien même s'il ne dit rien.",
    "J'ai du mal à saisir l'ambiance émotionnelle d'une pièce.",
    "À la voix, je devine généralement l'humeur de quelqu'un.",
    "Les signaux émotionnels discrets m'échappent souvent dans une conversation.",
    "Je comprends bien ce que ressentent les gens à leur langage corporel.",
    "J'identifie précisément les émotions dans l'art, la musique ou les récits.",
    "Quand je suis de bonne humeur, j'ai davantage d'idées créatives.",
    "J'utilise mes émotions pour décider sur quoi me concentrer.",
    "J'ai du mal à me servir de mes émotions pour me motiver.",
    "Mes émotions m'aident à réfléchir plus clairement à des problèmes complexes.",
    "J'ai du mal à transformer les émotions positives en énergie de travail.",
    "J'ajuste mon état d'esprit à la tâche, par exemple le calme pour un travail de précision.",
    "Je sais canaliser l'enthousiasme pour améliorer mes performances.",
    "Je comprends comment les émotions évoluent, par exemple de l'agacement à la colère.",
    "Je sais expliquer pourquoi naît une émotion complexe comme la jalousie.",
    "J'ai du mal à expliquer ce qui provoque des émotions mêlées.",
    "Je comprends comment la fierté et la honte se rattachent à l'image de soi.",
    "Souvent je ne comprends pas pourquoi les gens ressentent ce qu'ils ressentent.",
    "Je nomme précisément des nuances entre émotions, par exemple inquiétude et anxiété.",
    "Je comprends comment des émotions de fond, comme une légère inquiétude, influencent la pensée à la longue.",
    "Quand je suis contrarié, je me calme assez vite.",
    "Je sais remonter le moral de quelqu'un qui est triste.",
    "J'ai tendance à ruminer et à rester bloqué dans une mauvaise humeur.",
    "Je reste posé et lucide même sous pression.",
    "J'ai du mal à aider les autres à gérer leurs émotions négatives.",
    "Je résous les conflits d'une manière qui satisfait toutes les parties.",
    "Les émotions négatives fortes me submergent et je les gère mal.",
  ],
  pt: [
    "Percebo como alguém está se sentindo só de olhar para o rosto.",
    "Noto quando um amigo está mal mesmo que não diga nada.",
    "Tenho dificuldade em captar o clima emocional de um ambiente.",
    "Pela voz geralmente sei em que humor a pessoa está.",
    "Muitas vezes deixo passar sinais emocionais sutis numa conversa.",
    "Sou bom em entender o que as pessoas sentem pela linguagem corporal.",
    "Identifico com precisão emoções em arte, música ou histórias.",
    "Quando estou de bom humor, tenho mais ideias criativas.",
    "Uso minhas emoções para decidir no que me concentrar.",
    "Tenho dificuldade em usar minhas emoções para me motivar.",
    "Minhas emoções me ajudam a pensar com mais clareza em problemas complexos.",
    "Tenho dificuldade em transformar emoções positivas em energia para o trabalho.",
    "Ajusto meu estado emocional à tarefa, por exemplo calma para trabalho de precisão.",
    "Consigo canalizar entusiasmo para render mais.",
    "Entendo como as emoções evoluem com o tempo, por exemplo do incômodo à raiva.",
    "Sei explicar por que surge uma emoção complexa como o ciúme.",
    "Tenho dificuldade em explicar o que causa emoções misturadas.",
    "Entendo como orgulho e vergonha se ligam à autoimagem.",
    "Muitas vezes não entendo por que as pessoas sentem o que sentem.",
    "Nomeio com precisão diferenças sutis entre emoções, por exemplo inquietação e ansiedade.",
    "Entendo como emoções de fundo, como uma preocupação leve, afetam o pensamento ao longo do tempo.",
    "Quando fico abalado, me acalmo relativamente rápido.",
    "Sei como animar alguém que está triste.",
    "Costumo ruminar e ficar preso no mau humor.",
    "Mantenho a calma e penso com clareza mesmo sob pressão.",
    "Tenho dificuldade em ajudar os outros a lidar com emoções negativas.",
    "Resolvo conflitos de um jeito que satisfaz todas as partes.",
    "Emoções negativas fortes me dominam e não consigo lidar bem com elas.",
  ],
  it: [
    "Capisco come si sente qualcuno solo guardandolo in faccia.",
    "Mi accorgo quando un amico sta male anche se non lo dice.",
    "Faccio fatica a cogliere il clima emotivo di una stanza.",
    "Dalla voce di solito capisco di che umore è una persona.",
    "Spesso mi sfuggono i segnali emotivi sottili in una conversazione.",
    "Sono bravo a capire cosa provano le persone dal linguaggio del corpo.",
    "Riconosco con precisione le emozioni nell'arte, nella musica o nei racconti.",
    "Quando sono di buon umore mi vengono più idee creative.",
    "Uso le mie emozioni per decidere su cosa concentrarmi.",
    "Faccio fatica a usare le emozioni per motivarmi.",
    "Le mie emozioni mi aiutano a ragionare più lucidamente su problemi complessi.",
    "Faccio fatica a trasformare le emozioni positive in energia per il lavoro.",
    "Adatto il mio stato d'animo al compito, per esempio la calma per un lavoro di precisione.",
    "So incanalare l'entusiasmo per rendere di più.",
    "Capisco come le emozioni evolvono nel tempo, per esempio dal fastidio alla rabbia.",
    "So spiegare perché nasce un'emozione complessa come la gelosia.",
    "Faccio fatica a spiegare cosa provoca le emozioni miste.",
    "Capisco come orgoglio e vergogna si legano all'immagine di sé.",
    "Spesso non capisco perché le persone provino quello che provano.",
    "Distinguo con precisione sfumature tra emozioni, per esempio inquietudine e ansia.",
    "Capisco come le emozioni di fondo, come una lieve preoccupazione, influenzino il pensiero nel tempo.",
    "Quando sono turbato mi calmo abbastanza in fretta.",
    "So come tirare su di morale chi è triste.",
    "Tendo a rimuginare e a restare bloccato nel malumore.",
    "Resto composto e lucido anche sotto pressione.",
    "Faccio fatica ad aiutare gli altri a gestire le emozioni negative.",
    "Risolvo i conflitti in modo che tutte le parti siano soddisfatte.",
    "Le emozioni negative forti mi travolgono e non riesco a gestirle bene.",
  ],
  nl: [
    "Ik zie aan iemands gezicht hoe die zich voelt.",
    "Ik merk het als vrienden ergens mee zitten, ook als ze niets zeggen.",
    "Ik heb moeite de emotionele sfeer in een ruimte aan te voelen.",
    "Aan iemands stem hoor ik meestal in wat voor bui die is.",
    "Subtiele emotionele signalen in een gesprek ontgaan me vaak.",
    "Ik lees goed af aan lichaamstaal wat mensen voelen.",
    "Ik herken emoties nauwkeurig in kunst, muziek of verhalen.",
    "Als ik goedgehumeurd ben, krijg ik meer creatieve invallen.",
    "Ik gebruik mijn gevoelens om te bepalen waar ik me op richt.",
    "Ik vind het lastig mijn emoties in te zetten om mezelf te motiveren.",
    "Mijn emoties helpen me helderder na te denken over complexe problemen.",
    "Ik krijg positieve emoties moeilijk omgezet in werkenergie.",
    "Ik stem mijn stemming af op de taak, bijvoorbeeld rust bij precisiewerk.",
    "Ik kan enthousiasme gericht inzetten om beter te presteren.",
    "Ik begrijp hoe emoties zich in de tijd ontwikkelen, bijvoorbeeld van ergernis naar woede.",
    "Ik kan uitleggen waarom een complexe emotie als jaloezie ontstaat.",
    "Ik vind het lastig uit te leggen waardoor gemengde gevoelens ontstaan.",
    "Ik begrijp hoe trots en schaamte samenhangen met het zelfbeeld.",
    "Vaak snap ik niet waarom mensen voelen wat ze voelen.",
    "Ik benoem subtiele verschillen tussen emoties nauwkeurig, bijvoorbeeld onrust en angst.",
    "Ik begrijp hoe achtergrondgevoelens, zoals lichte zorg, het denken op termijn kleuren.",
    "Als ik van slag ben, kalmeer ik vrij snel.",
    "Ik weet iemand op te beuren die verdrietig is.",
    "Ik blijf malen en blijf hangen in een slecht humeur.",
    "Ik blijf kalm en denk helder, ook onder druk.",
    "Ik vind het lastig anderen te helpen met hun negatieve emoties.",
    "Ik los conflicten op zodat alle partijen tevreden zijn.",
    "Sterke negatieve emoties overspoelen me en ik krijg er weinig grip op.",
  ],
  pl: [
    "Poznaję po twarzy, jak ktoś się czuje.",
    "Zauważam, że przyjaciel ma gorszy dzień, nawet gdy nic nie mówi.",
    "Trudno mi wyczuć emocjonalny nastrój w pomieszczeniu.",
    "Po głosie zwykle poznaję, w jakim ktoś jest nastroju.",
    "Często umykają mi subtelne sygnały emocjonalne w rozmowie.",
    "Dobrze odczytuję uczucia z mowy ciała.",
    "Trafnie rozpoznaję emocje w sztuce, muzyce czy opowieściach.",
    "W dobrym nastroju mam więcej twórczych pomysłów.",
    "Wykorzystuję emocje, by zdecydować, na czym się skupić.",
    "Trudno mi wykorzystać emocje do zmotywowania siebie.",
    "Emocje pomagają mi jaśniej myśleć o złożonych problemach.",
    "Z trudem zamieniam pozytywne emocje w energię do pracy.",
    "Dopasowuję nastrój do zadania, na przykład spokój przy pracy wymagającej precyzji.",
    "Potrafię ukierunkować entuzjazm, żeby lepiej działać.",
    "Rozumiem, jak emocje zmieniają się w czasie, na przykład od irytacji do gniewu.",
    "Umiem wyjaśnić, dlaczego pojawia się złożona emocja jak zazdrość.",
    "Trudno mi wyjaśnić, skąd biorą się mieszane uczucia.",
    "Rozumiem, jak duma i wstyd wiążą się z obrazem siebie.",
    "Często nie rozumiem, dlaczego ludzie czują to, co czują.",
    "Trafnie nazywam subtelne różnice między emocjami, na przykład niepokój i lęk.",
    "Rozumiem, jak tło emocjonalne, choćby lekki niepokój, wpływa z czasem na myślenie.",
    "Gdy się zdenerwuję, dość szybko się uspokajam.",
    "Wiem, jak poprawić komuś nastrój, gdy jest smutny.",
    "Mam skłonność do rozpamiętywania i tkwienia w złym nastroju.",
    "Zachowuję spokój i jasność myślenia nawet pod presją.",
    "Trudno mi pomagać innym radzić sobie z negatywnymi emocjami.",
    "Rozwiązuję konflikty tak, by wszystkie strony były zadowolone.",
    "Silne negatywne emocje mnie przytłaczają i słabo sobie z nimi radzę.",
  ],
  ru: [
    "Я понимаю по лицу, что человек чувствует.",
    "Я замечаю, когда другу плохо, даже если он молчит.",
    "Мне трудно уловить эмоциональную атмосферу в помещении.",
    "По голосу я обычно понимаю, в каком человек настроении.",
    "В разговоре я часто упускаю тонкие эмоциональные сигналы.",
    "Я хорошо считываю чувства по языку тела.",
    "Я точно распознаю эмоции в искусстве, музыке и историях.",
    "В хорошем настроении у меня появляется больше творческих идей.",
    "Я опираюсь на чувства, решая, на чём сосредоточиться.",
    "Мне трудно использовать эмоции, чтобы себя мотивировать.",
    "Эмоции помогают мне яснее думать над сложными задачами.",
    "Мне сложно превращать хорошее настроение в рабочую энергию.",
    "Я подстраиваю настроение под задачу, например спокойствие для точной работы.",
    "Я умею направлять воодушевление на результат.",
    "Я понимаю, как чувства развиваются со временем, например от досады к гневу.",
    "Я могу объяснить, почему возникает сложное чувство вроде ревности.",
    "Мне трудно объяснить, откуда берутся смешанные чувства.",
    "Я понимаю, как гордость и стыд связаны с образом себя.",
    "Часто я не понимаю, почему люди чувствуют то, что чувствуют.",
    "Я точно называю тонкие различия между чувствами, например беспокойство и тревогу.",
    "Я понимаю, как фоновые чувства, например лёгкая тревога, со временем влияют на мышление.",
    "Расстроившись, я довольно быстро успокаиваюсь.",
    "Я знаю, как поднять настроение тому, кому грустно.",
    "Я склонен прокручивать мысли и застревать в плохом настроении.",
    "Я сохраняю собранность и ясность даже под давлением.",
    "Мне трудно помогать другим справляться с тяжёлыми чувствами.",
    "Я разрешаю конфликты так, чтобы все стороны остались довольны.",
    "Сильные тяжёлые чувства захлёстывают меня, и я плохо с ними справляюсь.",
  ],
  tr: [
    "Birinin yüzüne bakarak nasıl hissettiğini anlarım.",
    "Arkadaşlarımın keyfi kaçtığında söylemeseler bile fark ederim.",
    "Bir ortamın duygusal havasını okumakta zorlanırım.",
    "Ses tonundan genellikle birinin ruh halini anlarım.",
    "Sohbetlerde ince duygusal ipuçlarını sıkça kaçırırım.",
    "İnsanların ne hissettiğini beden dilinden iyi anlarım.",
    "Sanatta, müzikte ya da hikâyelerde duyguları isabetle tanırım.",
    "Keyfim yerindeyken daha çok yaratıcı fikir üretirim.",
    "Neye odaklanacağıma karar verirken duygularımdan yararlanırım.",
    "Kendimi motive etmek için duygularımı kullanmakta zorlanırım.",
    "Duygularım karmaşık sorunları daha net düşünmeme yardım eder.",
    "Olumlu duyguları işe enerji olarak aktarmakta zorlanırım.",
    "Ruh halimi göreve göre ayarlarım, örneğin hassas iş için sakinlik.",
    "Heyecanı performansa dönüştürmeyi bilirim.",
    "Duyguların zamanla nasıl geliştiğini anlarım, örneğin sıkıntıdan öfkeye.",
    "Kıskançlık gibi karmaşık bir duygunun neden doğduğunu açıklayabilirim.",
    "Karışık duyguların nedenini açıklamakta zorlanırım.",
    "Gurur ve utancın benlik algısıyla nasıl ilişkilendiğini anlarım.",
    "İnsanların neden öyle hissettiğini çoğu zaman anlamam.",
    "Duygular arasındaki ince farkları doğru adlandırırım, örneğin huzursuzluk ile kaygı.",
    "Hafif bir tedirginlik gibi arka plan duygularının düşünceyi zamanla nasıl etkilediğini anlarım.",
    "Üzüldüğümde kendimi nispeten çabuk sakinleştiririm.",
    "Üzgün birinin moralini nasıl düzelteceğimi bilirim.",
    "Sürekli düşünüp kötü ruh halinde takılı kalırım.",
    "Baskı altında bile sakin kalır, net düşünürüm.",
    "Başkalarının olumsuz duygularıyla baş etmesine yardım etmekte zorlanırım.",
    "Çatışmaları tüm tarafları memnun edecek biçimde çözerim.",
    "Güçlü olumsuz duygular beni aşar ve onları iyi yönetemem.",
  ],
  ro: [
    "Îmi dau seama cum se simte cineva doar privindu-l în față.",
    "Observ când un prieten e supărat chiar dacă nu spune nimic.",
    "Îmi vine greu să citesc atmosfera emoțională dintr-o încăpere.",
    "După voce îmi dau seama de obicei în ce dispoziție e cineva.",
    "Adesea îmi scapă semnalele emoționale subtile dintr-o conversație.",
    "Mă pricep să înțeleg ce simt oamenii din limbajul corpului.",
    "Identific cu precizie emoțiile în artă, muzică sau povești.",
    "Când sunt bine dispus îmi vin mai multe idei creative.",
    "Îmi folosesc emoțiile ca să decid pe ce să mă concentrez.",
    "Îmi vine greu să-mi folosesc emoțiile ca să mă motivez.",
    "Emoțiile mă ajută să gândesc mai limpede la probleme complexe.",
    "Cu greu transform emoțiile pozitive în energie de lucru.",
    "Îmi potrivesc starea cu sarcina, de exemplu calmul pentru munca de precizie.",
    "Știu să canalizez entuziasmul ca să randez mai bine.",
    "Înțeleg cum evoluează emoțiile în timp, de exemplu de la agasare la furie.",
    "Pot explica de ce apare o emoție complexă precum gelozia.",
    "Îmi vine greu să explic ce provoacă emoțiile amestecate.",
    "Înțeleg cum se leagă mândria și rușinea de imaginea de sine.",
    "Adesea nu înțeleg de ce oamenii simt ceea ce simt.",
    "Numesc precis diferențe fine între emoții, de exemplu neliniște și anxietate.",
    "Înțeleg cum emoțiile de fond, precum o îngrijorare ușoară, influențează gândirea în timp.",
    "Când mă tulbur, mă calmez relativ repede.",
    "Știu cum să înveselesc pe cineva care e trist.",
    "Am tendința să rumeg și să rămân blocat în dispoziții proaste.",
    "Rămân calm și gândesc limpede chiar și sub presiune.",
    "Îmi vine greu să-i ajut pe alții să-și gestioneze emoțiile negative.",
    "Rezolv conflictele astfel încât toate părțile să fie mulțumite.",
    "Emoțiile negative puternice mă copleșesc și nu le gestionez bine.",
  ],
  sv: [
    "Jag ser på ansiktet hur någon mår.",
    "Jag märker när vänner mår dåligt även om de inget säger.",
    "Jag har svårt att läsa av stämningen i ett rum.",
    "På rösten hör jag oftast vilket humör någon är på.",
    "Jag missar ofta subtila känslosignaler i samtal.",
    "Jag är bra på att förstå vad folk känner via kroppsspråk.",
    "Jag känner träffsäkert igen känslor i konst, musik eller berättelser.",
    "När jag är på gott humör får jag fler kreativa idéer.",
    "Jag använder mina känslor för att avgöra vad jag ska fokusera på.",
    "Jag har svårt att använda känslor för att motivera mig.",
    "Mina känslor hjälper mig tänka klarare kring svåra problem.",
    "Jag har svårt att omsätta positiva känslor i arbetsenergi.",
    "Jag anpassar sinnesstämningen till uppgiften, till exempel lugn vid precisionsarbete.",
    "Jag kan kanalisera entusiasm för att prestera bättre.",
    "Jag förstår hur känslor utvecklas över tid, till exempel från irritation till ilska.",
    "Jag kan förklara varför en sammansatt känsla som svartsjuka uppstår.",
    "Jag har svårt att förklara vad som orsakar blandade känslor.",
    "Jag förstår hur stolthet och skam hänger ihop med självbilden.",
    "Ofta förstår jag inte varför människor känner som de gör.",
    "Jag sätter exakta ord på små skillnader mellan känslor, till exempel oro och ångest.",
    "Jag förstår hur bakgrundskänslor, som lätt oro, påverkar tänkandet över tid.",
    "När jag blir upprörd lugnar jag ner mig ganska snabbt.",
    "Jag vet hur jag muntrar upp någon som är ledsen.",
    "Jag tenderar att grubbla och fastna i dåligt humör.",
    "Jag håller mig samlad och tänker klart även under press.",
    "Jag har svårt att hjälpa andra hantera sina negativa känslor.",
    "Jag löser konflikter så att alla parter blir nöjda.",
    "Starka negativa känslor överväldigar mig och jag hanterar dem dåligt.",
  ],
  da: [
    "Jeg kan se på et ansigt, hvordan nogen har det.",
    "Jeg mærker, når venner har det skidt, selv om de intet siger.",
    "Jeg har svært ved at aflæse stemningen i et rum.",
    "På stemmen hører jeg som regel, hvilket humør nogen er i.",
    "Jeg overser ofte fine følelsesmæssige signaler i samtaler.",
    "Jeg er god til at forstå følelser gennem kropssprog.",
    "Jeg genkender præcist følelser i kunst, musik eller fortællinger.",
    "Når jeg er i godt humør, får jeg flere kreative idéer.",
    "Jeg bruger mine følelser til at afgøre, hvad jeg skal fokusere på.",
    "Jeg har svært ved at bruge følelser til at motivere mig selv.",
    "Mine følelser hjælper mig med at tænke klarere om komplekse problemer.",
    "Jeg har svært ved at omsætte positive følelser til arbejdsenergi.",
    "Jeg tilpasser mit humør til opgaven, for eksempel ro til præcisionsarbejde.",
    "Jeg kan kanalisere begejstring til bedre præstation.",
    "Jeg forstår, hvordan følelser udvikler sig over tid, for eksempel fra irritation til vrede.",
    "Jeg kan forklare, hvorfor en sammensat følelse som jalousi opstår.",
    "Jeg har svært ved at forklare, hvad der udløser blandede følelser.",
    "Jeg forstår, hvordan stolthed og skam hænger sammen med selvbilledet.",
    "Ofte forstår jeg ikke, hvorfor folk føler, som de gør.",
    "Jeg sætter præcise ord på små forskelle mellem følelser, for eksempel uro og angst.",
    "Jeg forstår, hvordan baggrundsfølelser som let bekymring påvirker tænkningen over tid.",
    "Når jeg bliver oprevet, falder jeg forholdsvis hurtigt til ro.",
    "Jeg ved, hvordan jeg opmuntrer en, der er ked af det.",
    "Jeg har tendens til at gruble og sidde fast i dårligt humør.",
    "Jeg bevarer roen og tænker klart selv under pres.",
    "Jeg har svært ved at hjælpe andre med deres negative følelser.",
    "Jeg løser konflikter, så alle parter er tilfredse.",
    "Stærke negative følelser overvælder mig, og jeg håndterer dem dårligt.",
  ],
  no: [
    "Jeg ser på ansiktet hvordan noen har det.",
    "Jeg merker når venner har det vondt selv om de ikke sier noe.",
    "Jeg har vansker med å lese stemningen i et rom.",
    "På stemmen hører jeg som regel hvilket humør noen er i.",
    "Jeg går ofte glipp av fine følelsesmessige signaler i samtaler.",
    "Jeg er god til å forstå følelser gjennom kroppsspråk.",
    "Jeg gjenkjenner presist følelser i kunst, musikk eller fortellinger.",
    "Når jeg er i godt humør får jeg flere kreative ideer.",
    "Jeg bruker følelsene mine til å avgjøre hva jeg skal fokusere på.",
    "Jeg har vansker med å bruke følelser til å motivere meg selv.",
    "Følelsene mine hjelper meg å tenke klarere om sammensatte problemer.",
    "Jeg klarer sjelden å gjøre positive følelser om til arbeidsenergi.",
    "Jeg tilpasser humøret til oppgaven, for eksempel ro til presisjonsarbeid.",
    "Jeg kan kanalisere entusiasme til bedre prestasjon.",
    "Jeg forstår hvordan følelser utvikler seg over tid, for eksempel fra irritasjon til sinne.",
    "Jeg kan forklare hvorfor en sammensatt følelse som sjalusi oppstår.",
    "Jeg har vansker med å forklare hva som utløser blandede følelser.",
    "Jeg forstår hvordan stolthet og skam henger sammen med selvbildet.",
    "Ofte forstår jeg ikke hvorfor folk føler som de gjør.",
    "Jeg setter presise ord på små forskjeller mellom følelser, for eksempel uro og angst.",
    "Jeg forstår hvordan bakgrunnsfølelser som lett bekymring påvirker tenkningen over tid.",
    "Når jeg blir opprørt roer jeg meg forholdsvis raskt.",
    "Jeg vet hvordan jeg muntrer opp noen som er lei seg.",
    "Jeg har lett for å gruble og bli sittende fast i dårlig humør.",
    "Jeg holder hodet kaldt og tenker klart selv under press.",
    "Jeg har vansker med å hjelpe andre med negative følelser.",
    "Jeg løser konflikter slik at alle parter blir fornøyde.",
    "Sterke negative følelser overvelder meg og jeg håndterer dem dårlig.",
  ],
  fi: [
    "Näen kasvoista, miltä jostakusta tuntuu.",
    "Huomaan kun ystävällä on paha olo, vaikka hän ei sano mitään.",
    "Minun on vaikea aistia tilan tunnelmaa.",
    "Äänestä kuulen yleensä, millä tuulella joku on.",
    "Hienovaraiset tunnevihjeet menevät keskustelussa usein ohi.",
    "Osaan lukea tunteita hyvin kehonkielestä.",
    "Tunnistan tarkasti tunteita taiteessa, musiikissa ja tarinoissa.",
    "Hyvällä tuulella saan enemmän luovia ideoita.",
    "Käytän tunteitani päättääkseni, mihin keskityn.",
    "Minun on vaikea käyttää tunteita itseni motivointiin.",
    "Tunteeni auttavat minua ajattelemaan selkeämmin monimutkaisia ongelmia.",
    "Minun on vaikea muuttaa myönteisiä tunteita työenergiaksi.",
    "Sovitan mielialani tehtävään, esimerkiksi rauhallisuuden tarkkuustyöhön.",
    "Osaan suunnata innostuksen suoritukseen.",
    "Ymmärrän miten tunteet kehittyvät ajan myötä, esimerkiksi ärtymyksestä vihaan.",
    "Osaan selittää, miksi monimutkainen tunne kuten mustasukkaisuus syntyy.",
    "Minun on vaikea selittää, mistä ristiriitaiset tunteet johtuvat.",
    "Ymmärrän miten ylpeys ja häpeä liittyvät minäkuvaan.",
    "Usein en ymmärrä, miksi ihmiset tuntevat niin kuin tuntevat.",
    "Nimeän tarkasti pieniä eroja tunteiden välillä, esimerkiksi levottomuuden ja ahdistuksen.",
    "Ymmärrän miten taustatunteet, kuten lievä huoli, vaikuttavat ajatteluun ajan myötä.",
    "Kun järkytyn, rauhoitun melko nopeasti.",
    "Tiedän miten piristää surullista ihmistä.",
    "Minulla on taipumus vatvoa ja jäädä jumiin huonoon mielialaan.",
    "Pysyn tyynenä ja ajattelen selkeästi myös paineen alla.",
    "Minun on vaikea auttaa muita käsittelemään kielteisiä tunteita.",
    "Ratkaisen ristiriidat niin, että kaikki osapuolet ovat tyytyväisiä.",
    "Voimakkaat kielteiset tunteet valtaavat minut enkä hallitse niitä hyvin.",
  ],
  id: [
    "Saya bisa tahu perasaan seseorang hanya dari wajahnya.",
    "Saya menyadari saat teman sedang tidak baik meski ia tidak mengatakannya.",
    "Saya sulit membaca suasana emosional dalam sebuah ruangan.",
    "Dari nada suara biasanya saya tahu suasana hati seseorang.",
    "Saya sering melewatkan isyarat emosi yang halus dalam percakapan.",
    "Saya pandai memahami perasaan orang melalui bahasa tubuh.",
    "Saya mengenali emosi dengan tepat dalam seni, musik, atau cerita.",
    "Saat suasana hati saya baik, ide kreatif lebih banyak muncul.",
    "Saya memakai perasaan untuk menentukan apa yang perlu difokuskan.",
    "Saya sulit memakai emosi untuk memotivasi diri sendiri.",
    "Emosi membantu saya berpikir lebih jernih tentang masalah rumit.",
    "Saya sulit mengubah emosi positif menjadi energi kerja.",
    "Saya menyesuaikan suasana hati dengan tugas, misalnya tenang untuk pekerjaan presisi.",
    "Saya bisa menyalurkan antusiasme untuk meningkatkan hasil kerja.",
    "Saya paham bagaimana emosi berkembang seiring waktu, misalnya dari jengkel menjadi marah.",
    "Saya bisa menjelaskan mengapa emosi rumit seperti cemburu muncul.",
    "Saya sulit menjelaskan penyebab perasaan yang bercampur aduk.",
    "Saya paham bagaimana rasa bangga dan malu berkaitan dengan citra diri.",
    "Sering saya tidak paham mengapa orang merasakan apa yang mereka rasakan.",
    "Saya bisa menamai perbedaan halus antaremosi, misalnya gelisah dan cemas.",
    "Saya paham bagaimana emosi latar, seperti kekhawatiran ringan, memengaruhi pikiran dari waktu ke waktu.",
    "Saat kesal, saya bisa menenangkan diri relatif cepat.",
    "Saya tahu cara menghibur orang yang sedang sedih.",
    "Saya cenderung terus memikirkan dan terjebak dalam suasana hati buruk.",
    "Saya tetap tenang dan berpikir jernih bahkan di bawah tekanan.",
    "Saya sulit membantu orang lain mengelola emosi negatif mereka.",
    "Saya menyelesaikan konflik sehingga semua pihak merasa puas.",
    "Emosi negatif yang kuat membuat saya kewalahan dan sulit dikelola.",
  ],
  uk: [
    "Я одразу помічаю, коли мій настрій змінюється.",
    "Я можу точно назвати почуття, яке переживаю.",
    "Я розумію, що саме викликало мою емоцію.",
    "Я помічаю напругу в тілі раніше, ніж усвідомлюю тривогу.",
    "Я усвідомлюю, як мій настрій впливає на мої рішення.",
    "Я знаю свої сильні та слабкі сторони.",
    "Я розрізняю схожі почуття, як-от роздратування та злість.",
    "Я з виразу обличчя розумію, що людина засмучена.",
    "Я вловлюю зміну тону голосу співрозмовника.",
    "Я помічаю, коли комусь незручно в розмові.",
    "Я відчуваю настрій у групі людей.",
    "Я розумію, коли слова людини не збігаються з її почуттями.",
    "Я помічаю, коли друг приховує тривогу.",
    "Я вловлюю невисловлену напругу між людьми.",
    "Я зберігаю спокій, коли мене критикують.",
    "Я вмію заспокоїтися, коли злюся.",
    "Я не дозволяю поганому настрою зіпсувати весь день.",
    "Я думаю, перш ніж відповісти в конфлікті.",
    "Я справляюся з розчаруванням, не зриваючись на інших.",
    "Я відновлююся після невдачі досить швидко.",
    "Я витримую тиск, не втрачаючи ясності думки.",
    "Я використовую своє піднесення, щоб братися за складне.",
    "Я можу налаштувати себе на потрібний лад перед важливою справою.",
    "Я знаходжу слова, щоб підтримати людину.",
    "Я підлаштовую спосіб спілкування під співрозмовника.",
    "Я вмію розрядити напружену ситуацію.",
    "Я враховую почуття інших, ухвалюючи рішення.",
    "Я допомагаю людям поглянути на проблему інакше.",
  ],
  bg: [
    "Забелязвам веднага, когато настроението ми се промени.",
    "Мога да назова точно чувството, което изпитвам.",
    "Разбирам какво точно е предизвикало емоцията ми.",
    "Усещам напрежението в тялото си, преди да осъзная тревогата.",
    "Осъзнавам как настроението ми влияе върху решенията ми.",
    "Познавам силните и слабите си страни.",
    "Различавам сходни чувства като раздразнение и гняв.",
    "По изражението на лицето разбирам, че някой е разстроен.",
    "Долавям промяната в тона на гласа на събеседника.",
    "Забелязвам, когато на някого му е неудобно в разговор.",
    "Усещам настроението в група хора.",
    "Разбирам, когато думите на човек не съвпадат с чувствата му.",
    "Забелязвам, когато приятел крие тревогата си.",
    "Долавям неизказаното напрежение между хората.",
    "Запазвам спокойствие, когато ме критикуват.",
    "Умея да се успокоя, когато съм ядосан.",
    "Не позволявам на лошото настроение да провали целия ден.",
    "Помислям, преди да отговоря в конфликт.",
    "Справям се с разочарованието, без да си го изкарвам на другите.",
    "Възстановявам се доста бързо след неуспех.",
    "Издържам на напрежение, без да губя яснота на мисълта.",
    "Използвам приповдигнатото си настроение, за да се захвана с трудното.",
    "Мога да се настроя подходящо преди важна задача.",
    "Намирам думи, за да подкрепя някого.",
    "Приспособявам начина си на общуване към събеседника.",
    "Умея да разведря напрегната ситуация.",
    "Съобразявам се с чувствата на другите, когато взимам решения.",
    "Помагам на хората да погледнат на проблема по друг начин.",
  ],
  sr: [
    "Одмах приметим када ми се расположење промени.",
    "Могу тачно да именујем осећање које доживљавам.",
    "Разумем шта је тачно изазвало моју емоцију.",
    "Осетим напетост у телу пре него што освестим стрепњу.",
    "Свестан сам како моје расположење утиче на моје одлуке.",
    "Знам своје јаке и слабе стране.",
    "Разликујем слична осећања попут раздражености и беса.",
    "По изразу лица препознам да је неко узнемирен.",
    "Ухватим промену у тону саговорниковог гласа.",
    "Приметим када је некоме непријатно у разговору.",
    "Осетим расположење у групи људи.",
    "Разумем када се нечије речи не поклапају с осећањима.",
    "Приметим када пријатељ крије стрепњу.",
    "Осетим неизречену напетост међу људима.",
    "Остајем смирен када ме критикују.",
    "Умем да се смирим када сам љут.",
    "Не дозвољавам да лоше расположење упропасти цео дан.",
    "Размислим пре него што одговорим у сукобу.",
    "Носим се с разочарањем без искаљивања на друге.",
    "Прилично брзо се опоравим после неуспеха.",
    "Издржим притисак не губећи бистрину мисли.",
    "Користим свој занос да се прихватим тешког посла.",
    "Могу да се наштимујем како треба пред важан задатак.",
    "Налазим речи да некога подржим.",
    "Прилагођавам начин општења саговорнику.",
    "Умем да разбијем напету ситуацију.",
    "Узимам у обзир туђа осећања када доносим одлуке.",
    "Помажем људима да проблем сагледају другачије.",
  ],
  mk: [
    "Веднаш забележувам кога ќе ми се смени расположението.",
    "Можам точно да го именувам чувството што го доживувам.",
    "Разбирам што точно ја предизвикало мојата емоција.",
    "Ја чувствувам напнатоста во телото пред да ја освестам стравливоста.",
    "Свесен сум како расположението влијае на моите одлуки.",
    "Ги знам своите силни и слаби страни.",
    "Разликувам слични чувства како раздразнетост и гнев.",
    "По изразот на лицето препознавам дека некој е вознемирен.",
    "Ја фаќам промената во тонот на гласот на соговорникот.",
    "Забележувам кога на некој му е непријатно во разговор.",
    "Го чувствувам расположението во група луѓе.",
    "Разбирам кога зборовите на човекот не се совпаѓаат со неговите чувства.",
    "Забележувам кога пријател ја крие грижата.",
    "Ја чувствувам неискажаната напнатост меѓу луѓето.",
    "Останувам смирен кога ме критикуваат.",
    "Умеам да се смирам кога сум лут.",
    "Не дозволувам лошото расположение да го расипе целиот ден.",
    "Размислувам пред да одговорам во конфликт.",
    "Се справувам со разочарувањето без да се истурам врз другите.",
    "Прилично брзо се опоравувам по неуспех.",
    "Издржувам притисок без да ја губам бистрината на мислата.",
    "Го користам своето воодушевување за да се фатам со тешкото.",
    "Можам да се наштимам како треба пред важна задача.",
    "Наоѓам зборови за да поддржам некого.",
    "Го прилагодувам начинот на општење кон соговорникот.",
    "Умеам да разбијам напната ситуација.",
    "Ги земам предвид туѓите чувства кога носам одлуки.",
    "Им помагам на луѓето да го видат проблемот поинаку.",
  ],
  el: [
    "Αντιλαμβάνομαι αμέσως όταν αλλάζει η διάθεσή μου.",
    "Μπορώ να ονομάσω με ακρίβεια το συναίσθημα που βιώνω.",
    "Καταλαβαίνω τι ακριβώς προκάλεσε το συναίσθημά μου.",
    "Νιώθω την ένταση στο σώμα πριν συνειδητοποιήσω το άγχος.",
    "Έχω επίγνωση του πώς η διάθεσή μου επηρεάζει τις αποφάσεις μου.",
    "Γνωρίζω τα δυνατά και τα αδύνατα σημεία μου.",
    "Ξεχωρίζω παρόμοια συναισθήματα όπως ο εκνευρισμός και ο θυμός.",
    "Από την έκφραση του προσώπου καταλαβαίνω ότι κάποιος είναι αναστατωμένος.",
    "Πιάνω την αλλαγή στον τόνο της φωνής του συνομιλητή.",
    "Παρατηρώ όταν κάποιος νιώθει άβολα σε μια συζήτηση.",
    "Αισθάνομαι τη διάθεση μέσα σε μια ομάδα ανθρώπων.",
    "Καταλαβαίνω όταν τα λόγια κάποιου δεν συμφωνούν με τα συναισθήματά του.",
    "Παρατηρώ όταν ένας φίλος κρύβει την ανησυχία του.",
    "Πιάνω την ανείπωτη ένταση ανάμεσα σε ανθρώπους.",
    "Παραμένω ήρεμος όταν με κριτικάρουν.",
    "Ξέρω να ηρεμώ όταν θυμώνω.",
    "Δεν αφήνω μια κακή διάθεση να χαλάσει όλη τη μέρα.",
    "Σκέφτομαι πριν απαντήσω σε μια σύγκρουση.",
    "Αντιμετωπίζω την απογοήτευση χωρίς να τα βάζω με τους άλλους.",
    "Συνέρχομαι αρκετά γρήγορα μετά από μια αποτυχία.",
    "Αντέχω την πίεση χωρίς να χάνω τη διαύγειά μου.",
    "Αξιοποιώ τον ενθουσιασμό μου για να καταπιαστώ με τα δύσκολα.",
    "Μπορώ να συντονιστώ κατάλληλα πριν από μια σημαντική δουλειά.",
    "Βρίσκω τα λόγια για να στηρίξω κάποιον.",
    "Προσαρμόζω τον τρόπο επικοινωνίας μου στον συνομιλητή.",
    "Ξέρω να εκτονώνω μια τεταμένη κατάσταση.",
    "Λαμβάνω υπόψη τα συναισθήματα των άλλων όταν παίρνω αποφάσεις.",
    "Βοηθάω τους ανθρώπους να δουν ένα πρόβλημα διαφορετικά.",
  ],
  cs: [
    "Okamžitě si všimnu, když se mi změní nálada.",
    "Dokážu přesně pojmenovat pocit, který prožívám.",
    "Chápu, co přesně vyvolalo mou emoci.",
    "Napětí v těle vnímám dřív, než si uvědomím úzkost.",
    "Uvědomuji si, jak moje nálada ovlivňuje má rozhodnutí.",
    "Znám své silné i slabé stránky.",
    "Rozlišuji podobné pocity, jako je podráždění a hněv.",
    "Z výrazu tváře poznám, že je někdo rozrušený.",
    "Zachytím změnu v tónu hlasu druhého.",
    "Všimnu si, když je někomu v rozhovoru nepříjemně.",
    "Vnímám náladu ve skupině lidí.",
    "Poznám, když se něčí slova neshodují s jeho pocity.",
    "Všimnu si, když přítel skrývá obavy.",
    "Zachytím nevyslovené napětí mezi lidmi.",
    "Zůstávám klidný, když mě kritizují.",
    "Umím se uklidnit, když se zlobím.",
    "Nedovolím, aby špatná nálada zkazila celý den.",
    "V konfliktu si rozmyslím, než odpovím.",
    "Se zklamáním se vyrovnávám, aniž bych si to vybíjel na druhých.",
    "Po neúspěchu se poměrně rychle vzpamatuji.",
    "Vydržím tlak, aniž bych ztrácel jasnou hlavu.",
    "Své nadšení využívám k tomu, abych se pustil do těžkého.",
    "Před důležitým úkolem se dokážu správně naladit.",
    "Najdu slova, kterými někoho podpořím.",
    "Způsob komunikace přizpůsobuji druhému člověku.",
    "Umím uvolnit napjatou situaci.",
    "Při rozhodování beru v úvahu pocity druhých.",
    "Pomáhám lidem podívat se na problém jinak.",
  ],
  hr: [
    "Odmah primijetim kad mi se raspoloženje promijeni.",
    "Mogu točno imenovati osjećaj koji proživljavam.",
    "Razumijem što je točno izazvalo moju emociju.",
    "Napetost u tijelu osjetim prije nego što osvijestim tjeskobu.",
    "Svjestan sam kako moje raspoloženje utječe na moje odluke.",
    "Znam svoje jake i slabe strane.",
    "Razlikujem slične osjećaje poput razdraženosti i bijesa.",
    "Po izrazu lica prepoznam da je netko uznemiren.",
    "Uhvatim promjenu u tonu sugovornikova glasa.",
    "Primijetim kad je nekome neugodno u razgovoru.",
    "Osjetim raspoloženje u skupini ljudi.",
    "Razumijem kad se nečije riječi ne poklapaju s osjećajima.",
    "Primijetim kad prijatelj skriva zabrinutost.",
    "Osjetim neizrečenu napetost među ljudima.",
    "Ostajem smiren kad me kritiziraju.",
    "Znam se smiriti kad sam ljut.",
    "Ne dopuštam da loše raspoloženje pokvari cijeli dan.",
    "U sukobu razmislim prije nego što odgovorim.",
    "S razočaranjem se nosim bez iskaljivanja na drugima.",
    "Nakon neuspjeha se prilično brzo oporavim.",
    "Izdržim pritisak ne gubeći bistrinu misli.",
    "Svoj zanos koristim da se prihvatim teškoga.",
    "Prije važnog se zadatka znam prikladno ugoditi.",
    "Nalazim riječi kojima nekoga podržim.",
    "Način komunikacije prilagođavam sugovorniku.",
    "Znam razbiti napetu situaciju.",
    "Pri odlučivanju uzimam u obzir tuđe osjećaje.",
    "Pomažem ljudima da problem sagledaju drukčije.",
  ],
  sk: [
    "Okamžite si všimnem, keď sa mi zmení nálada.",
    "Dokážem presne pomenovať pocit, ktorý prežívam.",
    "Chápem, čo presne vyvolalo moju emóciu.",
    "Napätie v tele vnímam skôr, než si uvedomím úzkosť.",
    "Uvedomujem si, ako moja nálada ovplyvňuje moje rozhodnutia.",
    "Poznám svoje silné aj slabé stránky.",
    "Rozlišujem podobné pocity, ako je podráždenie a hnev.",
    "Z výrazu tváre spoznám, že je niekto rozrušený.",
    "Zachytím zmenu v tóne hlasu druhého.",
    "Všimnem si, keď je niekomu v rozhovore nepríjemne.",
    "Vnímam náladu v skupine ľudí.",
    "Spoznám, keď sa niečie slová nezhodujú s jeho pocitmi.",
    "Všimnem si, keď priateľ skrýva obavy.",
    "Zachytím nevyslovené napätie medzi ľuďmi.",
    "Zostávam pokojný, keď ma kritizujú.",
    "Viem sa upokojiť, keď sa hnevám.",
    "Nedovolím, aby zlá nálada pokazila celý deň.",
    "V konflikte si rozmyslím, než odpoviem.",
    "So sklamaním sa vyrovnávam bez toho, aby som si to vybíjal na druhých.",
    "Po neúspechu sa pomerne rýchlo spamätám.",
    "Vydržím tlak bez toho, aby som strácal jasnú hlavu.",
    "Svoje nadšenie využívam na to, aby som sa pustil do ťažkého.",
    "Pred dôležitou úlohou sa dokážem správne naladiť.",
    "Nájdem slová, ktorými niekoho podporím.",
    "Spôsob komunikácie prispôsobujem druhému človeku.",
    "Viem uvoľniť napätú situáciu.",
    "Pri rozhodovaní beriem do úvahy pocity druhých.",
    "Pomáham ľuďom pozrieť sa na problém inak.",
  ],
  sl: [
    "Takoj opazim, kadar se mi spremeni razpoloženje.",
    "Občutek, ki ga doživljam, znam natančno poimenovati.",
    "Razumem, kaj natanko je sprožilo moje čustvo.",
    "Napetost v telesu zaznam prej, kot se zavem tesnobe.",
    "Zavedam se, kako moje razpoloženje vpliva na moje odločitve.",
    "Poznam svoje močne in šibke plati.",
    "Razlikujem podobne občutke, kot sta razdraženost in jeza.",
    "Po izrazu obraza prepoznam, da je nekdo vznemirjen.",
    "Ujamem spremembo v tonu sogovornikovega glasu.",
    "Opazim, kadar je komu v pogovoru neprijetno.",
    "Zaznam razpoloženje v skupini ljudi.",
    "Razumem, kadar se besede nekoga ne ujemajo z njegovimi občutki.",
    "Opazim, kadar prijatelj skriva skrb.",
    "Ujamem neizrečeno napetost med ljudmi.",
    "Ostanem miren, kadar me kritizirajo.",
    "Znam se pomiriti, kadar sem jezen.",
    "Ne dovolim, da bi slabo razpoloženje pokvarilo ves dan.",
    "V sporu premislim, preden odgovorim.",
    "Z razočaranjem se spopadam, ne da bi ga stresal na druge.",
    "Po neuspehu si opomorem razmeroma hitro.",
    "Vzdržim pritisk, ne da bi izgubil bistrost misli.",
    "Svoje navdušenje uporabim, da se lotim težkega.",
    "Pred pomembno nalogo se znam ustrezno uglasiti.",
    "Najdem besede, s katerimi koga podprem.",
    "Način sporazumevanja prilagodim sogovorniku.",
    "Znam razbremeniti napet položaj.",
    "Pri odločanju upoštevam občutke drugih.",
    "Ljudem pomagam, da na težavo pogledajo drugače.",
  ],
  hu: [
    "Azonnal észreveszem, ha megváltozik a hangulatom.",
    "Pontosan meg tudom nevezni, milyen érzést élek át.",
    "Értem, mi pontosan váltotta ki az érzelmemet.",
    "A testi feszültséget hamarabb érzékelem, mint ahogy tudatosul bennem a szorongás.",
    "Tudatában vagyok, hogyan hat a hangulatom a döntéseimre.",
    "Ismerem az erősségeimet és a gyengeségeimet.",
    "Megkülönböztetem a hasonló érzéseket, például az ingerültséget és a haragot.",
    "Az arckifejezésből felismerem, ha valaki fel van dúlva.",
    "Elkapom a beszélgetőtárs hangszínének változását.",
    "Észreveszem, ha valaki kényelmetlenül érzi magát egy beszélgetésben.",
    "Megérzem a hangulatot egy embercsoportban.",
    "Felismerem, ha valakinek a szavai nem egyeznek az érzéseivel.",
    "Észreveszem, ha egy barátom elrejti az aggodalmát.",
    "Megérzem a ki nem mondott feszültséget emberek között.",
    "Nyugodt maradok, amikor bírálnak.",
    "Meg tudom nyugtatni magam, amikor mérges vagyok.",
    "Nem hagyom, hogy egy rossz hangulat elrontsa az egész napot.",
    "Konfliktusban gondolkodom, mielőtt válaszolnék.",
    "A csalódást úgy kezelem, hogy nem másokon vezetem le.",
    "Kudarc után viszonylag gyorsan összeszedem magam.",
    "Nyomás alatt is megőrzöm a tiszta gondolkodást.",
    "A lelkesedésemet arra használom, hogy nekilássak a nehéznek.",
    "Fontos feladat előtt megfelelően rá tudok hangolódni.",
    "Megtalálom a szavakat, amelyekkel támogathatok valakit.",
    "A kommunikációm módját a beszélgetőtárshoz igazítom.",
    "Fel tudom oldani a feszült helyzetet.",
    "Döntéskor figyelembe veszem mások érzéseit.",
    "Segítek az embereknek másképp látni egy problémát.",
  ],
  lt: [
    "Iškart pastebiu, kai pasikeičia mano nuotaika.",
    "Galiu tiksliai įvardyti jausmą, kurį išgyvenu.",
    "Suprantu, kas būtent sukėlė mano emociją.",
    "Įtampą kūne pajuntu anksčiau, nei suvokiu nerimą.",
    "Suvokiu, kaip mano nuotaika veikia mano sprendimus.",
    "Žinau savo stiprybes ir silpnybes.",
    "Skiriu panašius jausmus, tokius kaip suerzinimas ir pyktis.",
    "Iš veido išraiškos suprantu, kad žmogus nusiminęs.",
    "Pagaunu pašnekovo balso tono pokytį.",
    "Pastebiu, kai kam nors pokalbyje nejauku.",
    "Pajuntu nuotaiką žmonių grupėje.",
    "Suprantu, kai žmogaus žodžiai nesutampa su jo jausmais.",
    "Pastebiu, kai draugas slepia nerimą.",
    "Pagaunu neišsakytą įtampą tarp žmonių.",
    "Išlieku ramus, kai mane kritikuoja.",
    "Moku nusiraminti, kai pykstu.",
    "Neleidžiu blogai nuotaikai sugadinti visos dienos.",
    "Konflikte pagalvoju prieš atsakydamas.",
    "Su nusivylimu susitvarkau neišliedamas jo ant kitų.",
    "Po nesėkmės atsigaunu gana greitai.",
    "Ištveriu spaudimą neprarasdamas minties aiškumo.",
    "Savo pakilimą panaudoju imdamasis sunkių dalykų.",
    "Prieš svarbią užduotį moku tinkamai nusiteikti.",
    "Randu žodžių ką nors palaikyti.",
    "Bendravimo būdą pritaikau pašnekovui.",
    "Moku išsklaidyti įtemptą situaciją.",
    "Priimdamas sprendimus atsižvelgiu į kitų jausmus.",
    "Padedu žmonėms pažvelgti į problemą kitaip.",
  ],
  lv: [
    "Uzreiz pamanu, kad mainās mans garastāvoklis.",
    "Varu precīzi nosaukt sajūtu, ko pārdzīvoju.",
    "Saprotu, kas tieši izraisīja manu emociju.",
    "Sasprindzinājumu ķermenī sajūtu agrāk, nekā apzinos trauksmi.",
    "Apzinos, kā mans garastāvoklis ietekmē manus lēmumus.",
    "Zinu savas stiprās un vājās puses.",
    "Atšķiru līdzīgas jūtas, piemēram, aizkaitinājumu un dusmas.",
    "Pēc sejas izteiksmes saprotu, ka kāds ir satraukts.",
    "Uztveru sarunbiedra balss toņa maiņu.",
    "Pamanu, kad kādam sarunā ir neērti.",
    "Sajūtu noskaņu cilvēku grupā.",
    "Saprotu, kad cilvēka vārdi nesakrīt ar viņa jūtām.",
    "Pamanu, kad draugs slēpj satraukumu.",
    "Uztveru neizteikto spriedzi starp cilvēkiem.",
    "Saglabāju mieru, kad mani kritizē.",
    "Protu nomierināties, kad esmu dusmīgs.",
    "Neļauju sliktam garastāvoklim sabojāt visu dienu.",
    "Konfliktā apdomāju, pirms atbildu.",
    "Ar vilšanos tieku galā, neizgāžot to uz citiem.",
    "Pēc neveiksmes atgūstos diezgan ātri.",
    "Izturu spiedienu, nezaudējot domas skaidrību.",
    "Savu pacēlumu izmantoju, lai ķertos pie grūtā.",
    "Pirms svarīga uzdevuma protu pareizi noskaņoties.",
    "Atrodu vārdus, ar kuriem kādu atbalstīt.",
    "Saskarsmes veidu pielāgoju sarunbiedram.",
    "Protu atslābināt saspringtu situāciju.",
    "Pieņemot lēmumus, ņemu vērā citu jūtas.",
    "Palīdzu cilvēkiem paraudzīties uz problēmu citādi.",
  ],
  et: [
    "Märkan kohe, kui mu meeleolu muutub.",
    "Oskan täpselt nimetada tunnet, mida kogen.",
    "Mõistan, mis täpselt mu emotsiooni esile kutsus.",
    "Tunnen pinget kehas varem, kui teadvustan ärevust.",
    "Olen teadlik, kuidas mu meeleolu mõjutab mu otsuseid.",
    "Tean oma tugevaid ja nõrku külgi.",
    "Eristan sarnaseid tundeid nagu ärritus ja viha.",
    "Näoilmest saan aru, et keegi on endast väljas.",
    "Taban vestluskaaslase hääletooni muutust.",
    "Märkan, kui kellelgi on vestluses ebamugav.",
    "Tunnetan meeleolu inimeste rühmas.",
    "Saan aru, kui kellegi sõnad ei lange kokku tema tunnetega.",
    "Märkan, kui sõber varjab muret.",
    "Taban väljaütlemata pinget inimeste vahel.",
    "Jään rahulikuks, kui mind kritiseeritakse.",
    "Oskan end rahustada, kui olen vihane.",
    "Ei lase halval tujul kogu päeva rikkuda.",
    "Konfliktis mõtlen enne vastamist.",
    "Tulen pettumusega toime ilma seda teiste peal välja elamata.",
    "Ebaõnnestumisest taastun üsna kiiresti.",
    "Talun survet, kaotamata mõtteselgust.",
    "Kasutan oma indu, et raskete asjadega pihta hakata.",
    "Enne tähtsat ülesannet oskan end õigesti häälestada.",
    "Leian sõnu, millega kedagi toetada.",
    "Kohandan suhtlusviisi vestluskaaslasele.",
    "Oskan pingelist olukorda leevendada.",
    "Otsustamisel arvestan teiste tunnetega.",
    "Aitan inimestel probleemi teisiti näha.",
  ],
  ar: [
    "ألاحظ فورًا حين يتغيّر مزاجي.",
    "أستطيع تسمية الشعور الذي أمرّ به بدقة.",
    "أفهم ما الذي أثار انفعالي تحديدًا.",
    "أشعر بالتوتر في جسدي قبل أن أدرك القلق.",
    "أدرك كيف يؤثر مزاجي في قراراتي.",
    "أعرف نقاط قوتي وضعفي.",
    "أميّز بين مشاعر متقاربة مثل الانزعاج والغضب.",
    "أعرف من تعابير الوجه أن أحدهم متضايق.",
    "ألتقط تغيّر نبرة صوت محدّثي.",
    "ألاحظ حين يشعر أحدهم بعدم الارتياح في حديث.",
    "أستشعر المزاج السائد في مجموعة.",
    "أدرك حين لا تتطابق كلمات أحدهم مع مشاعره.",
    "ألاحظ حين يخفي صديق قلقه.",
    "ألتقط التوتر غير المعلن بين الناس.",
    "أبقى هادئًا حين أُنتقد.",
    "أعرف كيف أهدّئ نفسي حين أغضب.",
    "لا أدع مزاجًا سيئًا يفسد يومي كله.",
    "أفكّر قبل أن أردّ في خلاف.",
    "أتعامل مع خيبة الأمل دون أن أصبّها على غيري.",
    "أتعافى بعد الإخفاق بسرعة معقولة.",
    "أتحمّل الضغط دون أن أفقد صفاء تفكيري.",
    "أستثمر حماسي في الإقدام على المهام الصعبة.",
    "أستطيع تهيئة نفسي قبل مهمة مهمة.",
    "أجد الكلمات المناسبة لأساند أحدهم.",
    "أكيّف أسلوب حديثي بحسب من أخاطبه.",
    "أعرف كيف أنزع فتيل موقف متوتر.",
    "أراعي مشاعر الآخرين حين أتخذ قرارًا.",
    "أساعد الناس على رؤية المشكلة من زاوية أخرى.",
  ],
  he: [
    "אני מבחין מיד כשמצב הרוח שלי משתנה.",
    "אני יכול לתת שם מדויק לתחושה שאני חווה.",
    "אני מבין מה בדיוק עורר את הרגש שלי.",
    "אני חש את המתח בגוף לפני שאני מודע לחרדה.",
    "אני מודע לאופן שבו מצב הרוח שלי משפיע על החלטותיי.",
    "אני מכיר את החוזקות והחולשות שלי.",
    "אני מבחין בין תחושות דומות כמו עצבנות וכעס.",
    "מהבעת הפנים אני מבין שמישהו נסער.",
    "אני קולט שינוי בטון הדיבור של בן שיחי.",
    "אני מבחין כשלמישהו לא נוח בשיחה.",
    "אני חש את מצב הרוח בקבוצת אנשים.",
    "אני מבין כשמילים של מישהו אינן תואמות את רגשותיו.",
    "אני מבחין כשחבר מסתיר דאגה.",
    "אני קולט מתח לא מדובר בין אנשים.",
    "אני נשאר רגוע כשמבקרים אותי.",
    "אני יודע להירגע כשאני כועס.",
    "אני לא נותן למצב רוח רע לקלקל את כל היום.",
    "בעימות אני חושב לפני שאני עונה.",
    "אני מתמודד עם אכזבה בלי להוציא אותה על אחרים.",
    "אחרי כישלון אני מתאושש די מהר.",
    "אני עומד בלחץ בלי לאבד את בהירות המחשבה.",
    "אני מנצל את ההתלהבות שלי כדי לגשת למשימות קשות.",
    "לפני משימה חשובה אני יודע לכוון את עצמי כראוי.",
    "אני מוצא מילים לתמוך במישהו.",
    "אני מתאים את דרך התקשורת לבן שיחי.",
    "אני יודע לפוגג מצב מתוח.",
    "בקבלת החלטות אני מתחשב ברגשות של אחרים.",
    "אני עוזר לאנשים לראות בעיה מזווית אחרת.",
  ],
  fa: [
    "به‌محض دگرگونی حال و هوایم آن را درمی‌یابم.",
    "می‌توانم احساسی را که تجربه می‌کنم دقیق نام ببرم.",
    "می‌فهمم دقیقاً چه چیزی احساسم را برانگیخته است.",
    "پیش از آنکه اضطراب را دریابم، تنش را در بدنم حس می‌کنم.",
    "می‌دانم حال و هوایم چگونه بر تصمیم‌هایم اثر می‌گذارد.",
    "نقاط قوت و ضعف خود را می‌شناسم.",
    "احساس‌های نزدیک به هم مانند دلخوری و خشم را از هم بازمی‌شناسم.",
    "از حالت چهره درمی‌یابم کسی آشفته است.",
    "دگرگونی لحن صدای هم‌صحبتم را می‌گیرم.",
    "درمی‌یابم چه زمانی کسی در گفت‌وگو معذب است.",
    "حال و هوای یک گروه را حس می‌کنم.",
    "درمی‌یابم چه زمانی سخن کسی با احساسش همخوان نیست.",
    "درمی‌یابم چه زمانی دوستی نگرانی‌اش را پنهان می‌کند.",
    "تنش ناگفته میان آدم‌ها را حس می‌کنم.",
    "هنگام انتقاد آرام می‌مانم.",
    "می‌دانم چگونه خشمم را فرو بنشانم.",
    "نمی‌گذارم حال بد تمام روز را خراب کند.",
    "در کشمکش پیش از پاسخ می‌اندیشم.",
    "با ناکامی کنار می‌آیم بی‌آنکه سر دیگران خالی کنم.",
    "پس از شکست نسبتاً زود به حال می‌آیم.",
    "فشار را تاب می‌آورم بی‌آنکه روشنی اندیشه‌ام را از دست بدهم.",
    "شور خود را برای دست‌بردن به کارهای دشوار به کار می‌گیرم.",
    "پیش از کاری مهم می‌توانم خود را درست آماده کنم.",
    "واژه‌هایی می‌یابم تا کسی را دلگرم کنم.",
    "شیوهٔ گفت‌وگویم را با هم‌صحبتم سازگار می‌کنم.",
    "می‌دانم چگونه از تنش یک موقعیت بکاهم.",
    "در تصمیم‌گیری احساس دیگران را در نظر می‌گیرم.",
    "به مردم یاری می‌کنم مسئله را از زاویه‌ای دیگر ببینند.",
  ],
  hi: [
    "मेरा मिज़ाज बदलते ही मुझे तुरंत पता चल जाता है।",
    "जो भाव मैं महसूस करता हूँ उसे मैं सटीक नाम दे सकता हूँ।",
    "मैं समझ लेता हूँ कि मेरी भावना का कारण ठीक क्या था।",
    "चिंता का बोध होने से पहले ही मुझे शरीर में तनाव महसूस हो जाता है।",
    "मुझे पता रहता है कि मेरा मिज़ाज मेरे निर्णयों पर कैसे असर डालता है।",
    "मैं अपनी शक्तियों और कमज़ोरियों को जानता हूँ।",
    "मैं झुँझलाहट और क्रोध जैसे मिलते-जुलते भावों में अंतर कर लेता हूँ।",
    "चेहरे के भाव से मैं जान लेता हूँ कि कोई परेशान है।",
    "मैं सामने वाले की आवाज़ के लहजे का बदलाव पकड़ लेता हूँ।",
    "मैं भाँप लेता हूँ कि बातचीत में किसी को असहज लग रहा है।",
    "मैं लोगों के समूह का माहौल महसूस कर लेता हूँ।",
    "मैं समझ जाता हूँ कि किसी के शब्द उसकी भावनाओं से मेल नहीं खा रहे।",
    "मैं भाँप लेता हूँ कि कोई मित्र अपनी चिंता छिपा रहा है।",
    "लोगों के बीच अनकहा तनाव मैं पकड़ लेता हूँ।",
    "आलोचना होने पर भी मैं शांत रहता हूँ।",
    "ग़ुस्से में मैं ख़ुद को शांत करना जानता हूँ।",
    "मैं ख़राब मिज़ाज को पूरा दिन बिगाड़ने नहीं देता।",
    "टकराव में उत्तर देने से पहले मैं सोचता हूँ।",
    "निराशा को मैं दूसरों पर नहीं उतारता।",
    "असफलता के बाद मैं ठीक-ठाक जल्दी सँभल जाता हूँ।",
    "दबाव में भी मेरी सोच की स्पष्टता बनी रहती है।",
    "अपने उत्साह का उपयोग मैं कठिन काम शुरू करने में करता हूँ।",
    "महत्त्वपूर्ण काम से पहले मैं ख़ुद को सही ढंग से तैयार कर लेता हूँ।",
    "किसी को सँभालने के लिए मुझे उपयुक्त शब्द मिल जाते हैं।",
    "मैं अपनी बात कहने का ढंग सामने वाले के अनुसार बदल लेता हूँ।",
    "तनावपूर्ण स्थिति को हल्का करना मुझे आता है।",
    "निर्णय लेते समय मैं दूसरों की भावनाओं का ध्यान रखता हूँ।",
    "मैं लोगों को समस्या दूसरे कोण से देखने में मदद करता हूँ।",
  ],
  ja: [
    "気分が変わったことにすぐ気づく。",
    "今感じている気持ちを的確に言葉にできる。",
    "その感情が何によって起きたのか分かる。",
    "不安だと自覚する前に、体のこわばりに気づく。",
    "自分の気分が判断にどう影響するか分かっている。",
    "自分の得意なことと苦手なことを知っている。",
    "苛立ちと怒りのような近い感情を区別できる。",
    "表情から相手が動揺していると分かる。",
    "相手の声の調子の変化に気づく。",
    "会話の中で相手が居心地悪そうにしていると気づく。",
    "その場の空気を感じ取れる。",
    "言葉と本当の気持ちが食い違っていると分かる。",
    "友人が心配ごとを隠していると気づく。",
    "人のあいだの言葉にならない緊張を感じ取れる。",
    "批判されても落ち着いていられる。",
    "腹が立ったとき自分を静める方法を知っている。",
    "嫌な気分を一日じゅう引きずらない。",
    "もめごとでは答える前に一呼吸おく。",
    "落胆しても人に当たらずに済ませられる。",
    "失敗してもわりあい早く立ち直る。",
    "重圧の中でも考えを見失わない。",
    "気持ちの高ぶりを、難しい仕事に取りかかる力に変えられる。",
    "大事な仕事の前に気持ちを整えられる。",
    "人を支える言葉を見つけられる。",
    "相手に合わせて話し方を変えられる。",
    "張りつめた場をやわらげられる。",
    "決めるときに相手の気持ちを考えに入れる。",
    "問題を別の角度から見られるよう手助けできる。",
  ],
  vi: [
    "Tôi có thể nhận ra cảm xúc của ai đó chỉ bằng cách nhìn khuôn mặt họ.",
    "Tôi nhận ra khi bạn bè buồn ngay cả khi họ không nói ra.",
    "Tôi thấy khó đọc được bầu không khí cảm xúc trong một căn phòng.",
    "Tôi thường đoán được tâm trạng của ai đó qua giọng nói của họ.",
    "Tôi hay bỏ lỡ những tín hiệu cảm xúc tinh tế trong trò chuyện.",
    "Tôi giỏi hiểu cảm xúc của người khác qua ngôn ngữ cơ thể.",
    "Tôi có thể nhận diện chính xác cảm xúc trong nghệ thuật, âm nhạc hoặc câu chuyện.",
    "Khi tâm trạng tốt, tôi thường nghĩ ra nhiều ý tưởng sáng tạo hơn.",
    "Tôi dùng cảm xúc của mình để quyết định nên tập trung vào điều gì.",
    "Tôi thấy khó dùng cảm xúc để tạo động lực cho bản thân.",
    "Cảm xúc giúp tôi suy nghĩ rõ ràng hơn về những vấn đề phức tạp.",
    "Tôi chật vật để biến cảm xúc tích cực thành năng lượng cho công việc.",
    "Tôi điều chỉnh trạng thái cảm xúc cho phù hợp với nhiệm vụ, chẳng hạn giữ bình tĩnh khi làm việc đòi hỏi chính xác.",
    "Tôi có thể chuyển sự hào hứng thành động lực nâng cao hiệu suất.",
    "Tôi hiểu cảm xúc thường tiến triển thế nào theo thời gian, chẳng hạn từ khó chịu thành tức giận.",
    "Tôi có thể giải thích vì sao một cảm xúc phức tạp như ghen tị lại nảy sinh.",
    "Tôi thấy khó giải thích điều gì gây ra những cảm xúc lẫn lộn ở người khác.",
    "Tôi hiểu những cảm xúc như tự hào và xấu hổ liên quan thế nào đến hình ảnh bản thân.",
    "Tôi thường không hiểu vì sao người khác lại cảm thấy như vậy.",
    "Tôi có thể gọi tên chính xác những khác biệt tinh tế giữa các cảm xúc, như bất an và lo âu.",
    "Tôi hiểu những cảm xúc nền, như nỗi lo nhẹ, ảnh hưởng thế nào đến suy nghĩ theo thời gian.",
    "Khi buồn bực, tôi có thể trấn tĩnh lại tương đối nhanh.",
    "Tôi biết cách làm người khác vui lên khi họ buồn.",
    "Tôi hay nghiền ngẫm và mắc kẹt trong tâm trạng xấu.",
    "Tôi giữ được bình tĩnh và suy nghĩ sáng suốt ngay cả khi chịu áp lực.",
    "Tôi gặp khó khăn khi giúp người khác xử lý cảm xúc tiêu cực.",
    "Tôi có thể giải quyết xung đột theo cách làm hài lòng mọi bên.",
    "Tôi thấy choáng ngợp trước những cảm xúc tiêu cực mạnh và khó kiểm soát chúng.",
  ],
  ms: [
    "Saya boleh mengetahui perasaan seseorang hanya dengan melihat wajah mereka.",
    "Saya perasan apabila rakan saya bersedih walaupun mereka tidak memberitahunya.",
    "Saya sukar membaca nada emosi dalam sesebuah bilik.",
    "Saya biasanya dapat mengagak suasana hati seseorang daripada suaranya.",
    "Saya sering terlepas isyarat emosi yang halus dalam perbualan.",
    "Saya pandai memahami perasaan orang melalui bahasa badan mereka.",
    "Saya boleh mengenal pasti emosi dengan tepat dalam seni, muzik atau cerita.",
    "Apabila suasana hati saya baik, saya cenderung menghasilkan lebih banyak idea kreatif.",
    "Saya menggunakan perasaan saya untuk membantu memutuskan apa yang perlu difokuskan.",
    "Saya sukar menggunakan emosi saya untuk memotivasikan diri.",
    "Emosi saya membantu saya berfikir dengan lebih jelas tentang masalah yang rumit.",
    "Saya bergelut untuk membiarkan emosi positif menyuntik tenaga pada kerja saya.",
    "Saya menyesuaikan keadaan emosi saya dengan tugasan yang perlu dilakukan, contohnya tenang untuk kerja yang memerlukan ketepatan.",
    "Saya boleh menyalurkan keghairahan untuk meningkatkan prestasi saya.",
    "Saya faham bagaimana emosi berkembang mengikut masa, contohnya daripada rasa terganggu kepada kemarahan.",
    "Saya boleh menerangkan mengapa emosi rumit seperti cemburu timbul.",
    "Saya sukar menerangkan punca emosi bercampur pada orang lain.",
    "Saya faham bagaimana emosi seperti bangga dan malu berkait dengan imej diri.",
    "Saya selalunya tidak faham mengapa orang berasa seperti yang mereka rasakan.",
    "Saya boleh melabel perbezaan halus antara emosi dengan tepat, contohnya resah berbanding cemas.",
    "Saya faham bagaimana emosi latar seperti kerisauan ringan mempengaruhi pemikiran dari masa ke masa.",
    "Apabila saya kecewa, saya boleh menenangkan diri dengan agak cepat.",
    "Saya tahu cara menceriakan suasana hati orang lain ketika mereka bersedih.",
    "Saya cenderung merenung berulang kali dan terperangkap dalam suasana hati yang buruk.",
    "Saya kekal tenang dan berfikir dengan jelas walaupun di bawah tekanan.",
    "Saya menghadapi kesukaran membantu orang lain menguruskan emosi negatif mereka.",
    "Saya boleh menyelesaikan konflik dengan cara yang memuaskan semua pihak.",
    "Saya berasa terbeban oleh emosi negatif yang kuat dan sukar menguruskannya.",
  ],
  tl: [
    "Nasasabi ko ang nararamdaman ng isang tao sa pamamagitan lamang ng pagtingin sa mukha niya.",
    "Napapansin ko kapag malungkot ang mga kaibigan ko kahit hindi nila sinasabi.",
    "Nahihirapan akong basahin ang emosyonal na kapaligiran sa isang silid.",
    "Karaniwang nahuhulaan ko ang timpla ng isang tao sa tono ng kanyang boses.",
    "Madalas kong hindi napapansin ang mga banayad na senyas ng emosyon sa usapan.",
    "Magaling akong umunawa ng damdamin ng tao sa kilos ng kanyang katawan.",
    "Natutukoy ko nang tumpak ang emosyon sa sining, musika o kuwento.",
    "Kapag maganda ang timpla ko, mas maraming malikhaing ideya ang naiisip ko.",
    "Ginagamit ko ang aking damdamin para magpasya kung saan magpopokus.",
    "Nahihirapan akong gamitin ang emosyon ko para mag-udyok sa sarili.",
    "Nakakatulong ang emosyon ko para mas malinaw akong mag-isip tungkol sa mga kumplikadong problema.",
    "Nahihirapan akong hayaang magbigay-lakas ang positibong emosyon sa aking trabaho.",
    "Inaayon ko ang aking emosyonal na kalagayan sa gawaing kailangang tapusin, halimbawa kalmado para sa gawaing nangangailangan ng katumpakan.",
    "Nagagamit ko ang sabik na damdamin para mapabuti ang aking pagganap.",
    "Nauunawaan ko kung paano umuunlad ang emosyon sa paglipas ng panahon, halimbawa mula pagkainis tungo sa galit.",
    "Naipapaliwanag ko kung bakit lumilitaw ang kumplikadong emosyon tulad ng selos.",
    "Nahihirapan akong ipaliwanag kung ano ang nagdudulot ng halo-halong emosyon sa mga tao.",
    "Nauunawaan ko kung paano nauugnay ang emosyong tulad ng pagmamalaki at hiya sa pagtingin sa sarili.",
    "Madalas hindi ko maintindihan kung bakit ganoon ang nararamdaman ng mga tao.",
    "Natutukoy ko nang tumpak ang banayad na pagkakaiba ng emosyon, halimbawa pagkabalisa laban sa pag-aalala.",
    "Nauunawaan ko kung paano nakakaapekto sa pag-iisip ang mga nakatagong emosyon tulad ng bahagyang pag-aalala.",
    "Kapag nagagalit ako, mabilis akong nakakapagpakalma sa sarili.",
    "Alam ko kung paano pasayahin ang iba kapag malungkot sila.",
    "Madalas akong maglumagak sa isip at hindi makaalis sa masamang timpla.",
    "Nananatili akong kalmado at malinaw mag-isip kahit nasa ilalim ng pressure.",
    "Nahihirapan akong tumulong sa iba na pamahalaan ang kanilang negatibong emosyon.",
    "Nalulutas ko ang alitan sa paraang nakakabusog sa lahat ng panig.",
    "Nabibigatan ako sa matitinding negatibong emosyon at hindi ko ito magawang pamahalaan nang maayos.",
  ],
  af: [
    "Ek kan sien hoe iemand voel net deur na hul gesig te kyk.",
    "Ek merk op wanneer vriende ontsteld is selfs al sê hulle dit nie.",
    "Ek vind dit moeilik om die emosionele toon in 'n vertrek te lees.",
    "Ek kan gewoonlik aan iemand se stem hoor in watter bui hulle is.",
    "Ek mis dikwels subtiele emosionele leidrade in gesprekke.",
    "Ek is goed daarmee om mense se gevoelens uit hul lyftaal te verstaan.",
    "Ek kan emosies in kuns, musiek of stories akkuraat identifiseer.",
    "Wanneer ek in 'n goeie bui is, kom ek met meer kreatiewe idees vorendag.",
    "Ek gebruik my gevoelens om te besluit waarop om te fokus.",
    "Ek vind dit moeilik om my emosies te gebruik om myself te motiveer.",
    "My emosies help my om helderder oor komplekse probleme te dink.",
    "Ek sukkel om positiewe emosies my werk te laat energiseer.",
    "Ek pas my emosionele toestand aan by die taak wat ek moet doen, byvoorbeeld kalm vir presisiewerk.",
    "Ek kan opgewondenheid kanaliseer om my prestasie te verhoog.",
    "Ek verstaan hoe emosies met verloop van tyd ontwikkel, byvoorbeeld van ergernis na woede.",
    "Ek kan verduidelik waarom 'n komplekse emosie soos jaloesie ontstaan.",
    "Ek vind dit moeilik om te verduidelik wat gemengde emosies by mense veroorsaak.",
    "Ek verstaan hoe emosies soos trots en skaamte met selfbeeld verband hou.",
    "Ek verstaan dikwels nie waarom mense voel soos hulle voel nie.",
    "Ek kan subtiele verskille tussen emosies akkuraat benoem, byvoorbeeld ongemaklik teenoor angstig.",
    "Ek verstaan hoe agtergrondemosies soos ligte kommer denke oor tyd beïnvloed.",
    "Wanneer ek ontsteld is, kan ek myself redelik vinnig kalmeer.",
    "Ek weet hoe om iemand anders se bui op te tel wanneer hulle hartseer is.",
    "Ek is geneig om te herkou en in slegte buie vas te steek.",
    "Ek bly kalm en dink helder selfs onder druk.",
    "Ek sukkel om ander te help om hul negatiewe emosies te hanteer.",
    "Ek kan konflikte oplos op 'n manier wat alle partye tevrede stel.",
    "Ek voel oorweldig deur sterk negatiewe emosies en kan hulle nie goed hanteer nie.",
  ],
  sq: [
    "Mund ta kuptoj si ndihet dikush thjesht duke i parë fytyrën.",
    "E vërej kur miqtë janë të mërzitur edhe kur nuk e thonë.",
    "E kam të vështirë të lexoj tonin emocional në një dhomë.",
    "Zakonisht e kuptoj në çfarë humori është dikush nga zëri i tij.",
    "Shpesh më shpëtojnë shenjat e holla emocionale në biseda.",
    "Jam i mirë në kuptimin e ndjenjave të njerëzve përmes gjuhës së trupit.",
    "Mund t'i identifikoj saktë emocionet në art, muzikë ose tregime.",
    "Kur jam në humor të mirë, më vijnë më shumë ide krijuese.",
    "I përdor ndjenjat e mia për të vendosur ku të përqendrohem.",
    "E kam të vështirë t'i përdor emocionet për të motivuar veten.",
    "Emocionet e mia më ndihmojnë të mendoj më qartë për probleme komplekse.",
    "Mundohem t'i lë emocionet pozitive të energjizojnë punën time.",
    "E përshtat gjendjen time emocionale me detyrën që duhet të bëj, për shembull qetësi për punë që kërkon saktësi.",
    "Mund ta kanalizoj entuziazmin për të rritur performancën time.",
    "Kuptoj se si emocionet përparojnë me kohën, për shembull nga bezdia te zemërimi.",
    "Mund të shpjegoj pse lind një emocion kompleks si xhelozia.",
    "E kam të vështirë të shpjegoj çfarë shkakton emocione të përziera te njerëzit.",
    "Kuptoj se si emocionet si krenaria dhe turpi lidhen me imazhin e vetes.",
    "Shpesh nuk kuptoj pse njerëzit ndihen ashtu siç ndihen.",
    "Mund t'i emërtoj saktë dallimet e holla midis emocioneve, për shembull shqetësim kundrejt ankth.",
    "Kuptoj se si emocionet e sfondit, si shqetësimi i lehtë, ndikojnë në mendim me kalimin e kohës.",
    "Kur jam i mërzitur, mund ta qetësoj veten relativisht shpejt.",
    "Di si ta ngre humorin e dikujt tjetër kur është i trishtuar.",
    "Kam prirje të ripërtyp mendimet dhe të ngec në humor të keq.",
    "Qëndroj i qetë dhe mendoj qartë edhe nën presion.",
    "Kam vështirësi t'i ndihmoj të tjerët të menaxhojnë emocionet e tyre negative.",
    "Mund t'i zgjidh konfliktet në një mënyrë që kënaq të gjitha palët.",
    "Ndihem i mbingarkuar nga emocionet e forta negative dhe nuk i menaxhoj dot mirë.",
  ],
  sw: [
    "Naweza kujua mtu anahisije kwa kuangalia uso wake tu.",
    "Natambua marafiki wanapokuwa na huzuni hata wasiposema.",
    "Naona ugumu kusoma hali ya hisia ndani ya chumba.",
    "Kwa kawaida naweza kujua hali ya mtu kutokana na sauti yake.",
    "Mara nyingi napitwa na ishara ndogo za hisia katika mazungumzo.",
    "Nina uwezo mzuri wa kuelewa hisia za watu kupitia lugha ya mwili.",
    "Naweza kutambua kwa usahihi hisia katika sanaa, muziki au hadithi.",
    "Nikiwa na hali nzuri, huwa napata mawazo mengi zaidi ya ubunifu.",
    "Natumia hisia zangu kuamua nizingatie nini.",
    "Naona ugumu kutumia hisia zangu kujihamasisha.",
    "Hisia zangu hunisaidia kufikiri kwa uwazi zaidi kuhusu matatizo magumu.",
    "Nahangaika kuacha hisia chanya zitie nguvu kazi yangu.",
    "Nalinganisha hali yangu ya hisia na kazi ninayopaswa kufanya, kwa mfano utulivu kwa kazi inayohitaji usahihi.",
    "Naweza kuelekeza shauku kuongeza utendaji wangu.",
    "Naelewa jinsi hisia zinavyoendelea kwa muda, kwa mfano kutoka kero hadi hasira.",
    "Naweza kueleza kwa nini hisia ngumu kama wivu hutokea.",
    "Naona ugumu kueleza kinachosababisha hisia mchanganyiko kwa watu.",
    "Naelewa jinsi hisia kama fahari na aibu zinavyohusiana na taswira ya nafsi.",
    "Mara nyingi sielewi kwa nini watu wanahisi jinsi wanavyohisi.",
    "Naweza kutaja kwa usahihi tofauti ndogo kati ya hisia, kwa mfano wasiwasi dhidi ya hofu.",
    "Naelewa jinsi hisia za nyuma, kama wasiwasi mdogo, zinavyoathiri fikra kwa muda.",
    "Nikiwa nimeudhika, naweza kujituliza haraka kiasi.",
    "Najua jinsi ya kuinua hali ya mtu mwingine akiwa na huzuni.",
    "Huwa nafikiria mara kwa mara na kukwama katika hali mbaya.",
    "Nabaki mtulivu na kufikiri kwa uwazi hata chini ya shinikizo.",
    "Nina ugumu kuwasaidia wengine kudhibiti hisia zao hasi.",
    "Naweza kutatua migogoro kwa njia inayoridhisha pande zote.",
    "Nahisi kuelemewa na hisia hasi kali na siwezi kuzidhibiti vizuri.",
  ],
  th: [
    "ฉันบอกได้ว่าใครรู้สึกอย่างไรเพียงแค่มองที่ใบหน้าของเขา",
    "ฉันสังเกตได้เมื่อเพื่อนไม่สบายใจแม้เขาจะไม่พูดออกมา",
    "ฉันอ่านบรรยากาศทางอารมณ์ในห้องได้ยาก",
    "โดยปกติฉันบอกได้ว่าใครอารมณ์แบบไหนจากน้ำเสียงของเขา",
    "ฉันมักพลาดสัญญาณทางอารมณ์เล็กๆ ในบทสนทนา",
    "ฉันเก่งในการเข้าใจความรู้สึกของผู้คนผ่านภาษากาย",
    "ฉันระบุอารมณ์ในงานศิลปะ ดนตรี หรือเรื่องเล่าได้อย่างแม่นยำ",
    "เมื่ออารมณ์ดี ฉันมักคิดไอเดียสร้างสรรค์ได้มากขึ้น",
    "ฉันใช้ความรู้สึกของตนช่วยตัดสินใจว่าควรมุ่งความสนใจไปที่ใด",
    "ฉันใช้อารมณ์กระตุ้นแรงจูงใจตนเองได้ยาก",
    "อารมณ์ช่วยให้ฉันคิดเรื่องปัญหาซับซ้อนได้ชัดเจนขึ้น",
    "ฉันลำบากที่จะปล่อยให้อารมณ์เชิงบวกเติมพลังให้งานของฉัน",
    "ฉันปรับสภาวะอารมณ์ให้เข้ากับงานที่ต้องทำ เช่น สงบนิ่งสำหรับงานที่ต้องการความแม่นยำ",
    "ฉันแปรความตื่นเต้นให้กลายเป็นแรงผลักดันเพื่อเพิ่มผลงานได้",
    "ฉันเข้าใจว่าอารมณ์ดำเนินไปอย่างไรตามเวลา เช่น จากความรำคาญกลายเป็นความโกรธ",
    "ฉันอธิบายได้ว่าเหตุใดอารมณ์ซับซ้อนอย่างความหึงหวงจึงเกิดขึ้น",
    "ฉันอธิบายสาเหตุของอารมณ์ปนเปในตัวผู้อื่นได้ยาก",
    "ฉันเข้าใจว่าอารมณ์อย่างความภูมิใจและความอับอายเชื่อมโยงกับภาพลักษณ์ของตนอย่างไร",
    "ฉันมักไม่เข้าใจว่าทำไมผู้คนจึงรู้สึกอย่างที่เขารู้สึก",
    "ฉันเรียกชื่อความแตกต่างเล็กน้อยระหว่างอารมณ์ได้อย่างแม่นยำ เช่น ความอึดอัดกับความวิตกกังวล",
    "ฉันเข้าใจว่าอารมณ์พื้นหลังอย่างความกังวลเบาบางส่งผลต่อความคิดตามเวลาอย่างไร",
    "เมื่อไม่สบายใจ ฉันทำให้ตนเองสงบลงได้ค่อนข้างเร็ว",
    "ฉันรู้วิธีทำให้อารมณ์ของคนอื่นดีขึ้นเมื่อเขาเศร้า",
    "ฉันมักครุ่นคิดวนเวียนและติดอยู่ในอารมณ์ที่ไม่ดี",
    "ฉันยังคงสงบและคิดได้ชัดเจนแม้อยู่ภายใต้ความกดดัน",
    "ฉันมีปัญหาในการช่วยผู้อื่นจัดการอารมณ์ด้านลบของเขา",
    "ฉันคลี่คลายความขัดแย้งได้ในแบบที่ทุกฝ่ายพอใจ",
    "ฉันรู้สึกท่วมท้นกับอารมณ์ด้านลบที่รุนแรงและจัดการได้ไม่ดีนัก",
  ],
  ko: [
    "나는 얼굴만 봐도 상대가 어떤 기분인지 알 수 있다.",
    "친구가 말하지 않아도 속상해하는 것을 알아차린다.",
    "방 안의 감정적 분위기를 읽는 것이 어렵다.",
    "목소리만 들어도 상대의 기분을 대개 알 수 있다.",
    "대화에서 미묘한 감정 신호를 놓칠 때가 많다.",
    "몸짓을 통해 사람들의 감정을 잘 파악한다.",
    "예술이나 음악, 이야기 속의 감정을 정확히 알아본다.",
    "기분이 좋을 때 더 창의적인 생각이 떠오른다.",
    "무엇에 집중할지 정할 때 내 감정을 활용한다.",
    "감정을 이용해 스스로에게 동기를 부여하기가 어렵다.",
    "감정은 복잡한 문제를 더 명료하게 생각하도록 도와준다.",
    "긍정적인 감정을 일에 대한 에너지로 돌리는 데 어려움을 느낀다.",
    "해야 할 일에 맞춰 감정 상태를 조절한다. 예를 들어 정밀한 작업에는 차분함을 유지한다.",
    "설렘이나 열의를 성과를 높이는 힘으로 바꿀 수 있다.",
    "감정이 시간에 따라 어떻게 발전하는지 이해한다. 예를 들어 짜증에서 분노로 번지는 과정이다.",
    "질투 같은 복합적인 감정이 왜 생기는지 설명할 수 있다.",
    "사람들에게 복잡한 감정이 생기는 이유를 설명하기 어렵다.",
    "자부심이나 수치심 같은 감정이 자기 이미지와 어떻게 연결되는지 이해한다.",
    "사람들이 왜 그런 감정을 느끼는지 이해하지 못할 때가 많다.",
    "불편함과 불안처럼 미묘한 감정의 차이를 정확히 구분해 이름 붙일 수 있다.",
    "가벼운 걱정 같은 배경 감정이 시간에 따라 사고에 어떤 영향을 주는지 이해한다.",
    "기분이 상했을 때 비교적 빨리 스스로를 진정시킬 수 있다.",
    "슬퍼하는 사람의 기분을 북돋우는 방법을 안다.",
    "생각을 곱씹으며 나쁜 기분에서 벗어나지 못하는 편이다.",
    "압박을 받는 상황에서도 침착하게 명료히 생각한다.",
    "다른 사람이 부정적인 감정을 다루도록 돕는 일이 어렵다.",
    "모두가 만족할 방식으로 갈등을 해결할 수 있다.",
    "강한 부정적 감정에 압도되어 잘 다루지 못한다.",
  ],
  zh: [
    "我只要看对方的表情就能知道他的感受。",
    "即使朋友不说，我也能察觉他们心里不痛快。",
    "我很难读懂一个房间里的情绪氛围。",
    "我通常能从一个人的语气判断他的心情。",
    "我常常错过谈话中细微的情绪信号。",
    "我擅长通过肢体语言理解别人的感受。",
    "我能准确辨认艺术、音乐或故事中的情绪。",
    "心情好的时候，我往往能想出更多有创意的点子。",
    "我会用自己的感受来决定该把注意力放在哪里。",
    "我很难利用情绪来激励自己。",
    "情绪能帮助我更清晰地思考复杂问题。",
    "我很难让积极情绪为我的工作注入动力。",
    "我会让情绪状态配合手上的任务，例如做精细工作时保持平静。",
    "我能把兴奋转化为提升表现的动力。",
    "我理解情绪随时间演变的过程，例如从烦躁发展为愤怒。",
    "我能解释嫉妒这类复杂情绪为何会产生。",
    "我很难说清是什么让别人产生了复杂交织的情绪。",
    "我理解自豪与羞愧这类情绪如何与自我形象相关联。",
    "我常常不明白别人为什么会有那样的感受。",
    "我能准确区分情绪之间的细微差别，例如不安与焦虑。",
    "我理解轻微担忧这类背景情绪如何长期影响思考。",
    "心情不好时，我能比较快地让自己平静下来。",
    "我知道在别人难过时如何让他们振作起来。",
    "我容易反复回想，困在糟糕的情绪里出不来。",
    "即使承受压力，我也能保持镇定并清晰思考。",
    "我很难帮助别人处理他们的负面情绪。",
    "我能以让各方都满意的方式化解冲突。",
    "强烈的负面情绪会让我不知所措，难以妥善应对。",
  ],
};

function itemsFor(lang){
  const t = ITEMS_I18N[lang];
  if (!t) return ITEMS_EN;
  // keep the trait/branch coding from the English master, swap only the text
  return ITEMS_EN.map((it, i) => [t[i] != null ? t[i] : it[0], it[1], it[2]]);
}
let ITEMS = itemsFor(window.I18n?.lang || window.PAGE_LANG || 'en');
document.addEventListener('DOMContentLoaded', () => {
  ITEMS = itemsFor(window.I18n?.lang || window.PAGE_LANG || 'en');
});
const BRANCHES={
  P:{name:'Perceiving Emotions', color:'#f97316', desc:'Your ability to accurately read emotions in faces, voices, and surroundings.'},
  U:{name:'Using Emotions',      color:'#f59e0b', desc:'How well you leverage emotional states to enhance thinking and creativity.'},
  N:{name:'Understanding Emotions', color:'#6366f1', desc:'Your knowledge of emotional dynamics — how they blend, evolve, and influence behavior.'},
  M:{name:'Managing Emotions',   color:'#10b981', desc:'Your capacity to regulate your own emotions and positively influence others.'}
};
const ORDER=['P','U','N','M'];

let current=0, answers={};

function scoreToEQ(raw){
  // Each branch 7 items, 1-5 scale → min 7, max 35
  // Map 7-35 → EQ component score 60-140
  const t=(raw-7)/28; return Math.round(60+t*80);
}
function eqPct(eqScore){
  // EQ 100 = 50th percentile; SD~15
  const z=(eqScore-100)/15;
  return Math.max(1,Math.min(99,Math.round(normalCDF(z)*100)));
}
function normalCDF(z){
  const a=[0.319381530,-0.356563782,1.781477937,-1.821255978,1.330274429];
  const t2=1/(1+0.2316419*Math.abs(z));
  let poly=0,tp=t2; a.forEach(c=>{poly+=c*tp;tp*=t2;});
  const d=0.3989423*Math.exp(-z*z/2)*poly;
  return z>=0?1-d:d;
}
function label(total){
  if(total>=130) return{text:_t('rt_r_exceptional','Exceptional')+' ❤️',color:'#6366f1'};
  if(total>=115) return{text:_t('rt_r_superior','Superior'),color:'#8b5cf6'};
  if(total>=105) return{text:_t('rt_r_above','Above Average'),color:'#10b981'};
  if(total>=95)  return{text:_t('rt_r_average','Average'),color:'#06b6d4'};
  if(total>=85)  return{text:_t('rt_r_below','Below Average'),color:'#f59e0b'};
  return{text:_t('rt_r_practice','Keep Practicing'),color:'#ef4444'};
}

function renderShell(){
  document.getElementById('test-root').innerHTML=`
  <div class="instruction-card">
    <h3>${_t('eq_how_title',"How It Works")}</h3>
    <ul>
      <li>${_t('eq_how0',"{n} statements across the 4 dimensions of emotional intelligence.").replace('{n}',ITEMS.length)}</li>
      <li>${_t('eq_how1',"Rate how accurately each describes you. There are no right or wrong answers.")}</li>
      <li>${_t('eq_how2',"Based on the Mayer-Salovey-Caruso model — the leading scientific EI framework.")}</li>
    </ul>
  </div>
  <div class="test-card-ui">
    <div class="test-ui-header">
      <span class="test-ui-title">❤️ ${_t('eq_title',"Emotional Intelligence Test")}</span>
      <span id="eq-counter" class="q-counter">Q1 / ${ITEMS.length}</span>
    </div>
    <div class="test-ui-body" id="eq-body">
      <p style="color:var(--text-2)">${_t('eq_start_desc',"Discover your EQ across all 4 dimensions of emotional intelligence.")}</p>
      <button class="btn btn-primary" onclick="EQTest.start()">${_t('btn_start_test',"Start Test")}</button>
    </div>
    <div style="padding:12px 24px;border-top:1px solid var(--border)">
      <div class="q-progress-bar"><div class="q-progress-fill" id="eq-prog" style="width:0%"></div></div>
    </div>
  </div>
  <div class="results-panel" id="eq-results"></div>`;
}

function renderQ(){
  const [text,,rev]=ITEMS[current];
  document.getElementById('eq-counter').textContent=`Q${current+1} / ${ITEMS.length}`;
  document.getElementById('eq-prog').style.width=`${(current/ITEMS.length)*100}%`;
  const labels=[1,2,3,4,5].map(n=>[String(n), _t('likert_'+n)]);
  const btns=labels.map(([n,l],i)=>`<button class="likert-btn" onclick="EQTest.answer(${i+1})"><span class="likert-num">${n}</span><span class="likert-label">${l.replace('\n','<br>')}</span></button>`).join('');
  document.getElementById('eq-body').innerHTML=`
    <p class="q-counter">Q${current+1} / ${ITEMS.length}</p>
    <p class="question-text">"${text}"</p>
    <div class="likert">${btns}</div>`;
}

function showResults(){
  const raw={P:0,U:0,N:0,M:0};
  ITEMS.forEach(([,branch,rev],i)=>{
    const a=answers[i]||3; raw[branch]+= rev?(6-a):a;
  });
  const eqScores={};
  ORDER.forEach(b=>{ eqScores[b]=scoreToEQ(raw[b]); });
  const totalEQ=Math.round(ORDER.reduce((s,b)=>s+eqScores[b],0)/ORDER.length);
  const p=eqPct(totalEQ);
  const {text,color}=label(totalEQ);
  const circ=2*Math.PI*55;

  const bars=ORDER.map(b=>{
    const info=BRANCHES[b]; const eq=eqScores[b]; const bp=eqPct(eq);
    const bk='eq_b_'+b.toLowerCase();
    const bname=_t(bk,info.name), bdesc=_t(bk+'_desc',info.desc);
    return `<div class="trait-bar-item">
      <div class="trait-bar-top"><span class="trait-name" style="color:${info.color}">${bname}</span><span class="trait-pct">EQ ${eq}</span></div>
      <div class="trait-bar-track"><div class="trait-bar-fill" style="width:${bp}%;background:${info.color}"></div></div>
      <p style="font-size:.78rem;color:var(--text-2);margin-top:5px">${bdesc}</p>
    </div>`;
  }).join('');

  document.getElementById('eq-results').innerHTML=`
  <div class="result-score-wrap">
    <div class="score-ring-wrap" style="position:relative">
      <svg class="score-ring-svg" viewBox="0 0 130 130" style="width:130px;height:130px;transform:rotate(-90deg)">
        <circle class="score-ring-bg" cx="65" cy="65" r="55"/>
        <circle class="score-ring-fill" id="eq-ring" cx="65" cy="65" r="55"/>
      </svg>
      <div style="position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center">
        <div class="score-ring-num">${totalEQ}</div><div class="score-ring-unit">${_t('eq_result_label',"EQ Score")}</div>
      </div>
    </div>
    <div class="result-info">
      <h2>${text}</h2>
      <p class="result-desc">${totalEQ>=115?_t('eq_res_high',"Your emotional intelligence is genuinely high. You read, use and manage emotions with exceptional skill — a strong predictor of relationship quality and teamwork."):totalEQ>=95?_t('eq_res_mid',"Your EQ is solid and functional. You navigate emotions well in most situations, with room to deepen specific dimensions."):_t('eq_res_low',"Your EQ has room to grow. Emotional intelligence is one of the most trainable skills there is — labelling feelings precisely and deliberate practice both show measurable gains.")}</p>
      <div class="result-percentile" style="background:${color}22;color:${color}">${_t('percentile_prefix',"Better than")} ${p}% ${_t('percentile_suffix',"of people")}</div>
    </div>
  </div>
  <div class="bell-curve-wrap"><canvas id="eq-bell" style="width:100%;display:block"></canvas></div>
  <div class="trait-bars" style="margin-top:20px">${bars}</div>
  <div class="result-breakdown" style="margin-top:20px">
    ${ORDER.map(b=>`<div class="breakdown-item"><div class="b-label">${_t('eq_b_'+b.toLowerCase(),BRANCHES[b].name)}</div><div class="b-val" style="color:${BRANCHES[b].color}">${eqScores[b]}</div></div>`).join('')}
    <div class="breakdown-item"><div class="b-label">${_t('eq_result_label',"EQ Score")}</div><div class="b-val" style="color:${color}">${totalEQ}</div><div class="b-sub">${_t('rt_average',"Average")}: 100</div></div>
  </div>
  <div class="share-row">
    <button class="share-btn" id="share-copy" onclick="EQTest.copy()">📋 ${_t('share_copy',"Copy Result")}</button>
    <button class="share-btn" onclick="EQTest.tweet()">𝕏 ${_t('share_tweet',"Share on X")}</button>
  </div>
  <div style="text-align:center;margin-top:20px"><button class="btn btn-secondary" onclick="EQTest.reset()">↺ ${_t('btn_try_again',"Try Again")}</button></div>`;
  document.getElementById('eq-results').classList.add('show');
  window._eqResult={totalEQ,p,text};
  const ring=document.getElementById('eq-ring');
  ring.style.stroke=color;ring.setAttribute('stroke-dasharray',circ);ring.setAttribute('stroke-dashoffset',circ);
  setTimeout(()=>{ring.style.transition='stroke-dashoffset 1.2s cubic-bezier(.4,0,.2,1)';ring.setAttribute('stroke-dashoffset',circ*(1-p/100));},100);
  setTimeout(()=>document.querySelectorAll('.trait-bar-fill').forEach(b=>{const w=b.style.width;b.style.width='0';setTimeout(()=>{b.style.transition='width 1s cubic-bezier(.4,0,.2,1)';b.style.width=w;},50);}),100);
  requestAnimationFrame(()=>window.drawBellCurve?.('eq-bell',p,color));
}

window.EQTest={
  start(){current=0;answers={};renderQ();},
  answer(val){
    answers[current]=val;
    document.querySelectorAll('.likert-btn').forEach((b,i)=>{ if(i===val-1) b.classList.add('selected'); });
    setTimeout(()=>{ current++; if(current>=ITEMS.length) showResults(); else renderQ(); },280);
  },
  reset(){answers={};current=0;renderShell();},
  copy(){const r=window._eqResult;if(!r)return;const t=window.shareText('eq_result_label', r.totalEQ, r.text, r.p);navigator.clipboard?.writeText(t);},
  tweet(){const r=window._eqResult;if(!r)return;const t=window.shareText('eq_result_label', r.totalEQ, r.text, r.p);window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(t)}&url=${encodeURIComponent(location.href)}`,'_blank','noopener');}
};
document.addEventListener('DOMContentLoaded',renderShell);
})();
